### ISSUE TITLE
Add support for native MacOS/Android/Windows

### ISSUE THREAD

**Issue by zevv** [zevv/duc#100]
Duc compiles mostly clean on MacOS and Android, but this requires cairo, pango and X11. Would be nice to add a native android java and/or macos objective C/quartz app.

**Comment by zevv** [comment]
I've started a new branch that supports multiple graphics backends; cairo support works as it did before, but now also supports OpenGL (ES). Added new command duc-guigl (currently for X11,  should be rewritten to run on top of EGL for portability)

**Comment by stuartthebruce** [comment]
> On May 29, 2015, at 10:28 AM, Ico Doornekamp <notifications@github.com> wrote:
> 
> I've started a new branch that supports multiple graphics backends; cairo support works as it did before, but now also supports OpenGL (ES). Added new command duc-guigl (currently for X11, should be rewritten to run on top of EGL for portability)
> 
> 

FWIW, I just tried the opengl2 branch on OS X Yosemite and ./configure passed but make generated the following warning and error:


src/libduc-graph/graph-cairo.c:217:9: warning: enumeration values 'DUC_GRAPH_FORMAT_SVG' and
      'DUC_GRAPH_FORMAT_PDF' not handled in switch [-Wswitch]
        switch(bd->fmt) {
               ^
1 warning generated.


src/libduc-graph/graph-opengl.c:23:10: fatal error: 'GLES3/gl3.h' file not found
#include <GLES3/gl3.h>
         ^
1 error generated.
make[1]: *** [src/libduc-graph/graph-opengl.o] Error 1
make: *** [all] Error 2


--
Stuart Anderson  anderson@ligo.caltech.edu
http://www.ligo.caltech.edu/~anderson

**Comment by zevv** [comment]
short status update for those interested:

- The opengl2 branch now works fine for me. duc-guigl switched to libglut for window setup, so there's no longer a dependency on X11. Probably quite close to a native macos build.

- I've been able to compile the code base for android using freeglut; Duc runs as a native binary and is able to index and list on the cmdline. `duc guigl` starts, but nothing shows on the screen. I'm afraid this will require messing with Java to make it into a proper behaving android app, but the low level stuff seems to be in place.

What's missing is mostly autoconf stuff for proper detecting libraries and enabling/disabling cairo/pango/X11/glut/GLES/openGL stuff. No fun.

**Comment by stuartthebruce** [comment]
> On May 30, 2015, at 10:01 AM, Ico Doornekamp <notifications@github.com> wrote:
> 
> short status update for those interested:
> 
> The opengl2 branch now works fine for me. duc-guigl switched to libglut for window setup, so there's no longer a dependency on X11. Probably quite close to a native macos build.
> 
> I've been able to compile the code base for android using freeglut; Duc runs as a native binary and is able to index and list on the cmdline. duc guigl starts, but nothing shows on the screen. I'm afraid this will require messing with Java to make it into a proper behaving android app, but the low level stuff seems to be in place.
> 
> What's missing is mostly autoconf stuff for proper detecting libraries and enabling/disabling cairo/pango/X11/glut/GLES/openGL stuff. No fun.
> 
> 

What arguments should be given to ./configure for OS X? The build error I get has changed from missing gl3.h to missing gl2.h,

src/libduc-graph/graph-opengl.c:22:10: fatal error: 'GLES2/gl2.h' file not found
#include <GLES2/gl2.h>
         ^
1 error generated.
make[1]: *** [src/libduc-graph/graph-opengl.o] Error 1

Thanks.

--
Stuart Anderson  anderson@ligo.caltech.edu
http://www.ligo.caltech.edu/~anderson

**Comment by zevv** [comment]
* On 2015-05-30 20:45:18 +0200, stuartthebruce wrote:
 
> What arguments should be given to ./configure for OS X? The build
> error I get has changed from missing gl3.h to missing gl2.h,

I'm trying to get my hands on a mac os machine myself to properly test
this. It seems that the compiler needs some apple-specific flags to
include 'frameworks', something like

    CFLAGS="-framework OpenGL -framework GLUT"

Apart from that the OpengL headers are in a platform specific location,
so ther will need to be some autoconf stuff added to find the proper
header files.

Also the current shaders require shader language version 330, which is
not supported on Mac OS. I'll have to work a bit on this as well.

I hoped OpenGL would make things easier, but there's still a lot of
platform specific stuff to tweak.



If you feel lucky and have some time to spare, continue reading. Otherwise it's
probabbly safer to wait until I got things properly tested and added myself.



Below is a diff which makes duc compile for me on macos. I don't see the
screen from here (I'm logged on via SSH), so not sure if there is any
window or image coming up at all :)

Build with

    make CFLAGS="-framework OpenGL -framework GLUT"


diff --git a/src/duc/cmd-guigl.c b/src/duc/cmd-guigl.c
index cdcc5e7..dcb1d11 100644
--- a/src/duc/cmd-guigl.c
+++ b/src/duc/cmd-guigl.c
@@ -7,7 +7,7 @@
 #include "ducrc.h"
 #include "cmd.h"
 
-#ifdef HAVE_LIBGLUT
+#if 1
 
 #include <stdio.h>
 #include <ctype.h>
@@ -18,8 +18,8 @@
 
 #include <string.h>
 
-#include <GL/gl.h>
-#include <GL/glut.h>
+#include <OpenGL/gl.h>
+#include <GLUT/glut.h>
 
 static int opt_bytes;
 static int opt_dark;
diff --git a/src/duc/cmd-ui.c b/src/duc/cmd-ui.c
index ca6d274..5ccff9e 100644
--- a/src/duc/cmd-ui.c
+++ b/src/duc/cmd-ui.c
@@ -24,7 +24,7 @@
 #endif
 #endif
 #ifdef HAVE_LIBNCURSESW
-#include <ncursesw/ncurses.h>
+#include <ncurses.h>
 #endif
 
 enum {
diff --git a/src/libduc-graph/graph-opengl.c b/src/libduc-graph/graph-opengl.c
index 2634392..0f1a3dc 100644
--- a/src/libduc-graph/graph-opengl.c
+++ b/src/libduc-graph/graph-opengl.c
@@ -19,7 +19,8 @@
 #include <stdint.h>
 #include <libgen.h>
 
-#include <GLES2/gl2.h>
+//#include <OpenGL/OpenGL.h>
+#include <OpenGL/GL.h>
 
 #include "private.h"
 #include "duc.h"
@@ -40,31 +41,28 @@ struct opengl_backend_data {
 	GLuint loc_color;
 };
 
-static const GLchar *vshader = 
-	"#version 330 core\n"
-	"uniform mat4 matrix;\n"
-	"in vec4 pos_in;\n"
-	"in vec2 tex_in;\n"
-	"in vec4 color_in;\n"
-	"out vec2 tex_out;\n"
-	"out vec4 color;\n"
-	"void main()\n"
-	"{\n"
-	"	gl_Position = matrix * pos_in;\n"
-	"       tex_out = tex_in;\n"
-	"       color = color_in;\n"
-	"}\n";
-
+ static const GLchar *vshader =
+          "uniform mat4 matrix;\n"
+         "attribute vec4 pos_in;\n"
+         "attribute vec2 tex_in;\n"
+         "attribute vec4 color_in;\n"
+         "varying vec2 tex_out;\n"
+         "varying vec4 color;\n"
+          "void main()\n"
+          "{\n"
+          "       gl_Position = matrix * pos_in;\n"
+          "       tex_out = tex_in;\n"
+          "       color = color_in;\n"
+          "}\n";
+  
 static const GLchar *fshader = 
-	"#version 330 core\n"
-	"uniform sampler2D Texture;\n"
-	"in vec4 color;\n"
-	"in lowp vec2 tex_out;\n"
-	"out vec4 outV;\n"
-	"void main()\n"
-	"{\n"
-	"	outV = color + texture2D(Texture, tex_out);\n"
-	"}\n";
+        "uniform sampler2D Texture;\n"
+        "varying vec4 color;\n"
+        "varying vec2 tex_out;\n"
+        "void main()\n"
+        "{\n"
+        "       gl_FragColor = color + texture2D(Texture, tex_out);\n"
+        "}\n";
 
 

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by zevv** [comment]
@stuartthebruce: I just verified a working macos build with the opengl2 branch

    CFLAGS="-framework OpenGL -framework GLUT" \
    LDFLAGS=-L/opt/local/lib \
    ./configure --disable-cairo --disable-x11 --disable-ui --enable-opengl

Visually it's not as nice as the cairo due to ugly font rendering and lack of antialiasing though.

**Comment by zevv** [comment]
Duc changed from GLUT to GLFW for platform independent window handling. Compile on Mac OS X with:

    CFLAGS="-I/opt/local/include -framework OpenGL" \ 
    LDFLAGS=-L/opt/local/lib \
    ./configure --disable-cairo --disable-x11 --disable-ui --enable-opengl --with-db-backend=sqlite3

**Comment by stuartthebruce** [comment]
> On Jun 1, 2015, at 8:59 AM, Ico Doornekamp <notifications@github.com> wrote:
> 
> Duc changed from GLUT to GLFW for platform independent window handling. Compile on Mac OS X with:
> 
> CFLAGS="-I/opt/local/include -framework OpenGL" \ 
> LDFLAGS=-L/opt/local/lib \
> ./configure --disable-cairo --disable-x11 --disable-ui --enable-opengl --with-db-backend=sqlite3

Here is what I get on my Yosemite machine,

	gcc -DHAVE_CONFIG_H -I.    -I/opt/local/include  -Isrc/libduc -Isrc/libduc-graph -I/opt/local/include -framework OpenGL -MT src/duc/cmd-gui.o -MD -MP -MF $depbase.Tpo -c -o src/duc/cmd-gui.o src/duc/cmd-gui.c &&\
	mv -f $depbase.Tpo $depbase.Po
clang: warning: -framework OpenGL: 'linker' input unused
depbase=`echo src/duc/cmd-guigl.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	gcc -DHAVE_CONFIG_H -I.    -I/opt/local/include  -Isrc/libduc -Isrc/libduc-graph -I/opt/local/include -framework OpenGL -MT src/duc/cmd-guigl.o -MD -MP -MF $depbase.Tpo -c -o src/duc/cmd-guigl.o src/duc/cmd-guigl.c &&\
	mv -f $depbase.Tpo $depbase.Po
clang: warning: -framework OpenGL: 'linker' input unused
src/duc/cmd-guigl.c:52:19: error: unknown type name 'GLFWwindow'
static void sc2fb(GLFWwindow* window, double *x, double *y)
                  ^
src/duc/cmd-guigl.c:55:2: warning: implicit declaration of function 'glfwGetFramebufferSize' is invalid in C99
      [-Wimplicit-function-declaration]
        glfwGetFramebufferSize(window, &w1, &h1);
        ^
src/duc/cmd-guigl.c:56:2: warning: implicit declaration of function 'glfwGetWindowSize' is invalid in C99
      [-Wimplicit-function-declaration]
        glfwGetWindowSize(window, &w2, &h2);
        ^
…

Thanks.

--
Stuart Anderson  anderson@ligo.caltech.edu
http://www.ligo.caltech.edu/~anderson

**Comment by zevv** [comment]
@stuartthebruce: please try 'port install glfw' and retry

I've just merged the opengl2 branch to master. Native Mac OS X support is mostly in place, win32 support would be trivial.

**Comment by stuartthebruce** [comment]
> On Jun 4, 2015, at 12:56 PM, Ico Doornekamp <notifications@github.com> wrote:
> 
> @stuartthebruce <https://github.com/stuartthebruce>: please try 'port install glfw' and retry
> 
> I've just merged the opengl2 branch to master. Native Mac OS X support is mostly in place, win32 support would be trivial.
> 


./configure —enable-opengl fails unless I point CFLAGS at my macport installation,
env CFLAGS=“-I/opt/local/include" ./configure --enable-opengl --disable-x11
however, that fails to define HAVE_GLFW_GLFW3_H in config.h 

If I add that manually I then get the following missing symbols,

gcc -I/opt/local/include/cairo -I/opt/local/include/glib-2.0 -I/opt/local/lib/glib-2.0/include -I/opt/local/include -I/opt/local/include/pixman-1 -I/opt/local/include -I/opt/local/include/freetype2 -I/opt/local/include -I/opt/local/include/libpng16 -I/opt/local/include -I/opt/local/include/freetype2 -I/opt/local/include/libpng16 -I/opt/local/include  -D_REENTRANT -I/opt/local/include/pango-1.0 -I/opt/local/include/glib-2.0 -I/opt/local/lib/glib-2.0/include -I/opt/local/include  -D_REENTRANT -I/opt/local/include/pango-1.0 -I/opt/local/include/cairo -I/opt/local/include/pixman-1 -I/opt/local/include/libpng16 -I/opt/local/include -I/opt/local/include/pango-1.0 -I/opt/local/include/harfbuzz -I/opt/local/include/pango-1.0 -I/opt/local/include/glib-2.0 -I/opt/local/lib/glib-2.0/include -I/opt/local/include -I/opt/local/include/freetype2 -I/opt/local/include -I/opt/local/include/libpng16 -I/opt/local/include -I/opt/local/include/freetype2 -I/opt/local/include   -Isrc/libduc -Isrc/libduc-graph -I/opt/local/include   -o duc src/libduc/buffer.o src/libduc/db.o src/libduc/db-tokyo.o src/libduc/db-leveldb.o src/libduc/db-sqlite3.o src/libduc/dir.o src/libduc/duc.o src/libduc/index.o src/libduc/stripdir.o src/libduc/varint.o src/libduc-graph/graph.o src/libduc-graph/graph-cairo.o src/libduc-graph/graph-opengl.o src/duc/cmd-cgi.o src/duc/cmd-graph.o src/duc/cmd-gui.o src/duc/cmd-guigl.o src/duc/cmd-index.o src/duc/cmd-info.o src/duc/cmd-ls.o src/duc/cmd-ui.o src/duc/cmd-xml.o src/duc/ducrc.o src/duc/main.o -L/opt/local/lib -lcairo  -L/opt/local/lib -lpango-1.0 -lm -lgobject-2.0 -lglib-2.0 -lintl  -L/opt/local/lib -lpangocairo-1.0 -lcairo -lpangoft2-1.0 -lpango-1.0 -lm -lgobject-2.0 -lglib-2.0 -lintl -lfontconfig -lfreetype  -L/opt/local/lib -ltokyocabinet -lbz2 -lz -lpthread -lm -lc  -lncurses -lm 
Undefined symbols for architecture x86_64:
  "_glActiveTexture", referenced from:
      _draw_char in graph-opengl.o
  "_glAttachShader", referenced from:
      _shaders in graph-opengl.o
  "_glBindTexture", referenced from:
      _duc_graph_new_opengl in graph-opengl.o
      _draw_char in graph-opengl.o

--
Stuart Anderson  anderson@ligo.caltech.edu
http://www.ligo.caltech.edu/~anderson

**Comment by zevv** [comment]
This works for me

    CFLAGS="-I/opt/local/include -framework OpenGL" \
    LDFLAGS="-L/opt/local/lib" \
    ./configure --disable-cairo --disable-x11 --disable-ui --enable-opengl

I'm not sure if/how autoconf should find this out without hints from
the user though.

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by stuartthebruce** [comment]
> On Jun 4, 2015, at 9:42 PM, Ico Doornekamp <notifications@github.com> wrote:
> 
> 
> This works for me
> 
> CFLAGS="-I/opt/local/include -framework OpenGL" \
> LDFLAGS="-L/opt/local/lib" \
> ./configure --disable-cairo --disable-x11 --disable-ui --enable-opengl
> 
> I'm not sure if/how autoconf should find this out without hints from
> the user though.

That command creates a config.h file that does not define HAVE_GLFW_GLFW3_H that is needed at compile time even though that is available,

MBP:duc> grep HAVE_GLFW_GLFW3_H config.h
MBP:duc> ls -l /opt/local/include/GLFW/glfw3.h
-rw-r--r--  1 root  admin  115643 May 29 04:15 /opt/local/include/GLFW/glfw3.h

Thanks.

--
Stuart Anderson  anderson@ligo.caltech.edu
http://www.ligo.caltech.edu/~anderson
