### ISSUE TITLE
Follow freedesktop standards for configuration and database file

### ISSUE THREAD

**Issue by zevv** [zevv/duc#103]
Instead of writing to ~/.duc.db, Duc should follow the XDG standards for cache and config file locations.

http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by zevv** [comment]
9a6a12e implements reading config from `~/.config/duc/ducrc` as well as the old path `~/.duc.db`.

Ideally the database should go to `~/.cache/duc` instead of `~/.duc.db`, but this will break working systems. A good time to change this is when the database format has to change and the db version goes up, because old databases will be obsolete anyway.

**Comment by l8gravely** [comment]
>>>>> "Ico" == Ico Doornekamp <notifications@github.com> writes:

Ico> 9a6a12e implements reading config from ~/.config/duc/ducrc as
Ico> well as the old path ~/.duc.db.

Ico> Ideally the database should go to ~/.cache/duc instead of
Ico> ~/.duc.db, but this will break working systems. A good time to
Ico> change this is when the database format has to change and the db
Ico> version goes up, because old databases will be obsolete anyway.

It would be nice if when duc tried to read an old database, it errored
out with the version mismatch info, so people could maybe figure out
how old it was?

**Comment by zevv** [comment]
* On 2016-10-16 00:24:38 +0200, John wrote:
 
> >>>>> "Ico" == Ico Doornekamp <notifications@github.com> writes:
> 
> Ico> 9a6a12e implements reading config from ~/.config/duc/ducrc as
> Ico> well as the old path ~/.duc.db.
> 
> Ico> Ideally the database should go to ~/.cache/duc instead of
> Ico> ~/.duc.db, but this will break working systems. A good time to
> Ico> change this is when the database format has to change and the db
> Ico> version goes up, because old databases will be obsolete anyway.
> 
> It would be nice if when duc tried to read an old database, it errored
> out with the version mismatch info, so people could maybe figure out
> how old it was?

We could put something like that in it for some time to help people
switch, but I'd like to drop legacy stuff after some time so we don't
need to support this for ages.

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by zevv** [comment]
* On 2016-10-16 00:24:38 +0200, John wrote:
 
> >>>>> "Ico" == Ico Doornekamp <notifications@github.com> writes:
> 
> Ico> 9a6a12e implements reading config from ~/.config/duc/ducrc as
> Ico> well as the old path ~/.duc.db.
> 
> Ico> Ideally the database should go to ~/.cache/duc instead of
> Ico> ~/.duc.db, but this will break working systems. A good time to
> Ico> change this is when the database format has to change and the db
> Ico> version goes up, because old databases will be obsolete anyway.
> 
> It would be nice if when duc tried to read an old database, it errored
> out with the version mismatch info, so people could maybe figure out
> how old it was?

What about this: we simple change the path of the database to the new
path ~/.cache/duc/duc.db, so indexing and reading uses only this file.
The old ~/.duc.db is never touch again.

We add a tiny snippet of code that simply checks if a file ~/.duc.db
exists, and emits a warning if found - nothing else. This prevents
confusion about which file is actually being used but helps people
migrate to the new setup.

-- 
:wq
^X^Cy^K^X^C^C^C^C
