### ISSUE TITLE
Add SVG graph backend

### ISSUE THREAD

**Issue by zevv** [zevv/duc#104]
Duc now supports multiple backends for generating graphics: cairo/pango and OpenGL. 

A SVG backend (just printf, not built on top of cairo) should be easy to add, allowing Duc to run with minimal dependencies on embedded systems and small file servers like Synlogogy and QNAP.

**Comment by zevv** [comment]
Implemented in da066ec..a84c174

**Comment by olivluca** [comment]
Am I reading the source wrong or the cgi still uses cairo? If it is so, would it be possible to use svg even for the cgi?

**Comment by olivluca** [comment]
Mmh , just saw issue #84

**Comment by zevv** [comment]
* On 2015-06-11 19:56:55 +0200, Luca Olivetti wrote:
 
> Am I reading the source wrong or the cgi still uses cairo? If it is
> so, would it be possible to use svg even for the cgi?

CGI is indeed still using cairo. I did some research (see #84) some time
ago and found out that SVG from cairo results in huge files. The
printf() generated SVG seems much nicer, so it would be feasible to make
the CGI switch SVG.

With the modular drawing backend there's another solution: instead of
using SVG, the duc-graph code generates a stream of minimal javascript
which renders the graph onto a HTML5 canvas. Not sure yet about the
advantages/disadvantages though.

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by olivluca** [comment]
Well, the advantage would be removing the dependency on cairo, though it's not a big deal.

**Comment by zevv** [comment]
* On 2015-06-11 20:15:09 +0200, Luca Olivetti wrote:
 
> Well, the advantage would be removing the dependency on cairo, though it's not a big deal.

That is indeed an advantage, but I meant the two alternative
implementations: rendering SVG, or rendering javascript which renders
the graph on a canvas

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by zevv** [comment]
I've just added a html5/javascript/canvas back end as well. The resulting data is about 8 times smaller for JS then for SVG, so this seems like a good candidate for integration into the CGI. This will completely drop cairo/pango dependencies for the CGI, which is a nice pro on headless servers.

**Comment by l8gravely** [comment]
Ico> I've just added a html5/javascript/canvas back end as well. The
Ico> resulting data is about 8 times smaller for JS then for SVG, so
Ico> this seems like a good candidate for integration into the CGI.
Ico> This will completely drop cairo/pango dependencies for the CGI,
Ico> which is a nice pro on headless servers.

Sorry I've been so out of it lately, but this is great work, I can't
wait to try it... though it will probably be a month before I find the
time.  Way way way too busy...

I wish I could buy you a beer or three to thank you for all your work
on this!
John

**Comment by zevv** [comment]
* On 2015-06-12 02:56:59 +0200, John wrote:
 
> I wish I could buy you a beer or three to thank you for all your work
> on this!

I have a memory like an elephant for beer promises, so if we ever meet,
you'll know what to do :)

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by olivluca** [comment]
Maybe it's me (I refreshed from git master after seeing the announcement), but there's a couple of problem with the cgi command now:

1) the directories in the image are not clickable
2) the table (with the --list) option, doesn't show the biggest directories as it did before

1 coupled with 2 makes it difficult to drill down and see where the space is gone

E.g. in the following image, rpm, gparted, servidor, etc., should be at the top of the list

![duc](https://cloud.githubusercontent.com/assets/8250980/8128906/fcc57766-1103-11e5-942d-c4ae672e8014.png)

"duc list" shows them in the correct order (biggest to smallest)

OTOH, loading of the page with the image on the canvas is much faster than loading the previous png generated separately.

I configured with:

autoreconf
./configure --disable-ui --disable-gui --disable-cairo --disable-x11

**Comment by olivluca** [comment]
These are the first lines of output of "duc list" on the same directory as above:

882.9M rpm
516.4M plone2.5
355.6M gparted
337.5M zeotest
304.0M export
223.7M zopetest
189.0M puppy
152.9M samba-3.6.24
142.4M nuevo-zope
129.3M clonezilla-live-2.2.3-10-i486.zip

**Comment by zevv** [comment]
-problem 1: not able to click on the directory. What browser are you using? Does your browser have a javascript console where you can check if there are any JS errors?

-problem 2: the wrong list: Yes, I just noticed and fixed this about an hour ago. Because the image is now generated inline in the CGI, the code generating the HTML page with the index shared the directory object with the graph drawing. The graph iterates the directory listing until the sections get smaller then 1 pixel, but it was not rewound. All the items in the list are the ones that did make it into the graph.

The fix was simply to rewind the directory before drawing the list. Unfortunately this was too late to go into the 1.3 release, again due to improper testing by myself. (The user base is still a tad too small to catch these things for me)

I think this deserves a bugfix release, so expect a 1.3.1 version one of these days.

**Comment by zevv** [comment]
Is the demo at http://duc.zevv.nl/demo.cgi?x=430&y=374&path=/usr/share clickable for you?

**Comment by olivluca** [comment]
Yes, it is, I just found it is clickable only if I add the option --tooltip (which I just did).

**Comment by zevv** [comment]
* On 2015-06-12 13:37:25 +0200, Luca Olivetti wrote:
 
> Yes, it is, I just found it is clickable only if I add the option --tooltip (which I just did).

You're absolutely right. Fixed in git master.

(The old implementation used image maps for clicking, the new
implementation uses javascript but used part of the infratstructure that
was only generated when tooltips were enabled)

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by olivluca** [comment]
Great, thank you.
