### ISSUE TITLE
Problem finding font.c when building 1.3.2 tarball with opengl on Mac

### ISSUE THREAD

**Issue by stuartthebruce** [zevv/duc#107]
env LDFLAGS=-L/opt/X11/lib ./configure --enable-opengl

src/libduc-graph/graph-opengl.c:33:10: fatal error: 'font.c' file not found
#include "font.c"
         ^
1 error generated.
make[1]: *** [src/libduc-graph/graph-opengl.o] Error 1

FWIW, font.c is also reported as not found when disabling cairo and x11
./configure --enable-opengl --disable-cairo --disable-x11

How about adding a short blurb in INSTALL indicating a recommended set of options for Mac users (given the current problems with pango in macports generating useless fonts in gui mode).

**Comment by zevv** [comment]
* On 2015-06-14 19:39:20 +0200, stuartthebruce wrote:
 
> env LDFLAGS=-L/opt/X11/lib ./configure --enable-opengl
> 
> src/libduc-graph/graph-opengl.c:33:10: fatal error: 'font.c' file not found
> #include "font.c"
>          ^
> 1 error generated.
> make[1]: *** [src/libduc-graph/graph-opengl.o] Error 1

And another one. That is one of the problems with all these compile time
options.

> FWIW, font.c is also reported as not found when disabling cairo and
> x11 ./configure --enable-opengl --disable-cairo --disable-x11
> 
> How about adding a short blurb in INSTALL indicating a recommended set
> of options for Mac users (given the current problems with pango in
> macports generating useless fonts in gui mode).

I'll look into that!
 

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by zevv** [comment]
* On 2015-06-14 19:39:20 +0200, stuartthebruce wrote:
 
> env LDFLAGS=-L/opt/X11/lib ./configure --enable-opengl
> 
> src/libduc-graph/graph-opengl.c:33:10: fatal error: 'font.c' file not found
> #include "font.c"
>          ^
> 1 error generated.
> make[1]: *** [src/libduc-graph/graph-opengl.o] Error 1
> 
> FWIW, font.c is also reported as not found when disabling cairo and x11
> ./configure --enable-opengl --disable-cairo --disable-x11
> 
> How about adding a short blurb in INSTALL indicating a recommended set of options for Mac users (given the current problems with pango in macports generating useless fonts in gui mode).

I have no access to a Mac OS machine on the short term. I'm not sure if
the command below still works:

    CFLAGS="-I/opt/local/include -framework OpenGL" \
    LDFLAGS="-L/opt/local/lib" \
    ./configure --disable-cairo --disable-x11 --disable-ui --enable-opengl

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by stuartthebruce** [comment]
1.3.3 tarball does indeed have font.c. The following is sufficient to compile on my Yosemite laptop,
./configure --enable-opengl --disable-cairo --disable-x11
There is certainly no reason that I am aware of to recommend "--disable-ui". However, the above build when running guigl generates a new window with "Hello World" in title bar that is black until I move the cursor and then I see a lot of flashing random pixel maps.

Note, it was not necessary to specify -I or -L to get this compiled and linked against macports software in /opt/local, e.g.,
MBP:duc-1.3.3> ldd ./duc
./duc:
	/opt/local/lib/libtokyocabinet.9.dylib (compatibility version 9.0.0, current version 9.11.0)
	/opt/local/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.6)
	/opt/local/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
	/opt/local/lib/libglfw.3.dylib (compatibility version 3.0.0, current version 3.1.0)
	/opt/local/lib/libGL.1.dylib (compatibility version 4.0.0, current version 4.0.0)
	/opt/local/lib/libncurses.5.dylib (compatibility version 5.0.0, current version 5.0.0)

P.S. Why create a new command "guigl" rather than just calling it "gui" independent of what GUI framework is used?

**Comment by zevv** [comment]
* On 2015-06-14 20:34:49 +0200, stuartthebruce wrote:
 
> 1.3.3 tarball does indeed have font.c. The following is sufficient to compile on my Yosemite laptop,
> ./configure --enable-opengl --disable-cairo --disable-x11

Great. That's probably becuase GLFW3 is now included by pkg-config,
which takes care of all the dependencies for building.

> There is certainly no reason that I am aware of to recommend
> "--disable-ui". 

I've had a discussion on the MacPorts irc channel, and there was some
confusion about the ncurses/ncursesw package. I did my tests without the
curses ui, but if it works for you I guess there is no problem there.

> However, the above build when running guigl generates a new window
> with "Hello World" in title bar that is black until I move the cursor
> and then I see a lot of flashing random pixel maps.

Well, that's interesting, I really wonder what's happening here. It's a
shame I do not have easy access to a Mac myself, this makes testing 
quite hard to do.

> Note, it was not necessary to specify -I or -L to get this compiled
> and linked against macports software in /opt/local, e.g.,

See the above, I guess these are all provided by GLFW3's pkg-config
configuration.

> P.S. Why create a new command "guigl" rather than just calling it
> "gui" independent of what GUI framework is used?

The OpenGL GUI is still a kind of experimental (hence --enable-opengl
instead of --disable-opengl), but my plan is indeed to have this replace
the 'gui' command. My biggest issue at this time with the OpengL code is
that text rendering is far from trivial, and the current fixed bitmap
fonts end up way to small on a Mac with high resolution display.

 

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by zevv** [comment]
I'm able to reproduce the 'noise' on Mac OS X. I have no clue why and how, but forcing the '-framework OpenGL' on the LDFLAGS solves the problem for me.

So complete recipe that works for me on Mac OS is now:

````
./configure --enable-opengl --disable-cairo --disable-x11
make LDFLAGS="-framework OpenGL"
````

**Comment by stuartthebruce** [comment]
That works for me as well, though as previously indicated the font is rather small.

**Comment by zevv** [comment]
* On 2015-06-16 03:20:41 +0200, stuartthebruce wrote:
 
> That works for me as well, though as previously indicated the font is rather small.

That should be solved in git master

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by stuartthebruce** [comment]
opengl fonts from git master look much better on Yosemite now.

Note, the following compile warnings might be worth cleaning up,

src/libduc/duc.c:264:12: warning: comparison of unsigned enum expression >= 0 is always true [-Wtautological-compare]
        return (t >= 0 && t <= DUC_FILE_TYPE_UNKNOWN) ? duc_file_type_list[t].c : ' ';
                ~ ^  ~
src/libduc/duc.c:270:12: warning: comparison of unsigned enum expression >= 0 is always true [-Wtautological-compare]
        return (t >= 0 && t <= DUC_FILE_TYPE_UNKNOWN) ? duc_file_type_list[t].s : " ";
                ~ ^  ~

src/libduc-graph/graph-opengl.c:403:2: warning: implicit declaration of function 'glGenerateMipmap' is invalid in C99
      [-Wimplicit-function-declaration]
        glGenerateMipmap(GL_TEXTURE_2D);
