### ISSUE TITLE
CGI selecteds wrong location on iOS zoomed image

### ISSUE THREAD

**Issue by stuartthebruce** [zevv/duc#109]
After zooming in on a DUC 1.3.3 image displayed via cgi from a Linux Apache server on an iPhone running iOS 8.3 it appears that there is a coordinate translation issue and the wrong location in the graph is selected. The same problem does not occur when the initial image is not zoomed.

**Comment by zevv** [comment]
Oh, wow, an invitation to Javascript Hell :) I don't own any iOS devices so I'll have to figure out how to fix that.

(Anyone reading this who owns an i[Phone|Pad] and is willing to look into a bit of javascript?)

**Comment by l8gravely** [comment]
Is this fixed in v1.4.1 since that issue with viewport not being right when the display was scrolled was fixed?  I suspect this is the same issue.  Don't have anything to check with right now myself.

**Comment by stuartthebruce** [comment]
> On Oct 20, 2016, at 12:34 PM, John <notifications@github.com> wrote:
> 
> Is this fixed in v1.4.1 since that issue with viewport not being right when the display was scrolled was fixed? I suspect this is the same issue. Don't have anything to check with right now myself.


Different behavior with 1.4.1 (and iOS 10.0.2). If I select a region on a zoomed image I no longer get a wrong display of a different part of the graph, instead I get back to a full unzoomed image rather then a view of the selected part.

--
Stuart Anderson  anderson@ligo.caltech.edu
http://www.ligo.caltech.edu/~anderson

**Comment by stuartthebruce** [comment]
I can confirm this is now working with 1.4.3 + https://github.com/zevv/duc/issues/129.
