### ISSUE TITLE
Errors creating RPM with Mock on Centos 6.6

### ISSUE THREAD

**Issue by refrain** [zevv/duc#110]
Centos 6.6

Getting some errors when using mock to create RPMs for duc:

make[2]: Entering directory `/builddir/build/BUILD/duc-master'
/sbin/ldconfig || :;
/sbin/ldconfig: Can't create temporary cache file /etc/ld.so.cache~: Permission denied

and

RPM build errors:
error: File not found by glob: /builddir/build/BUILDROOT/duc-1.0-1.el6.x86_64/usr/lib64/*.so*
    File not found by glob: /builddir/build/BUILDROOT/duc-1.0-1.el6.x86_64/usr/lib64/*.so*
Child return code was: 1

**Comment by zevv** [comment]
I'm afraid I can't help you on this one. The .spec was contributed by @edospadoni some time ago, but since I don't run Redhat or CentOS myself I'm not able to test and/or fix. Sorry for that!
