### ISSUE TITLE
version 1.3.3 truncates info -b output

### ISSUE THREAD

**Issue by stuartthebruce** [zevv/duc#112]
duc version 1.3.3 truncates the Size output in byte mode before getting to PB, e.g.,

# duc --version
duc version: 1.3.3
options: cairo x11 ui tokyocabinet

# duc info -a -d archive.duc
Date       Time       Files    Dirs    Size Path
2015-07-04 00:30:02  186.6M  119.6K    4.6P /archive/frames

# duc info -a -b -d archive.duc
Date       Time       Files    Dirs    Size Path
2015-07-04 00:30:02 186645797  119570 515404729721573 /archive/frames

There should be another digit in the last size output.

**Comment by zevv** [comment]
Thans, fixed in master.
