### ISSUE TITLE
version ambiguity

### ISSUE THREAD

**Issue by stuartthebruce** [zevv/duc#113]
After building from  master "duc --version"  generates,
duc version: 1.3.3
options: cairo x11 ui tokyocabinet
which is confusing since it is different and incompatible with actual 1.3.3 builds, e.g.,
Error opening: archive.duc - Database version mismatch
Database version mismatch

It would be useful if both "--version" was more specific and the database version number in a file was exposed via some command as well as referenced in the error message.

**Comment by zevv** [comment]
I'll make sure version numbers and internal db version will be better coupled in the future, and added a FAQ in the docs.
