### ISSUE TITLE
Problem linking master on Solaris 11

### ISSUE THREAD

**Issue by stuartthebruce** [zevv/duc#114]
I am no longer able to link a 64-bit version from master on Solaris 11.

gmake results in,

Undefined first referenced
symbol in file
g_weak_ref_clear /opt/csw/lib/amd64/libpangoft2-1.0.so.0
pango_font_map_changed /opt/csw/lib/amd64/libpangoft2-1.0.so.0
g_unicode_script_to_iso15924 /opt/csw/lib/amd64/libharfbuzz.so.0
g_atomic_int_dec_and_test /opt/csw/lib/amd64/libpangoft2-1.0.so.0
g_atomic_int_inc /opt/csw/lib/amd64/libpangoft2-1.0.so.0
g_unichar_compose /opt/csw/lib/amd64/libharfbuzz.so.0
g_unichar_decompose /opt/csw/lib/amd64/libharfbuzz.so.0
g_unichar_fully_decompose /opt/csw/lib/amd64/libharfbuzz.so.0
g_weak_ref_get /opt/csw/lib/amd64/libpangoft2-1.0.so.0
g_weak_ref_set /opt/csw/lib/amd64/libpangoft2-1.0.so.0
g_unicode_script_from_iso15924 /opt/csw/lib/amd64/libharfbuzz.so.0
ld: fatal: symbol referencing errors
collect2: ld returned 1 exit status

This is after ./configure passes and ends up with.

configuration summary:

```
Package version: duc 1.3.3
Prefix: /usr/local
Database backend: tokyocabinet
X11 support: yes
OpenGL support: no
UI (ncurses) support: yes
Graph cairo support: yes
```

Picking  one of the unresolved symbols it looks like it is available in a library that is being linked in,

root@ldas-dev:~# nm /opt/csw/lib/amd64/libglib-2.0.so.0 | grep g_unicode_script_to_iso15924
[5494] | 672912| 43|FUNC |GLOB |0 |15 |g_unicode_script_to_iso15924

I have the same problem trying to build 32-bit (i.e., without the -m64 flag and without needing to manually add -L/opt/csw/lib/amd64 -R/opt/csw/lib/amd64

Since I am primarily interested in generating database files on Solaris and viewing on Linux I am able to work around this by configuring with "--disable-x11 --disable-cairo".

**Comment by zevv** [comment]
This one is pretty old, and unfortunately I have no access to a solaris machine to reproduce. Still relevant or can I close?

**Comment by l8gravely** [comment]
Ico> This one is pretty old, and unfortunately I have no access to a
Ico> solaris machine to reproduce.  Still relevant or can I close?

I've got access to Solaris 11, I'll see if I can find some time this
week to try this out.  Been flat out at work lately, which is why I've
been so quiet.

**Comment by zevv** [comment]
* On 2016-02-24 15:55:23 +0100, John wrote:
 
> Ico> This one is pretty old, and unfortunately I have no access to a
> Ico> solaris machine to reproduce.  Still relevant or can I close?
> 
> I've got access to Solaris 11, I'll see if I can find some time this
> week to try this out.  Been flat out at work lately, which is why I've
> been so quiet.

No problem; not much happening here either :)

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by stuartthebruce** [comment]
> On Feb 24, 2016, at 7:11 AM, Ico Doornekamp <notifications@github.com> wrote:
> 
> * On 2016-02-24 15:55:23 +0100, John wrote:
> 
> > Ico> This one is pretty old, and unfortunately I have no access to a
> > Ico> solaris machine to reproduce. Still relevant or can I close?
> > 
> > I've got access to Solaris 11, I'll see if I can find some time this
> > week to try this out. Been flat out at work lately, which is why I've
> > been so quiet.

I have just reproduce this problem with the latest version of Solaris (11.3.5.6.0) and duc (1.4.0). Note, this remains a fairly minor issue as I typically index on Solaris and view on Linux.

Thanks.

--
Stuart Anderson  anderson@ligo.caltech.edu
http://www.ligo.caltech.edu/~anderson

**Comment by zevv** [comment]
Is this issue still relevant?

**Comment by stuartthebruce** [comment]
I do not have currently have (or forsee) a need to run GUI mode on Solaris, so the workaround of configuring with "--disable-x11 --disable-cairo" to index on Solaris file servers and view the results on Linux is sufficient for me.

Thanks.

**Comment by zevv** [comment]
Closing this, thanks!
