### ISSUE TITLE
Incremental Indexing

### ISSUE THREAD

**Issue by CMCDragonkai** [zevv/duc#115]
I'm exploring using something like this for monitoring servers.

Just a question, is the indexing process incremental or does it restart the indexing from scratch each time?

What would it take to make it a live process, that can continuously monitor file changes and incrementally index it? What might be overhead of this?

**Comment by zevv** [comment]
Hi Roger,

* On 2015-08-04 05:36:08 +0200, Roger Qiu wrote:

> Just a question, is the indexing process incremental or does it
> restart the indexing from scratch each time?

Incremental indexing is on the whish list. I've started some work on
this a few months ago but didn't get to finish it. Check issue #101
for more details.

There's a branch available called 'cached-indexing' which might work for
you.

> What would it take to make it a live process, that can continuously
> monitor file changes and incrementally index it? What might be
> overhead of this?

That would probably be possible, although it will probably require a lot
of platform-specific code and is currently not on the roadmap. 

The overhead depends on the size of your file system. Most modern OS's
have infrastructure available for watching file system events (inotify,
kqueue, FSevents), but these typically have overhead for each directory
being watched, consuming quite a bit of memory when you have a large
number of directories on disk. 

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by CMCDragonkai** [comment]
That's cool. I'll be watching the cached-indexing branch for now.

I read that inotify doesn't scale, and it also isn't recursive. For this problem, perhaps one could watch only directories, and if a directory changes, perform a scan on it?

**Comment by zevv** [comment]
* On 2015-08-04 10:34:10 +0200, Roger Qiu wrote:
 
> I read that inotify doesn't scale, and it also isn't recursive. For
> this problem, perhaps one could watch only directories, and if a
> directory changes, perform a scan on it?

That also does not scale too well. Maybe it would be better to leave the
watching to something portable and generic, like Gamin. Lots of added
dependencies and complexity, though.

**Comment by zevv** [comment]
Closing this ticket for now. The request has been added to `TODO.md`
