### ISSUE TITLE
autoreconf on RHEL 5.5 fails

### ISSUE THREAD

**Issue by l8gravely** [zevv/duc#116]
Working again on duc, and finding that autoreconf on RHEL 5.6 systems isn't working right, I get:

> autoreconf
> configure.ac:160: error: possibly undefined macro: AC_TYPE_UINT32_T
>       If this token and others are legitimate, please use m4_pattern_allow.
>       See the Autoconf documentation.
> configure.ac:161: error: possibly undefined macro: AC_TYPE_UINT64_T
> configure.ac:162: error: possibly undefined macro: AC_TYPE_UINT8_T
> autoreconf: /usr/bin/autoconf failed with exit status: 1

I had to make a couple of changes:
1. comment out the AC_TYPE_ stuff above from configure.ac around lines 160 to 162.
2. add in a new macro:
   AM_PROG_CC_C_O
3. manually do 'automake -a' to add in the missing files.

I'll push this all as branch 'rhel5' later on today I hope.

**Comment by l8gravely** [comment]
I've pushed up a new branch rhel5 which fixes this, now to test on other releases to make sure it doesn't break things.

**Comment by zevv** [comment]
Any updates on this?

**Comment by zevv** [comment]
This is getting old, closing!
