### ISSUE TITLE
suggestion: print full path in error messages about stat problems

### ISSUE THREAD

**Issue by l8gravely** [zevv/duc#118]
When running duc on an NFS mounted filesystem with 5.5Tb worth of space used, and 25+ million files, I got a bunch of errors like this:

Error statting semtech: No such file or directory
Error statting baysand: No such file or directory
Error statting Baysand: No such file or directory
Error statting streamtv: No such file or directory
Error statting synapse: No such file or directory

But I haven't a clue which directory path they are under.  I'll see if I can whip up a patch to include that info, since it helps with debugging and error checking.

John

**Comment by zevv** [comment]
* On 2015-08-05 20:49:49 +0200, John wrote:
 
> When running duc on an NFS mounted filesystem with 5.5Tb worth of space used, and 25+ million files, I got a bunch of errors like this:
> 
> Error statting semtech: No such file or directory
> Error statting baysand: No such file or directory
> Error statting Baysand: No such file or directory
> Error statting streamtv: No such file or directory
> Error statting synapse: No such file or directory
> 
> But I haven't a clue which directory path they are under.  I'll see if
> I can whip up a patch to include that info, since it helps with
> debugging and error checking.

Yeah, I've run into that as well. For performance reasons duc does not
keep track of the complete path name when statting files, so there is no
single string available you can simply print there. Getting the full
path would require you to unwind the call stack while storing paths,
which is a nasty solution. Maybe a simple getcwd() would suffice as
well?

 

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by l8gravely** [comment]
Maybe... I just started looking at the code again and it's not simple like I hoped.  I'll give it a whirl and see what I can do.

I've also re-started my test run with -x -p -e .snapshot since I suspect the run failed due to going into the Netapp .snapshot directory in a semi-endless loop.  More when I know more but tests take a while.... :-)

**Comment by zevv** [comment]
Implemented in 256abc6. Change was not that hard, we now simply use realpath() to convert the name of the dirent to a full path relatively to the current directory.
