### ISSUE TITLE
Looping in pread()

### ISSUE THREAD

**Issue by benpro** [zevv/duc#120]
Hi there,

It looks like ```duc index``` can be frozen in a ```pread()``` loop consuming 100% of a core.

ps:
```root      3173 99.0  0.0  90612 16504 pts/1    R+   16:12   2:50 duc index -d /backup/duc.idx /backup/last```

lsof:
```duc     3173 root   15r   DIR   8,17     4096 21103538 /backup/last/home/iscope/www/Bases/Press_GoogleNews_Indus_Dehn-De/images.nordbay
ern.de/polopoly_fs/1.4675495.1443690332!httpImage/26293969.JPG_gen/derivatives/video_teaser                                            ```

strace:
```
[…]
pread(3, "\260\241\34\353\230<N\275\352\361jw\303.\5\10\32\300q\244,\312\"\363\306+ZH\231\25\222y"..., 256, 62323200) = 256
pread(3, "\260\241\34\353\230<N\275\352\361jw\303.\5\10\32\300q\244,\312\"\363\306+ZH\231\25\222y"..., 256, 62323200) = 256
pread(3, "\260\241\34\353\230<N\275\352\361jw\303.\5\10\32\300q\244,\312\"\363\306+ZH\231\25\222y"..., 256, 62323200) = 256
pread(3, "\260\241\34\353\230<N\275\352\361jw\303.\5\10\32\300q\244,\312\"\363\306+ZH\231\25\222y"..., 256, 62323200) = 256
[…] Looping
```

Relaunched many time. Got sometimes:
```duc: tchdb.c:408: tchdbput: Assertion `hdb && kbuf && ksiz >= 0 && vbuf && vsiz >= 0```
Disappeared when deleting the index file.

Any ideas?

**Comment by zevv** [comment]
Corrupt database, I'm afraid (see #80). Tokyocabinet has failed on me
before. It is pretty fast and the database files are compact, but every
now and then these things seem to happen.

* On 2015-12-22 16:22:55 +0100, Benoît.S wrote:
 
> Hi there,
> 
> It looks like ```duc index``` can be frozen in a ```pread()``` loop consuming 100% of a core
> 
> ps:
> ```root      3173 990  00  90612 16504 pts/1    R+   16:12   2:50 duc index -d /backup/ducidx /backup/last```
> 
> lsof:
> ```duc     3173 root   15r   DIR   8,17     4096 21103538 /backup/last/home/iscope/www/Bases/Press_GoogleNews_Indus_Dehn-De/imagesnordbay
> ernde/polopoly_fs/146754951443690332!httpImage/26293969JPG_gen/derivatives/video_teaser                                            ```
> 
> strace:
> ```
> […]
> pread(3, "\260\241\34\353\230<N\275\352\361jw\303\5\10\32\300q\244,\312\"\363\306+ZH\231\25\222y", 256, 62323200) = 256
> pread(3, "\260\241\34\353\230<N\275\352\361jw\303\5\10\32\300q\244,\312\"\363\306+ZH\231\25\222y", 256, 62323200) = 256
> pread(3, "\260\241\34\353\230<N\275\352\361jw\303\5\10\32\300q\244,\312\"\363\306+ZH\231\25\222y", 256, 62323200) = 256
> pread(3, "\260\241\34\353\230<N\275\352\361jw\303\5\10\32\300q\244,\312\"\363\306+ZH\231\25\222y", 256, 62323200) = 256
> […] Looping
> ```
> 
> Relaunched many time Got sometimes:
> ```duc: tchdbc:408: tchdbput: Assertion `hdb && kbuf && ksiz >= 0 && vbuf && vsiz >= 0```
> Disappeared when deleting the index file
> 
> Any ideas?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/zevv/duc/issues/120

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by benpro** [comment]
Ok so, the loop in pread() is due to a corrupted database?
Maybe this can be avoided? Like detecting the loop and exiting with an error?

**Comment by zevv** [comment]
* On 2015-12-22 17:44:12 +0100, Benoît.S wrote:
 
> Ok so, the loop in pread() is due to a corrupted database?
> Maybe this can be avoided? Like detecting the loop and exiting with an error?

I think we can not control this; the looping takes plce inside a
tokyocabinet function call, so Duc does not know anything about any
looping. It calls a function which just happens to never return.

The only remotely sane thing I can think of is scheduling an alarm timer
before calling TC functions and aborting Duc if the call takes too long,
This sound like a horrible workaround and is not very portable, though.

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by benpro** [comment]
So is it a tokyocabinet issue? Can't we report it to upstream?

**Comment by zevv** [comment]
* On 2015-12-22 21:27:23 +0100, Benoît.S wrote:
 
> So is it a tokyocabinet issue? Can't we report it to upstream?

Unfortunately upstream development has long ceased and no bugs are
fixed. Tokyocabinet has been obsoleted in favour of kyotocabinet, but
the latter is C++ with a half-baked C binding which does not properly
fit in the model Duc uses.

-- 
:wq
^X^Cy^K^X^C^C^C^C
