### ISSUE TITLE
Feature Request: List all files in the database which are above a specific size

### ISSUE THREAD

**Issue by ech3** [zevv/duc#121]
I have a script which scans all of the files on a filesystem for files which are larger than a certain size, and notifies their owners that they have files that violate the size limit. I would like to be to replace that functionality with a duc scan instead so that I can both generate graphs and achieve this "big" file size reporting functionality in one shot with a single database.

**Comment by zevv** [comment]
* On 2016-01-07 16:47:10 +0100, ech3 wrote:
 
> I have a script which scans all of the files on a filesystem for files
> which are larger than a certain size, and notifies their owners that
> they have files that violate the size limit I would like to be to
> replace that functionality with a duc scan instead so that I can both
> generate graphs and achieve this "big" file size reporting
> functionality in one shot with a single database 

Duc is able to provide this info for you in XML format, use the 'xml'
subcommand with the -s/--min_size=VAL option. For example, to dump all
directories and files over 1Mb in size use:

   duc xml -s 1000000


 

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by ech3** [comment]
I didn't realize the XML option could do that. I just use an XSLT like below, and it looks like I am good to go. Thanks.

```
<?xml version="1.0"?>

<xsl:stylesheet version="1.0"
xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

<xsl:template match="/">
  <xsl:apply-templates select="//ent[not(@type)]" />
</xsl:template>

<xsl:template match="ent">
  <xsl:for-each select="ancestor::ent"><xsl:value-of select="@name" />/</xsl:for-each>
  <xsl:value-of select="@name" /><xsl:text>&#xa;</xsl:text>
</xsl:template>

</xsl:stylesheet>
```
