### ISSUE TITLE
CGI does not work properly with lighttpd

### ISSUE THREAD

**Issue by zevv** [zevv/duc#122]
Duc uses the environment variable QUERY_STRING to receive the CGI command line from the web server. On apache this variable is always available, and is empty if no CGI parameters are given. On Lighttpd though, the variable is simply not available if no arguments are given. In this case, Duc assumes the user is not running in a CGI environment and gives the error message.
         
As a workaround you can edit your duc.cgi script to always set the variable:
           
````
  #!/bin/sh
  export QUERY_STRING="$QUERY_STRING"
  /usr/bin/duc cgi -d /home/ico/.duc.db
````

**Comment by olivluca** [comment]
Cool, shorter that what I'm using
```
if [ -z $QUERY_STRING ] ; then
  QUERY_STRING=""
  export QUERY_STRING
fi
```

**Comment by zevv** [comment]
Interesting to see that lighthttpd's behaviour is not RFC-compliant: RFC 3875 chapter "4.1.7. QUERY_STRING" states that

````
The server MUST set this variable; if the Script-URI does not include a query component, the QUERY_STRING MUST be defined as an empty string ("").
````

I'll change Duc to check for the GATEWAY_INTERFACE variable, which seems to be available on all major CGI implementations.
