### ISSUE TITLE
Sort/display/graph by number of files, not file size/disk usage

### ISSUE THREAD

**Issue by SupremeGit** [zevv/duc#123]
Hi,
When trying to manage large quantities of data the number of files is often a critical factor.
100GB of tiny files can take longer to copy than 10TB of large files, especially on a distributed filesystem like gluster, with large latencies for each file operation.

Duc is looking fantastic, for working out where disk space has been used, but would be even more useful, if it could generate the same sort of graphs to show where the largest number of files are.

Please consider adding this feature when you can. 
It would be incredibly useful.
Thanks.

**Comment by zevv** [comment]
That sounds like a useful feature; I just added it to the duc database
backend in a few minutes, the implementation is pretty trivial. Duc
already keeps track of two different sizes for each file/dir: the
apparent and the actual size. I added a third size type here, which is
always simply 1 for each file, which then gets automatically accumulated
over subdirectories. There's a slight increas in the database size
because duc needs to keep track of an extra number for each file,
though.

I need to do some more work to add the option to all the displaying
tools and ui's though, but that won't take too long.

* On 2016-02-23 04:23:09 +0100, SupremeGit wrote:
 
> Hi,
> When trying to manage large quantities of data the number of files is often a critical factor.
> 100GB of tiny files can take longer to copy than 10TB of large files, especially on a distributed filesystem like gluster, with large latencies for each file operation.
> 
> Duc is looking fantastic, for working out where disk space has been used, but would be even more useful, if it could generate the same sort of graphs to show where the largest number of files are.
> 
> Please consider adding this feature when you can. 
> It would be incredibly useful.
> Thanks.
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/zevv/duc/issues/123
>    Hi,
>    When trying to manage large quantities of data the number of files is
>    often a critical factor.
>    100GB of tiny files can take longer to copy than 10TB of large files,
>    especially on a distributed filesystem like gluster, with large latencies
>    for each file operation.
> 
>    Duc is looking fantastic, for working out where disk space has been used,
>    but would be even more useful, if it could generate the same sort of
>    graphs to show where the largest number of files are.
> 
>    Please consider adding this feature when you can.
>    It would be incredibly useful.
>    Thanks.
> 
>    —
>    Reply to this email directly or [1]view it on GitHub.
> 
>    Reverse link: [2]unknown
> 
> References
> 
>    Visible links
>    1. https://github.com/zevv/duc/issues/123
>    2. https://github.com/zevv/duc/issues/123

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by zevv** [comment]
Feature added in the latest git versions. Please give it a try and let me know if this works for you.

**Comment by SupremeGit** [comment]
I've just given it a quick test and it is exactly what we needed.
You ppls have implemented this incredibly quickly, it's almost like you hit the repository with a bolt of magic lightning, and behold! It is done! And it works perfectly.
You updated the man page with the --count option.
AND you updated the help text for the gui command so i could see that "c" toggles between showing file size and file count.
Awesome work :-)
Thanks so much.

**Comment by zevv** [comment]
* On 2016-02-24 01:18:54 +0100, SupremeGit wrote:
 
> I've just given it a quick test and it is exactly what we needed.  You
> ppls have implemented this incredibly quickly, it's almost like you
> hit the repository with a bolt of magic lightning, and behold! It is
> done! And it works perfectly.  

You were just lucky: I have a few days off, and the the change was
pretty trivial :)

-- 
:wq
^X^Cy^K^X^C^C^C^C
