### ISSUE TITLE
bad url parameter decoding in duc cgi

### ISSUE THREAD

**Issue by patLPG** [zevv/duc#124]
I'm using duc 1.4.0 cgi with --list. In my brower, if I navigate in folders with space or other character in the name, I received an error path doesn't exist. I've changed the decode_uri method in cmd-cgi.c following this article;
[https://stackoverflow.com/questions/2673207/c-c-url-decode-library]
And now it's working (at least for me).

Thank you for the nice work with duc!
Best regards,
Patrice

`static void decode_uri(char *src, char *dst)
{
        char a, b;
        while (*src) {
                if ((*src == '%') &&
                    ((a = src[1]) && (b = src[2])) &&
                    (isxdigit(a) && isxdigit(b))) {
                        if (a >= 'a')
                                a -= 'a'-'A';
                        if (a >= 'A')
                                a -= ('A' - 10);
                        else
                                a -= '0';
                        if (b >= 'a')
                                b -= 'a'-'A';
                        if (b >= 'A')
                                b -= ('A' - 10);
                        else
                                b -= '0';
                        *dst++ = 16*a+b;
                        src+=3;
                } else if (*src == '+') {
                        *dst++ = ' ';
                        src++;
                } else {
                        *dst++ = *src++;
                }
        }
        *dst++ = '\0';
}

static int decode_uri_old(char *src, char *dst)
{
        int len = 0;
        while(*src) {
                if (*src == '%' && src[1] && src[2] && isxdigit(src[1]) && isxdigit(src[2])) {
                        src[1] -= src[1] <= '9' ? '0' : (src[1] <= 'F' ? 'A' : 'a')-10;
                        src[2] -= src[2] <= '9' ? '0' : (src[2] <= 'F' ? 'A' : 'a')-10;
                        dst[len] = 16 * src[1] + src[2];
                        src += 3;
                        continue;
                }
                dst[len] = *src++;
                len ++;
        }
        dst[len] = '\0';
        return len;
}`

**Comment by zevv** [comment]
Hi Patrice,

Thanks for pointing that out. Handling files/dirs with spaces is part of
my test suite, but for some reason it broke somewhere and slipped
through without getting noticed. 

Fixed in the latest git version, using more-or-less your code.

* On 2016-02-24 17:20:57 +0100, patLPG wrote:
 
> I'm using duc 1.4.0 cgi with --list. In my brower, if I navigate in folders with space or other character in the name, I received an error path doesn't exist. I've changed the decode_uri method in cmd-cgi.c following this article;
> [https://stackoverflow.com/questions/2673207/c-c-url-decode-library]
> And now it's working (at least for me).
> 
> Thank you for the nice work with duc!
> Best regards,
> Patrice
> 
> `static void decode_uri(char *src, char *dst)
> {
>         char a, b;
>         while (*src) {
>                 if ((*src == '%') &&
>                     ((a = src[1]) && (b = src[2])) &&
>                     (isxdigit(a) && isxdigit(b))) {
>                         if (a >= 'a')
>                                 a -= 'a'-'A';
>                         if (a >= 'A')
>                                 a -= ('A' - 10);
>                         else
>                                 a -= '0';
>                         if (b >= 'a')
>                                 b -= 'a'-'A';
>                         if (b >= 'A')
>                                 b -= ('A' - 10);
>                         else
>                                 b -= '0';
>                         *dst++ = 16*a+b;
>                         src+=3;
>                 } else if (*src == '+') {
>                         *dst++ = ' ';
>                         src++;
>                 } else {
>                         *dst++ = *src++;
>                 }
>         }
>         *dst++ = '\0';
> }
> 
> static int decode_uri_old(char *src, char *dst)
> {
>         int len = 0;
>         while(*src) {
>                 if (*src == '%' && src[1] && src[2] && isxdigit(src[1]) && isxdigit(src[2])) {
>                         src[1] -= src[1] <= '9' ? '0' : (src[1] <= 'F' ? 'A' : 'a')-10;
>                         src[2] -= src[2] <= '9' ? '0' : (src[2] <= 'F' ? 'A' : 'a')-10;
>                         dst[len] = 16 * src[1] + src[2];
>                         src += 3;
>                         continue;
>                 }
>                 dst[len] = *src++;
>                 len ++;
>         }
>         dst[len] = '\0';
>         return len;
> }`
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/zevv/duc/issues/124
>    I'm using duc 1.4.0 cgi with --list. In my brower, if I navigate in
>    folders with space or other character in the name, I received an error
>    path doesn't exist. I've changed the decode_uri method in cmd-cgi.c
>    following this article;
>    [[1]https://stackoverflow.com/questions/2673207/c-c-url-decode-library]
>    And now it's working (at least for me).
> 
>    Thank you for the nice work with duc!
>    Best regards,
>    Patrice
> 
>    `static void decode_uri(char src, char *dst)
>    {
>    char a, b;
>    while (src) {
>    if ((src == '%') &&
>    ((a = src[1]) && (b = src[2])) &&
>    (isxdigit(a) && isxdigit(b))) {
>    if (a >= 'a')
>    a -= 'a'-'A';
>    if (a >= 'A')
>    a -= ('A' - 10);
>    else
>    a -= '0';
>    if (b >= 'a')
>    b -= 'a'-'A';
>    if (b >= 'A')
>    b -= ('A' - 10);
>    else
>    b -= '0';
>    *dst++ = 16a+b;
>    src+=3;
>    } else if (*src == '+') {
>    *dst++ = ' ';
>    src++;
>    } else {
>    *dst++ = *src++;
>    }
>    }
>    *dst++ = '\0';
>    }
> 
>    static int decode_uri_old(char src, char *dst)
>    {
>    int len = 0;
>    while(src) {
>    if (*src == '%' && src[1] && src[2] && isxdigit(src[1]) &&
>    isxdigit(src[2])) {
>    src[1] -= src[1] <= '9' ? '0' : (src[1] <= 'F' ? 'A' : 'a')-10;
>    src[2] -= src[2] <= '9' ? '0' : (src[2] <= 'F' ? 'A' : 'a')-10;
>    dst[len] = 16 * src[1] + src[2];
>    src += 3;
>    continue;
>    }
>    dst[len] = *src++;
>    len ++;
>    }
>    dst[len] = '\0';
>    return len;
>    }`
> 
>    —
>    Reply to this email directly or [2]view it on GitHub.
> 
>    Reverse link: [3]unknown
> 
> References
> 
>    Visible links
>    1. https://stackoverflow.com/questions/2673207/c-c-url-decode-library
>    2. https://github.com/zevv/duc/issues/124
>    3. https://github.com/zevv/duc/issues/124

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by zevv** [comment]
I managed to mess this up in the 1.4 release, is fixed in 7da6e5d83b1563b4627d365228a2b95f15907edd, will make a new release shortly
