### ISSUE TITLE
Toggle between count and size display in cgi mode

### ISSUE THREAD

**Issue by stuartthebruce** [zevv/duc#129]
I think it would be great if there was a toggle displayed in cgi mode that would allow users to switch between showing size and count.

**Comment by zevv** [comment]
I think this applies to more options, not only --count. It would be nice to be able to switch apparent size, palette, fuzz, and all these things which are also available on the command line.

I'd like to keep the CGI a bit simple though, not sure if I will implement all these for now.

**Comment by stuartthebruce** [comment]
For now I have modified by CGI wrapper to use different symbolic links in the URL to indicate what view the user wants to see, e.g., actual disk usage versus apparent size versus file count.

**Comment by stuartthebruce** [comment]
I have run into a problem with this solution (multiple links to the same CGI script and using $0 to decide what view mode to operate in). However, I think the problem is more general. In particular, after clicking on a disk usage map cgi returns an x,y coordinate for the resulting image, e.g.,

https://duc.com/diskusage.cgi?x=341&y=328.0500030517578&path=/home1/ahnitz

if my script attempts to switch to a file count view by modifying /*.cgi/ section of the URL, e.g.,

https://duc.com/filecount.cgi?x=341&y=328.0500030517578&path=/home1/ahnitz

the same x,y coordinates do not necessarily correspond to the same directory in the database for the two different views since the relative fraction of a space a directory uses is different if measured in bytes versus file count. Note, the same problem can happen when changes from actual to apparent disk usage as well.

Would it be possible to have cgi mode return an updated path string rather than modifying the base directory with x&y coordinates? That would be invariant when changing view modes.

Thanks.

**Comment by zevv** [comment]
Good point. Changed `duc cgi` to return a 302 redirect with the new path instead of drawing from the requested (x,y) coordinates. Please try c57e9066617656fe44b130d0624781787a05d409 and let me know if this works for you.

**Comment by stuartthebruce** [comment]
Perfect. Works exactly as expected.

Are you willing to spin a 1.4.4 release for this?

Thanks.

> On Jan 8, 2017, at 7:37 AM, Ico Doornekamp <notifications@github.com> wrote:
> 
> Good point. Changed duc cgi to return a 302 redirect with the new path instead of drawing from the requested (x,y) coordinates. Please try c57e906 and let me know if this works for you.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--
Stuart Anderson  anderson@ligo.caltech.edu
http://www.ligo.caltech.edu/~anderson
