### ISSUE TITLE
OSX and leveldb

### ISSUE THREAD

**Issue by stuartthebruce** [zevv/duc#131]
On OS X 10.11.3 with leveldb installed via macports ./configure passes,

./configure --disable-x11 --with-db-backend=leveldb

...
 
 configuration summary:

   - Package version: duc 1.4.0
   - Prefix: /usr/local
   - Database backend: leveldb
   - X11 support: no
   - OpenGL support: no
   - UI (ncurses) support: yes
   - Graph cairo support: yes

However, the final link fails with,

Undefined symbols for architecture x86_64:
  "_leveldb_get", referenced from:
      _db_putcat in db-leveldb.o
      _db_get in db-leveldb.o
  "_leveldb_open", referenced from:
      _db_open in db-leveldb.o
  "_leveldb_options_create", referenced from:
      _db_open in db-leveldb.o

until a manual -lleveldb is added at which point and index command runs for about as long as expected, however, the info command fails,

duc info --debug
Reading from database "/Users/stuart.anderson/.duc.db"
Error opening: /Users/stuart.anderson/.duc.db - Unknown error, contact the author
Unknown error, contact the author

This is building from,

git show
commit 02a35ccfbad672786a11fbe9b31421721b4a6adf
Author: Ico Doornekamp <ico@pruts.nl>
Date:   Sun Mar 6 21:46:26 2016 +0100

**Comment by stuartthebruce** [comment]
My mistake. "Unknown error, contact the author" comes from having the wrong permission on the .duc.db directory and files (it appears that at least .duc.db/ and .duc.db/LOCK need to be owned by the user running duc in the case of leveldb).

A more specific file permission error might be worth throwing in this case if it is not too hard to catch.

**Comment by zevv** [comment]
* On 2016-03-07 03:31:19 +0100, stuartthebruce wrote:
 
> My mistake. "Unknown error, contact the author" comes from having the
> wrong permission on the .duc.db directory and files (it appears that
> at least .duc.db/ and .duc.db/LOCK need to be owned by the user
> running duc in the case of leveldb).
> 
> A more specific file permission error might be worth throwing in this
> case if it is not too hard to catch.

Leveldb does not return specific error codes which can be interpreted by
the calling program. Instead, it returns a pointer to a string
containing a readable error message. I usually try to keep the duc
backend code silent on stdout/stderr and propagate errors to the various
duc command tools, but in this case there is no other way then to simply
print this message to stderr if it occurs.

Fixed in 9d1de3e 

 

-- 
:wq
^X^Cy^K^X^C^C^C^C
