### ISSUE TITLE
3 digits displayed for seconds

### ISSUE THREAD

**Issue by stuartthebruce** [zevv/duc#133]
On SL6 running a recent version from master I am now seeing 3 digits in the seconds field of the timestamp in cgi mode, e.g., note the ":031" below. Note, this was only 2 digits in version 1.4.0.

> git branch
* master

> git log | head -1
commit 02a35ccfbad672786a11fbe9b31421721b4a6adf

> env SCRIPT_NAME= GATEWAY_INTERFACE= duc cgi --count -d /var/www/html/diskusage/ducdb/filesystem/home1.duc | tail
  <tr>
   <td><a href="?cmd=index&path=/home1">/home1</a></td>
   <td>75.9T</td>
   <td>206732343</td>
   <td>7754523</td>
   <td>2016-03-09</td>
   <td>00:30:031</td>
  </tr>
 </table>
</div>

**Comment by zevv** [comment]
This was fixed in 02a35ccfbad672786a11fbe9b31421721b4a6adf on march 6 (debug printf I forgot to remove)
