### ISSUE TITLE
index time not being reported

### ISSUE THREAD

**Issue by stuartthebruce** [zevv/duc#135]
The index command in version 1.4.1 is reporting only "0" or "-0" for  timing information on both a Solaris 11 and SL 6 build, e.g.,

# duc index -v -x -p /var
Writing to database "/root/.duc.db"
Skipping share: not crossing file system boundaries
Indexed 15584 files and 5713 directories, (324.8MB apparent, 183.3MB actual) in 0d, 0 hours, 0 minutes, and -0.00 seconds.

**Comment by l8gravely** [comment]
I think I've fixed this now.  Needed to A) fix the calc from seconds to human readable times, a B) fix the output for quick indexing runs.  Could I ask you to re-run your test using:

time duc index -v -x -p /var

as a test?

**Comment by stuartthebruce** [comment]
> On Oct 15, 2016, at 3:47 PM, John <notifications@github.com> wrote:
> 
> I think I've fixed this now. Needed to A) fix the calc from seconds to human readable times, a B) fix the output for quick indexing runs. Could I ask you to re-run your test using:
> 
> time duc index -v -x -p /var
> 
> as a test?

With which version of duc?

Thanks.

--
Stuart Anderson  anderson@ligo.caltech.edu
http://www.ligo.caltech.edu/~anderson

**Comment by l8gravely** [comment]
>>>>> "stuartthebruce" == stuartthebruce  <notifications@github.com> writes:

>> On Oct 15, 2016, at 3:47 PM, John <notifications@github.com> wrote:
>> 
>> I think I've fixed this now. Needed to A) fix the calc from seconds to human
stuartthebruce> readable times, a B) fix the output for quick indexing runs. Could I ask you to
stuartthebruce> re-run your test using:
>> 
>> time duc index -v -x -p /var
>> 
>> as a test?

stuartthebruce> With which version of duc?

The latest version of the master branch.

  git clone https://github/zevv/duc

Should give you the latest version.  Double check in src/libduc/duc.c
for three calls to 'floor(', which is what was needed to fix the
conversion.

John

**Comment by stuartthebruce** [comment]
> On Oct 15, 2016, at 6:11 PM, John <notifications@github.com> wrote:
> 
> >>>>> "stuartthebruce" == stuartthebruce <notifications@github.com> writes:
> 
> >> On Oct 15, 2016, at 3:47 PM, John <notifications@github.com> wrote:
> >> 
> >> I think I've fixed this now. Needed to A) fix the calc from seconds to human
> stuartthebruce> readable times, a B) fix the output for quick indexing runs. Could I ask you to
> stuartthebruce> re-run your test using:
> >> 
> >> time duc index -v -x -p /var
> >> 
> >> as a test?

That worked (at least to within a fraction of a second, which is good enough for me), e.g.,

# time ./duc index -v -x -p /var
…
Indexed 25979 files and 7503 directories, (9.6GB apparent, 10.2GB actual) in 0.10 secs.

real	0m0.147s
user	0m0.079s
sys	0m0.060s

and with a slightly longer index,

Indexed 2523589 files and 72423 directories, (566.5GB apparent, 621.7GB actual) in 4 minutes, and 48.3

real	4m48.752s
user	0m10.067s
sys	0m31.865s

--
Stuart Anderson  anderson@ligo.caltech.edu
http://www.ligo.caltech.edu/~anderson

**Comment by l8gravely** [comment]
Thanks for the confirmation!  I'm marking this closed now.
