### ISSUE TITLE
src/libduc/index.c:285:17: error: 'PATH_MAX' undeclared (first use in this function)

### ISSUE THREAD

**Issue by hpfn** [zevv/duc#136]
Hi,

duc-1.4.1 does not build on hurd-i386. (Debian)

Failing reason for duc on hurd-i386: [0]
> ../../src/libduc/index.c:285:17: error: 'PATH_MAX' undeclared (first use in this function)

[0] - https://buildd.debian.org/status/package.php?p=duc

I am not a programmer. But I did a 'diff' between version 1.4.0 and 1.4.1
and PATH_MAX only exists in 1.4.1. Two times, inside two different functions.
And there is no '#define'.

Could you take a look at it ?

regards,
Herbert

**Comment by l8gravely** [comment]
>>>>> "hpfn" == hpfn  <notifications@github.com> writes:

hpfn> duc-1.4.1 does not build on hurd-i386. (Debian)

hpfn> Failing reason for duc on hurd-i386: [0]

hpfn>     ../../src/libduc/index.c:285:17: error: 'PATH_MAX' undeclared (first use in this function)
   
hpfn> [0] - https://buildd.debian.org/status/package.php?p=duc

hpfn> I am not a programmer. But I did a 'diff' between version 1.4.0 and 1.4.1
hpfn> and PATH_MAX only exists in 1.4.1. Two times, inside two different functions.
hpfn> And there is no '#define'.

I see the problem.  GNU Hurd doesn't define PATH_MAX because they say
the POSIX standard doesn't require it at all, and that we should
instead be doing dynamic allocation.

Since it's a rainy day here, I might find the time to do some hacking
and see if I can whip up a patch for this.

John

**Comment by l8gravely** [comment]
hpfn> duc-1.4.1 does not build on hurd-i386. (Debian)

hpfn> Failing reason for duc on hurd-i386: [0]

hpfn>     ../../src/libduc/index.c:285:17: error: 'PATH_MAX' undeclared (first use in this function)
   
hpfn> [0] - https://buildd.debian.org/status/package.php?p=duc

hpfn> I am not a programmer. But I did a 'diff' between version 1.4.0
hpfn> and 1.4.1 and PATH_MAX only exists in 1.4.1. Two times, inside
hpfn> two different functions.  And there is no '#define'.

Herbert,

It might be just enough to change that to be DUC_PATH_MAX instead....
can you try that simple change and let us know?

John

**Comment by hpfn** [comment]
On Sat, 02 Apr 2016 07:37:31 -0700
John <notifications@github.com> wrote:

> 
> hpfn> duc-1.4.1 does not build on hurd-i386. (Debian)
> 
> hpfn> Failing reason for duc on hurd-i386: [0]
> 
> hpfn>     ../../src/libduc/index.c:285:17: error: 'PATH_MAX' undeclared (first use in this function)
>    
> hpfn> [0] - https://buildd.debian.org/status/package.php?p=duc
> 
> hpfn> I am not a programmer. But I did a 'diff' between version 1.4.0
> hpfn> and 1.4.1 and PATH_MAX only exists in 1.4.1. Two times, inside
> hpfn> two different functions.  And there is no '#define'.
> 
> Herbert,
> 
> It might be just enough to change that to be DUC_PATH_MAX instead....
> can you try that simple change and let us know?
> 

Ok. I will do that.



regards,
-- 
Herbert Parentes Fortes Neto (hpfn)

**Comment by zevv** [comment]
Atually, the exact size is not at all important, since the buffer is
only used to report error messages. We can use any arbitrary size which
is likely large enough for practical cases, 4k or so would be just fine.

DUC_PATH_MAX would be fine as well, will fix this asap.

 
> >>>>> "hpfn" == hpfn  <notifications@github.com> writes:
> 
> hpfn> duc-1.4.1 does not build on hurd-i386. (Debian)
> 
> hpfn> Failing reason for duc on hurd-i386: [0]
> 
> hpfn>     ../../src/libduc/index.c:285:17: error: 'PATH_MAX' undeclared (first use in this function)
>    
> hpfn> [0] - https://buildd.debian.org/status/package.php?p=duc
> 
> hpfn> I am not a programmer. But I did a 'diff' between version 1.4.0 and 1.4.1
> hpfn> and PATH_MAX only exists in 1.4.1. Two times, inside two different functions.
> hpfn> And there is no '#define'.
> 
> I see the problem.  GNU Hurd doesn't define PATH_MAX because they say
> the POSIX standard doesn't require it at all, and that we should
> instead be doing dynamic allocation.
> 
> Since it's a rainy day here, I might find the time to do some hacking
> and see if I can whip up a patch for this.
> 
> John
> 
> 
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/zevv/duc/issues/136#issuecomment-204726915
>    >>>>> "hpfn" == hpfn <notifications@github.com> writes:
> 
>    hpfn> duc-1.4.1 does not build on hurd-i386. (Debian)
> 
>    hpfn> Failing reason for duc on hurd-i386: [0]
> 
>    hpfn> ../../src/libduc/index.c:285:17: error: 'PATH_MAX' undeclared (first
>    use in this function)
> 
>    hpfn> [0] - https://buildd.debian.org/status/package.php?p=duc
> 
>    hpfn> I am not a programmer. But I did a 'diff' between version 1.4.0 and
>    1.4.1
>    hpfn> and PATH_MAX only exists in 1.4.1. Two times, inside two different
>    functions.
>    hpfn> And there is no '#define'.
> 
>    I see the problem. GNU Hurd doesn't define PATH_MAX because they say
>    the POSIX standard doesn't require it at all, and that we should
>    instead be doing dynamic allocation.
> 
>    Since it's a rainy day here, I might find the time to do some hacking
>    and see if I can whip up a patch for this.
> 
>    John
> 
>    —
>    You are receiving this because you are subscribed to this thread.
>    Reply to this email directly or [1]view it on GitHub
> 
>    Reverse link: [2]unknown
> 
> References
> 
>    Visible links
>    1. https://github.com/zevv/duc/issues/136#issuecomment-204726915
>    2. https://github.com/zevv/duc/issues/136#issuecomment-204726915

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by hpfn** [comment]
On Sun, 03 Apr 2016 10:13:19 -0700
Ico Doornekamp <notifications@github.com> wrote:

> Atually, the exact size is not at all important, since the buffer is
> only used to report error messages. We can use any arbitrary size which
> is likely large enough for practical cases, 4k or so would be just fine.
> 
> DUC_PATH_MAX would be fine as well, will fix this asap.
> 

It builds on a local chroot enviroment.

In a Debian machine it is pending confirmation an upload.
https://buildd.debian.org/status/fetch.php?pkg=duc&arch=hurd-i386&ver=1.4.1-2&stamp=1459689707


regards,
-- 
Herbert Parentes Fortes Neto (hpfn)

**Comment by zevv** [comment]
Hi Herbert,

* On 2016-04-03 20:15:01 +0200, hpfn wrote:
 
> > Atually, the exact size is not at all important, since the buffer is
> > only used to report error messages. We can use any arbitrary size which
> > is likely large enough for practical cases, 4k or so would be just fine.
> > 
> > DUC_PATH_MAX would be fine as well, will fix this asap.
> > 
> 
> It builds on a local chroot enviroment.
> 
> In a Debian machine it is pending confirmation an upload.
> https://buildd.debian.org/status/fetch.php?pkg=duc&arch=hurd-i386&ver=1.4.1-2&stamp=1459689707
 
I've applied this change in the latest Git master, if it is not blocking
for you it'll go out with the next release. If you prefer I can also
spin a 1.4.2 for this, just let me know.

Ico

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by hpfn** [comment]
Hi,

> > 
> > It builds on a local chroot enviroment.
> > 
> > In a Debian machine it is pending confirmation an upload.
> > https://buildd.debian.org/status/fetch.php?pkg=duc&arch=hurd-i386&ver=1.4.1-2&stamp=1459689707
>  
> I've applied this change in the latest Git master, if it is not blocking
> for you it'll go out with the next release. If you prefer I can also
> spin a 1.4.2 for this, just let me know.
> 

Ok. The patch will not be needed in the future. But
do not worry about a 1.4.2.

The package is setted 'Installed' on unstable now.
https://buildd.debian.org/status/package.php?p=duc


regards,
-- 
Herbert Parentes Fortes Neto (hpfn)

**Comment by zevv** [comment]
ok, thanks
