### ISSUE TITLE
Request to separately display file and directory count in UI mode

### ISSUE THREAD

**Issue by stuartthebruce** [zevv/duc#138]
I would find it helpful if UI mode presented separate counts for files and directories rather than combining them as version 1.4.1 does, e.g., "Total 2.0TB in 2.9M files/directories (actual size)"

It would also be helpful if there was a command to filter the display between file-only, directory-only, or the current combined view.

And for viewing large directories it would also be helpful to have commands to jump-to-end and jump-to-top of list and/or change the sorting from size to alphabetical.

**Comment by zevv** [comment]
Latest master: Home and End keys added, file and directory count in duc-ui are now separate. I guess I'm not making a new release for this, so this will ship out with the next release when it happens.

File/directory filtering and sorting are harder to implement, I might fix those later.
