### ISSUE TITLE
Locate functionality

### ISSUE THREAD

**Issue by WillemJan** [zevv/duc#148]
root@light1:/ # duc ls / -R | grep libharfbuzz0b
440.0K  │   │   │   ├─ libharfbuzz0b
  12.0K  │   │   │   │   ├─ libharfbuzz0b:armhf.symbols
    4.0K  │   │   │   │   ├─ libharfbuzz0b:armhf.md5sums
    4.0K  │   │   │   │   ├─ libharfbuzz0b:armhf.list
    4.0K  │   │   │   │   ├─ libharfbuzz0b:armhf.shlibs

Does not cut it, for I am unable to see the abs-path.
Therefore I would like to have a feature something like '''locate''':

duc locate libharfbuzz0b

/var/lib/*blublah/libharfbuzz0b 440.0K
/us/share/lib/ libharfbuzz0b:armhf.symbols 12.0K

All the best,

Willem Jan

**Comment by l8gravely** [comment]
Maybe the answer is to add a new -p option to show the full path in the ls command instead?

**Comment by zevv** [comment]
* On 2016-10-15 19:00:40 +0200, John wrote:
 
> Maybe the answer is to add a new -p option to show the full path in the ls command instead?
> 
>    Maybe the answer is to add a new -p option to show the full path in the ls
>    command instead?

Or (although it breaks backwards compatibility) change the
-R/--recursive flag to show full paths, and add a new option for
explicitly requesting a tree view (-T/--tree)?
 

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by zevv** [comment]
* On 2016-10-15 19:00:40 +0200, John wrote:
 
> Maybe the answer is to add a new -p option to show the full path in the ls command instead?
> 
>    Maybe the answer is to add a new -p option to show the full path in the ls
>    command instead?

Thinking again it seems that leaving the tree as the default recursive
view makes more sense; indeed let's add a specific option for requesting
a full path listing.

Implementation almost done, checking in in a few minutes.

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by zevv** [comment]
@WillemJan: please try the latest version. Add `--full-path` when running `duc ls`

**Comment by zevv** [comment]
OP is happy, closing

**Comment by l8gravely** [comment]
>>>>> "Ico" == Ico Doornekamp <notifications@github.com> writes:

Ico> * On 2016-10-15 19:00:40 +0200, John wrote:
>> Maybe the answer is to add a new -p option to show the full path in the ls
Ico> command instead?
>> 
>> Maybe the answer is to add a new -p option to show the full path in the ls
>> command instead?

Ico> Or (although it breaks backwards compatibility) change the
Ico> -R/--recursive flag to show full paths, and add a new option for
Ico> explicitly requesting a tree view (-T/--tree)?

Maybe that's for the best, changing to match what the gnu ls command
does, for least surprise maybe?

You've been inspired today!  Lots of changes.  I've been pushing new
branches of stuff, hopefully you like my changes to testing.  I've
added in support for testing the CGI stuff without a web server.

Silly, but fun learning.

**Comment by zevv** [comment]
* On 2016-10-16 00:22:03 +0200, John wrote:
 
> >>>>> "Ico" == Ico Doornekamp <notifications@github.com> writes:
> 
> Ico> * On 2016-10-15 19:00:40 +0200, John wrote:
> >> Maybe the answer is to add a new -p option to show the full path in the ls
> Ico> command instead?
> >> 
> >> Maybe the answer is to add a new -p option to show the full path in the ls
> >> command instead?
> 
> Ico> Or (although it breaks backwards compatibility) change the
> Ico> -R/--recursive flag to show full paths, and add a new option for
> Ico> explicitly requesting a tree view (-T/--tree)?
> 
> Maybe that's for the best, changing to match what the gnu ls command
> does, for least surprise maybe?

You make a point, but on the other hand Duc is not quite ls. It's
purpose is to be able to find big things on your disk, and the problem
with the full-path list is that it kind of makes no sense at all: there
is no apperent order in the output.
 

-- 
:wq
^X^Cy^K^X^C^C^C^C
