### ISSUE TITLE
Additional requirement for CentOS

### ISSUE THREAD

**Issue by vanderlee** [zevv/duc#151]
To run `./configure` on my CentOS 6.x box, I needed to `yum install ncurses-devel` in addition to the packages listed on https://duc.zevv.nl/. Perhaps this should be added to the install instructions on the site?

p.s. The SSL certificate for https://duc.zevv.nl/ is invalid; it's a wildcard SSL for `*.pruts.nl`.

**Comment by l8gravely** [comment]
Martijn> To run ./configure on my CentOS 6.x box, I needed to yum
Martijn> install ncurses-devel in addition to the packages listed on
Martijn> https://duc.zevv.nl/. Perhaps this should be added to the
Martijn> install instructions on the site?

Thanks for the report, I've updated the INSTALL file in a branch
called 'docs'.  We'll merge it in soon.

Martijn> p.s. The SSL certificate for https://duc.zevv.nl/ is invalid; it's a wildcard
Martijn> SSL for *.pruts.nl.

Sorry, I can't help there.
