### ISSUE TITLE
Feature request: Show increase since last index or time period

### ISSUE THREAD

**Issue by herrenP** [zevv/duc#153]
Hi,

The main reason I started using this tool is actually trying to find users that increase their home directory rapidly. It was easy in the beginning but starting to get much harder now that we have more users and I keep forgetting the initial size. :) I think it would be nice, and certainly possible?, for DUC to show the increase in % since last index or a configured time period (say 7 days ago).

**Comment by drasill** [comment]
I have the same need.

I currently index the disk with a new DB file each time (something like `duc index -d /path/to/duc.db.$(date +%Y-%m-%d)`) so I can compare the sizes, but I'd love to sort it by size increase.

**Comment by l8gravely** [comment]
drasill> I have the same need.

drasill> I currently index the disk with a new DB file each time (something like duc
drasill> index -d /path/to/duc.db.$(date +%Y-%m-%d)) so I can compare the sizes, but I'd
drasill> love to sort it by size increase.

The answer *might* be to have a utility to diff two duc dbs and show
the differences...  but I honestly don't have a good idea on how this
should be done, and I've got some other projects on my plate which
have fallen behind lately.

John

**Comment by herrenP** [comment]
Oh. I thought this information was already in the DB. I do like drasills solution although I index each hour. Guess I could remove them every now and then.

Drasill: How do you show the diff? Do you just output it to a file? In my case I would like to see it in the CGI web page. Gotta think about this a bit.

**Comment by zevv** [comment]
I agree this would be a nice feature, although I'm afraid it is not easy to add. Currently Duc is kind of stupid with the database: indexing is basically a write-only operation which simple overwrites all previous records during a scan. To add a size diff to the database would require a fundamental rewrite of the way data is stored and handled.

I'm closing this ticked but adding the request to a new list of nice-to-haves I'm adding so the issue list will stay a bit clean.

**Comment by timsnyder** [comment]
@zevv is your list of nice-to-haves that you mentioned available for others to view and comment on or pick up for submitting a PR?

**Comment by zevv** [comment]
Quoting Tim Snyder (2016-12-22 16:28:48)

> [1]@zevv is your list of nice-to-haves that you mentioned available for
> others to view and comment on or pick up for submitting a PR?

Up till now the list was mainly in the back of my head and in old and
closed issue tickets. I've put up a quick list in a wiki page here:

https://github.com/zevv/duc/wiki

Feel free to add ideas or comment on what's there.


--
:wq
^X^Cy^K^X^C^C^C^C
