### ISSUE TITLE
GPG signatures for source validation

### ISSUE THREAD

**Issue by NicoHood** [zevv/duc#155]
As we all know, today more than ever before, it is crucial to be able to trust our computing environments. One of the main difficulties that package maintainers of Linux distributions face, is the difficulty to verify the authenticity and the integrity of the source code.

The Arch Linux team would appreciate it if you would provide us GPG signatures in order to verify easily and quickly of your source code releases.

**Overview of the required tasks:**
* [ ] Please [create and/or use a 4096-bit RSA keypair](https://wiki.archlinux.org/index.php/GnuPG#Create_key_pair) for the file signing
* The key may be used for [email encryption](https://www.enigmail.net/index.php/en/) too
* Keep your key secret, use a strong unique passphrase for the key
* [ ] Upload the public key to a key server
* [ ] [Sign every new commit by default](https://help.github.com/articles/signing-commits-using-gpg/)
* [ ] [Sign new tags](https://help.github.com/articles/signing-tags-using-gpg/)
* Verify the Github Release tarball download against your local source
* [ ] [Sign Github Release tarballs](https://wiki.debian.org/Creating%20signed%20GitHub%20releases)

**Additional Information:**
* https://help.github.com/categories/gpg/
* https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work
* https://www.qubes-os.org/doc/verifying-signatures/
* https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https

Thanks.

**Comment by zevv** [comment]
No problem, I guess now is a good a time as any to upgrade my 10 years old DSA/1024 key.

How do I handle merges from non-signed commits?

**Comment by NicoHood** [comment]
I think the best idea for handling those merges is to reject them unless the submitter signs them via gpg. It would not be much of a problem and if I am not wrong you can also sign older commits. On the other hand you could also sign them.

The most important part of the signing is the source release (used for packaging the software) and the tagged releases. If large parts of your git history are signed, that'd be still okay. We always try to get the best security available, but not everyone understands why this is important. Feel free to insist on people signing their PRs or just merge them if you don't feel so.

Thanks for taking the time :)

**Comment by NicoHood** [comment]
You still did not upload any signature to the releases. May you please do so?

**Comment by zevv** [comment]
Quoting Nico (2016-12-23 12:00:00)
>    You still did not upload any signature to the releases. May you please do
>    so?

Just signed the latest 1.4.2 release.

--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by NicoHood** [comment]
Thanks a lot <3

You still need to add the public gpg key to your github account so it can show "verified" on github. It would also be a good idea to sign the tag itself too. For ArchLinux packaging this is enough though :)

**Comment by zevv** [comment]
Quoting Nico (2016-12-25 15:59:19)

> You still need to add the public gpg key to your github account so it can
> show "verified" on github. It would also be a good idea to sign the tag
> itself too. For ArchLinux packaging this is enough though :)

Slowly getting there. Just added my GPG to github, but I can't find any
signs of the release being 'verified' at this time. Where should this
show up?

--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by NicoHood** [comment]
"verified" on the left side. Example:
https://github.com/NicoHood/guestwlan/releases

You need to tag the release via command line: `git tag -s 1.0.0`

**Comment by zevv** [comment]
Quoting Nico (2016-12-25 18:13:05)
>    "verified" on the left side. Example:
>    [1]https://github.com/NicoHood/guestwlan/releases
> 
>    You need to tag the release via command line: git tag -s 1.0.0

Is there a trick to sign a tag retrospectively, or should I simply
delete the tag and create it new?

--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by NicoHood** [comment]
I have no idea. I'd have to google too. I suggest to sign new commits and new tags next time and dont worry too much about the existing one. The source download is the important one for us packages and that is fine.

**Comment by zevv** [comment]
Quoting Nico (2016-12-29 16:11:46)
>    I have no idea. I'd have to google too. I suggest to sign new commits and
>    new tags next time and dont worry too much about the existing one. The
>    source download is the important one for us packages and that is fine.

Ok, I'll leave it as it is now since everything is pushed to github
already and I don't want to mess up anyone's clones. I'll keep in mind
to sign for the next release.

Thanks,

--
:wq
^X^Cy^K^X^C^C^C^C
