### ISSUE TITLE
Kyoto cabinet support

### ISSUE THREAD

**Issue by groutr** [zevv/duc#158]
Are there plans to add support for kyoto cabinet database?  It seems it is recommended for use over tokyocabinet.
http://fallabs.com/tokyocabinet/

**Comment by zevv** [comment]
Quoting Ryan Grout (2016-12-15 20:44:44)

>    Are there plans to add support for kyoto cabinet database?

Not at this time, but on request I can take a stab at this. If I recall
correctly I gave this a try some time a go, but there was a problem with
the C api of kyoto cabinet which forces the database file name to have a
certain extension. A small nuisance, but for some reason this kept me
from integrating kyotocabinet support altogether.

--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by groutr** [comment]
The reason for my question is that kyoto cabinet has builtin support for Python 2/3.  Python libraries for tokyocabinet are either unmaintained or don't support Python 3 very well.

**Comment by groutr** [comment]
I see that there seems to be support for other database formats.  How does one use leveldb or sqlite in duc?

**Comment by l8gravely** [comment]
>>>>> "Ryan" == Ryan Grout <notifications@github.com> writes:

Ryan> I see that there seems to be support for other database
Ryan> formats. How does one use leveldb or sqlite in duc?

sqlite is really just for testing, I wouldn't bother.  Not as sure
about leveldb since I haven't used it at all.  I

**Comment by zevv** [comment]
Sqlite actually has his benefits: as of this time, it is the most portable database format which can be used to access Duc indexes on machines with different architectures and word size.

**Comment by zevv** [comment]
@groutr: Switching database backends requires you to rebuild Duc from source, check the INSTALL file for details.

Not sure if still relevant, but I have added kyotocabinet support in a5cad54dede91b24476e91740f22b433af51ef1e.

**Comment by groutr** [comment]
Wow!  Thanks @zevv!
