### ISSUE TITLE
How to handle all the db backends

### ISSUE THREAD

**Issue by zevv** [zevv/duc#164]
At this time Duc supports five different database backends, all come with some good and some bad. Is it a good idea to keep supporting all of those, or should we pick one (the best?) and drop the rest?

I did some simple tests to check performance and database size of the various dbs on my little laptop, these are the results. I also added a column indicating if the database files are portable over different architectures, and if the db format is 'crash safe', whatever that means

````
database       time   size  portable   crash_safe
-------------------------------------------------
tokyocabinet   6.42   39M     no         ?
sqlite3        6.30   99M     yes        yes
lmdb           3.48  118M     no         yes
kyoto          4.28   40M     no         no
````

I left out leveldb because this backend seems to be kind of broken at the moment - which is one of the downsides of supporting so many.

So:

- kyoto is great for performance and compression, but not stable and not portable
- sqlite is the only portable database - drop this and people can not export db's from solaris to linux
- lmdb is blazingly fast, but the db size is the largest of all

Not an easy choice...

**Comment by zevv** [comment]
Quoting John (2016-12-29 22:23:52)
>
>   Ico> I did some simple tests to check performance and database size of
>   Ico> the various dbs on my little laptop, these are the results. I
>   Ico> also added a column indicating if the database files are portable
>   Ico> over different architectures, and if the db format is 'crash
>   Ico> safe', whatever that means
>
>   What number of files and size of the filesystem please?

2016-12-29 21:22:38    2.4M  210.6K  319.7G /

>   Ico> I left out leveldb because this backend seems to be kind of
>   Ico> broken at the moment - which is one of the downsides of
>   Ico> supporting so many.
>
>   What was the idea behind leveldb?

I have no clue, it probable seemed like a good idea at the moment to put
it in.

>   I don't think we need to worry about portable at all. It's really not
>   worth fighting over. Yes, it would be nice to be able to generate
>   data on Solaris (in my case) and display on Linux, but I can't see the
>   writing on the wall that I should just drop supporting Solaris.

Personally I don't care for portability, but it tends to come up every
now and then. Maybe adding 'export/import' functions would be enough
to make these people happy.

>   I'm also thinking that maybe we should pull the library code into duc,
>   if it's small enough. This is where I think lmdb wins.

It would indeed be nice if basic Duc could build with no dependencies
except libc.

>   But if the size grows by 3x... it might be a problem. I've currently
>   got 5.2Gb of duc DBs (tokyocabinet based) which would grow to 15Gb in
>   size. This impacts how much data needs to be read to compute data.

I might be able to shave off something like 20% by doing Snappy
compression at the record level. Snappy sources are also small and could
be embedded in Duc, if the licenses agree.


--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by jbd** [comment]
Here is my new user opinion, for what it worth =)

tokyo and kyoto cabinet seems unsupported.

I feel that lmdb is the right choice for the long term. [The benchmarks page](https://symas.com/products/lightning-memory-mapped-database/project-benchmarks/) are quite complete. A lot of projects have switch to it (CFengine particulary made the [switch](https://groups.google.com/forum/#!topic/help-cfengine/oS0oIQYyCYw) from tokyocabinet to lmdb for example). lmdb has been initially build to replace the default bdb backend within openldap, it give some kind of guarantee of sustainability. It should not be an argument, but the author of LMDB is known for the quality of its code. I also like the fact that lmdb can embedded quite easily.

The [crash consistency](http://www.openldap.org/lists/openldap-devel/201410/msg00008.html) is also central in the design of lmdb. It may be not critical on the duc use case (just run it again) though, but from my point of view, I would not make such tradeoff (even to have a smaller database in the end).

Jean-Baptiste

**Comment by zevv** [comment]
Quick test with snappy on lmdb: index time stays the same, db size shrinks to 75% (118M to 92M).

One note on lmdb though: I'm not into the details of how lmdb handles overwrites, but in my tests I see the db size double if I re-index the same filesystem. 

See https://symas.com/understanding-lmdb-database-file-sizes-and-memory-utilization/ for more info

**Comment by l8gravely** [comment]
>>>>> "Ico" == Ico Doornekamp <notifications@github.com> writes:

Ico> Quick test with snappy on lmdb: index time stays the same, db
Ico> size shrinks to 75% (118M to 92M).

That's a nice improvement!

Ico> One note on lmdb though: I'm not into the details of how lmdb
Ico> handles overwrites, but in my tests I see the db size double if I
Ico> re-index the same filesystem.

Ouch... but I thought we said that the best thing to do was to index
to a temp file, and then move it onto the old DB location?  Or can
lmdb handle people reading while it's being updated?  

Ico> See https://symas.com/
Ico> understanding-lmdb-database-file-sizes-and-memory-utilization/ for more info

Will try to look this over.

**Comment by jbd** [comment]
> l8gravely> Or can lmdb handle people reading while it's being updated?

Yes it can. Each reader have a consistent view within a read transaction. That why those transactions must be keeping short (see the "Can you back up an LMDB instance while it is actively updating, or do
you need to stop it?" question [here](https://symas.com/getting-down-and-dirty-with-lmdb-qa-with-symas-corporations-howard-chu-about-symass-lightning-memory-mapped-database/))

> zevv> One note on lmdb though: I'm not into the details of how lmdb handles overwrites, but in my tests I see the db size double if I re-index the same filesystem.

Ouch indeed. Like suggested, this could be workarounded by using a new database each time, but this means no mtime optimisation for updating : you'll have to crawl everything again right ? I don't know enough LMDB to help you here or even if its design allow a reasonable solution (does not seem like it from the symas blog post and a few google searches)

**Comment by stuartthebruce** [comment]
> On Dec 29, 2016, at 2:23 PM, John <notifications@github.com> wrote:
> 
> >>>>> "Ico" == Ico Doornekamp <notifications@github.com> writes:
> 
> Ico> At this time Duc supports five different database backends, all
> Ico> come with some good and some bad. Is it a good idea to keep
> Ico> supporting all of those, or should we pick one (the best?) and
> Ico> drop the rest?
> 
> Yes!! 
> 
> Ico> I did some simple tests to check performance and database size of
> Ico> the various dbs on my little laptop, these are the results. I
> Ico> also added a column indicating if the database files are portable
> Ico> over different architectures, and if the db format is 'crash
> Ico> safe', whatever that means
> 
> What number of files and size of the filesystem please? 
> 
> Ico> database time size portable crash_safe
> Ico> -------------------------------------------------
> Ico> tokyocabinet 6.42 39M no ?
> Ico> sqlite3 6.30 99M yes yes
> Ico> lmdb 3.48 118M no yes
> Ico> kyoto 4.28 40M no no
> 
> Ico> I left out leveldb because this backend seems to be kind of
> Ico> broken at the moment - which is one of the downsides of
> Ico> supporting so many.
> 
> What was the idea behind leveldb? 
> 
> Ico> So: kyoto still seems a good choice considering size and
> Ico> speed. lmdb wins on speed but uses almost 3 times the size on the
> Ico> index and is not portable. sqlite3 is portable but not
> Ico> particularly fast nor small.
> 
> Ico> Not an easy choice...
> 
> I don't think we need to worry about portable at all. It's really not
> worth fighting over. Yes, it would be nice to be able to generate
> data on Solaris (in my case) and display on Linux, but I can't see the
> writing on the wall that I should just drop supporting Solaris.

FWIW, generating tokyocabinet on Solaris x86 and displaying on Linux
is working for me. I haven’t tried switching over to kyoto yet, but
that looks like the best choice from the performance table above.

For reference, I am daily indexing 1.8B files, 82M directories, and
8.9PB of data in 12 filesystems.

Thanks.

--
Stuart Anderson  anderson@ligo.caltech.edu
http://www.ligo.caltech.edu/~anderson

**Comment by zevv** [comment]
Quoting John (2016-12-29 23:07:21)
>   Ouch... but I thought we said that the best thing to do was to index
>   to a temp file, and then move it onto the old DB location? Or can
>   lmdb handle people reading while it's being updated?

I fixed this a few days ago.

--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by jbd** [comment]
> stuartthebruce> For reference, I am daily indexing 1.8B files, 82M directories, and 8.9PB of data in 12 filesystems.

That's impressive. Would you mind sharing databases sizes and running time ? I've shared some of mine in https://github.com/zevv/duc/issues/163#issuecomment-269619856 (using lmdb backend).

**Comment by stuartthebruce** [comment]
> On Dec 30, 2016, at 2:21 AM, jbd <notifications@github.com> wrote:
> 
> stuartthebruce> For reference, I am daily indexing 1.8B files, 82M directories, and 8.9PB of data in 12 filesystems.
> 
> That's impressive. Would you mind sharing databases sizes and running time ? I’ve shared some of mine in #163 (comment) (using lmdb backend).

These are for the tokyocabinet backend runs last night,

Filesystem	/bin/du	/bin/ls	Files		Directories	Download 	Scan (hh:mm:ss)
/archive/frames	140.5T 	6.0P	181477468 	123809 		901M		04:55:23
/backup 	23.1T 	653.9T	326890819 	24025034 	2.7G		*
/hdfs/frames 	1.5P 	1.5P	4551506 	6163 		38M		01:55:17
/home1 		65.6T 	63.0T	119812782 	7591941 	1001M		01:42:18
/home2 		90.7T 	86.9T	201678337 	9259550 	1.8G		04:23:39
/home3 		67.8T 	64.9T	152859988 	8115027 	1.3G		01:55:17
/home4 		77.0T 	72.3T	249054498 	7065112 	1.9G		04:11:47
/home5 		85.7T 	84.3T	68996497 	2658221 	633M		01:03:44
/home6 		53.4T 	52.1T	77313530 	2661679 	605M		00:51:13
/oldacct1 	202.2G 	132.3T	229580799 	10711719 	1.9G		*
/oldacct2 	425.8G 	85.9T	298771400 	13464692 	2.0G		*
/zfs1 		7.9T 	9.1T	146784		2121		1.8M		00:00:54
/zfs2 		21.9T 	29.9T	1692693 	15759		15M		00:01:38
/zfs3 		26.7T 	27.0T	412615		25001		4.1M		00:01:02
Total		2.2P	8.9P	1.8G		81.8M		14.3G 

* filesystems scanned in parallel with /archive/frames so that reported time is the longest of those 4 filesystems.

P.S. For all but the first 3 filesystems the above wall clock Scan times also include running 1468 parallel instances of duc to provide smaller database files (1468) for subsets of the filesystems (individual user directory trees).

Thanks.

--
Stuart Anderson  anderson@ligo.caltech.edu
http://www.ligo.caltech.edu/~anderson

**Comment by l8gravely** [comment]
>>>>> "jbd" == jbd  <notifications@github.com> writes:

stuartthebruce> For reference, I am daily indexing 1.8B files, 82M
jbd>     directories, and 8.9PB of data in 12 filesystems.

jbd> That's impressive. Would you mind sharing databases sizes and
jbd> running time ?  I've shared some of mine in #163 (comment) (using
jbd> lmdb backend).

Wow, beats my approx 300tb of indexing hands down.  And doing it daily
is even more impressive!  I usually just do my filesystems weekly...

**Comment by jbd** [comment]
> zevv> One note on lmdb though: I'm not into the details of how lmdb handles overwrites, but in my tests I see the db size double if I re-index the same filesystem.

I didn't read [the article about the lmdb database size](https://symas.com/understanding-lmdb-database-file-sizes-and-memory-utilization/), but after a few iterations of indexing the same path, the database does not grow anymore:

```
$ rm -f /tmp/d.db; while true; do ./duc index -d /tmp/d.db -x /usr/share && stat -c %s /tmp/d.db; sleep 1; done
9986048
19968000
29949952
29974528
29995008
29995008
29995008
29995008
29995008
^C
```

I do not understand yet the size stabilization behaviour.

**Comment by l8gravely** [comment]
>>>>> "jbd" == jbd  <notifications@github.com> writes:

zevv> One note on lmdb though: I'm not into the details of how lmdb handles
jbd>     overwrites, but in my tests I see the db size double if I re-index the same
jbd>     filesystem.

jbd> I didn't read the article about the lmdb database size, but after a few
jbd> iterations of indexing the same path, the database does not grow anymore:

jbd> $ rm -f /tmp/d.db; while true; do ./duc index -d /tmp/d.db -x /usr/share && stat -c %s /tmp/d.db; sleep 1; done
jbd> 9986048
jbd> 19968000
jbd> 29949952
jbd> 29974528
jbd> 29995008
jbd> 29995008
jbd> 29995008
jbd> 29995008
jbd> 29995008
jbd> ^C

jbd> I do not understand yet the size stabilization behaviour.

That kinda suck, tripling in size!  Can you give more details on your
configuration and compile mode?  And which revision you're compiling?

**Comment by jbd** [comment]
I've edited the conclusion in my post before your answer. After quickly read some part of the article, this make sense. Not ideal from a user perspective I agree, but justified from a technical point of view (search about "compaction" in the article).

**Comment by zevv** [comment]
Makes sense indeed. Still not sure if lmdb would be ok as the only and default db backend. In my test setup the db size increases from 39M to 352M, that's probably bad news for a lot of users.

Different people have different needs; probably best to keep supporting multiple backends then.

**Comment by zevv** [comment]
Closing this for now. All db's have pros and cons it seems.
