### ISSUE TITLE
A "file count" mode

### ISSUE THREAD

**Issue by noamraph** [zevv/duc#168]
Hi,

It would be nice to have a "file count" mode, that would show the number of files instead of the disk space used. A large number of files is a burden on tools like rsync (and also duc). It is useful to be able to see where are all the files in a directory tree, with no regard for their sizes.

ncdu has this feature.

Thanks,
Noam

**Comment by zevv** [comment]
Hi Noam,

Quoting noamraph (2017-01-08 12:21:27)

> It would be nice to have a "file count" mode, that would show the
> number of files instead of the disk space used. A large number of
> files is a burden on tools like rsync (and also duc). It is useful to
> be able to see where are all the files in a directory tree, with no
> regard for their sizes.
> 
> ncdu has this feature.

Duc also does: in 'duc ls' used the '--count' option to see counts
instead of sizes. In 'duc ui' or 'duc gui' use the 'c' key to toggle
between size and count mode.

Check the man page for details.

--
:wq
^X^Cy^K^X^C^C^C^C
