### ISSUE TITLE
duc-nox manpage

### ISSUE THREAD

**Issue by hpfn** [zevv/duc#170]
Hi,

I maintain the duc Debian package. As requested, it is 
provided two packages: duc and duc-nox.

Every new version of duc I have to refresh the duc-nox 
manpage because only duc manpage is provided in the
tarball. This is maintainence hard work.

Can you please provide the duc-nox manpage ?

Regards,
Herbert

**Comment by zevv** [comment]
Hi herbert,

Quoting Herbert Fortes (2017-01-13 14:32:12)

> Every new version of duc I have to refresh the duc-nox manpage because
> only duc manpage is provided in the tarball. This is maintainence hard
> work.

The man page is generated at build time by combining doc/manual.txt and
doc/options.txt, the latter of which is generated by running 'duc
manual'. The output of 'duc manual' depends on the enabled options
chosen at configure time.

Would it be feasible for you to re-generate the man page at package
build time? This would also make sure the options from the man page
always reflect the available options from the duc binary as built by
you.

 $ rm -f doc/duc.1
 $ make -C doc

Let me know if this works for you


--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by hpfn** [comment]
Hi Ico Doornekamp,

I am really sorry for the long delay.

> Hi herbert,
> 
> Quoting Herbert Fortes (2017-01-13 14:32:12)
> 
>> Every new version of duc I have to refresh the duc-nox manpage because
>> only duc manpage is provided in the tarball. This is maintainence hard
>> work.
> 
> The man page is generated at build time by combining doc/manual.txt and
> doc/options.txt, the latter of which is generated by running 'duc
> manual'. The output of 'duc manual' depends on the enabled options
> chosen at configure time.

I did not know about that. :(
 
> 
> Would it be feasible for you to re-generate the man page at package
> build time? This would also make sure the options from the man page
> always reflect the available options from the duc binary as built by
> you.
> 
> $ rm -f doc/duc.1
> $ make -C doc
> 
> Let me know if this works for you
> 

I build the package twice, to generate duc and duc-nox executables.
With different options chosen at configure time. I will see that and
come back with an answer later.

Thanks!



Regards,
Herbert

**Comment by hpfn** [comment]
Hi,

I tried:
$ rm -f doc/duc.1 
$ make -C doc

with '--disable-cairo --disable-x11' to build a different
manpage. But I got this error:

$ LANG=C make -C doc
make: Entering directory '/home/qemu/duc/duc-1.4.3/doc'
make: *** No rule to make target '../duc', needed by 'duc.1'.  Stop.
make: Leaving directory '/home/qemu/duc/duc-1.4.3/doc'



Regards,
Herbert

**Comment by zevv** [comment]
Quoting Herbert Fortes (2017-01-27 13:48:49)
> Hi,
> 
> I tried:
> $ rm -f doc/duc.1 
> $ make -C doc
> 
> with '--disable-cairo --disable-x11' to build a different
> manpage. But I got this error:

The documentation is generated by the duc binary, so you should first
build Duc with the appropriate options, then (re)generate the
documentation

  $ rm -f doc/duc.1
  $ make
  $ make -C doc

Hope this helps

--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by hpfn** [comment]
On 27-01-2017 11:08, Ico Doornekamp wrote:
> Quoting Herbert Fortes (2017-01-27 13:48:49)
>> Hi,
>>
>> I tried:
>> $ rm -f doc/duc.1
>> $ make -C doc
>>
>> with '--disable-cairo --disable-x11' to build a different
>> manpage. But I got this error:
> 
> The documentation is generated by the duc binary, so you should first
> build Duc with the appropriate options, then (re)generate the
> documentation
> 
> $ rm -f doc/duc.1
> $ make
> $ make -C doc
> 

Ok. I was able to generate a duc-nox.1 manpage. It is
different from the original duc.1. But it still has
problems, tought.

For example, in original duc.1 I have three references
to 'pallete':

# grep palette ../duc.1
\fB\-\-palette=VAL\fR
select palette\. available palettes are: size, rainbow, greyscale, monochrome, classic
\fB\-\-palette=VAL\fR
select palette\. available palettes are: size, rainbow, greyscale, monochrome, classic
p           toggle palettes
\fB\-\-palette=VAL\fR
select palette\. available palettes are: size, rainbow, greyscale, monochrome, classic
palette rainbow

And in generated duc-nox.1 I have two references to
'pallete':

# grep palette doc/duc.1\fB\-\-palette=VAL\fR
select palette\. available palettes are: size, rainbow, greyscale, monochrome, classic
\fB\-\-palette=VAL\fR
select palette\. available palettes are: size, rainbow, greyscale, monochrome, classic
palette rainbow

And I still have references to 'gui' in duc-nox.1 too. 5 lines 
instead of 8.

Can it be improve ?



Regards,
Herbert

**Comment by zevv** [comment]
Quoting Herbert Fortes (2017-01-29 15:01:08)
 
> And in generated duc-nox.1 I have two references to
> 'pallete':
> 
> # grep palette doc/duc.1\fB\-\-palette=VAL\fR
> select palette\. available palettes are: size, rainbow, greyscale, monochrome, classic
> \fB\-\-palette=VAL\fR
> select palette\. available palettes are: size, rainbow, greyscale, monochrome, classic
> palette rainbow

That is perfectly fine: these are part of the 'cgi' and 'graph'
commands, which are still available if you configure without cairo or
X11.

> And I still have references to 'gui' in duc-nox.1 too. 5 lines 
> instead of 8.
> 
> Can it be improve ?

The man page is generated from two parts: one part of free text from
doc/manual.txt, and the list of available commands and options which is
generated by the Duc binary.

The free text contains some references to commands that might or might
not be available depending on the configuration. I think that adding
some notes to the manual.txt describing that some subcommands may or may
not be available depending on the configuration should be sufficient.
Otherwise, the manual.txt will have to be completely generated depending
on the configuration, which is kind of a hassle.

I have added some notes to the text and an addition question to the FAQ
section, available in e0933ee61f996c21bab3825648792858cd26fb5c

Thanks,

Ico

--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by hpfn** [comment]
>> And in generated duc-nox.1 I have two references to
>> 'pallete':
>>
>> # grep palette doc/duc.1\fB\-\-palette=VAL\fR
>> select palette\. available palettes are: size, rainbow, greyscale, monochrome, classic
>> \fB\-\-palette=VAL\fR
>> select palette\. available palettes are: size, rainbow, greyscale, monochrome, classic
>> palette rainbow
> 
> That is perfectly fine: these are part of the 'cgi' and 'graph'
> commands, which are still available if you configure without cairo or
> X11.
> 
>> And I still have references to 'gui' in duc-nox.1 too. 5 lines
>> instead of 8.
>>
>> Can it be improve ?
> 
> The man page is generated from two parts: one part of free text from
> doc/manual.txt, and the list of available commands and options which is
> generated by the Duc binary.
> 
> The free text contains some references to commands that might or might
> not be available depending on the configuration. I think that adding
> some notes to the manual.txt describing that some subcommands may or may
> not be available depending on the configuration should be sufficient.
> Otherwise, the manual.txt will have to be completely generated depending
> on the configuration, which is kind of a hassle.
> 
> I have added some notes to the text and an addition question to the FAQ
> section, available in e0933ee61f996c21bab3825648792858cd26fb5c
> 

Ok. That is the end of the issue.

Thanks for the replies.



Regards,
Herbert
