### ISSUE TITLE
Cgi failed on big database

### ISSUE THREAD

**Issue by Radek-Svoboda** [zevv/duc#177]
Cgi failed on large index  (680MBytes, 44M files,1M folders)

/usr/local/bin/duc cgi -a  --tooltip --palette=rainbow  --ring-gap=10  --list -d  /tmp/vfxstore-root-VFXstore.duc

[Tue Feb 21 13:46:47 2017] [error] [client 192.168.31.250] (8)Exec format error: exec of '/var/www/cgi-bin/vfxstore-root-VFXstore.cgi' failed
[Tue Feb 21 13:46:47 2017] [error] [client 192.168.31.250] Premature end of script headers: vfxstore-root-VFXstore.cgi

smaller indexes works ok.

ThankYou for hint

Radek

**Comment by zevv** [comment]
Quoting Radek-Svoboda (2017-02-21 14:22:45)
> Cgi failed on large index  (680MBytes, 44M files,1M folders)

That's not a large index :)

Do you get the error when loading the first page, or when selecting a
specific path?

> /usr/local/bin/duc cgi -a  --tooltip --palette=rainbow  --ring-gap=10  --list -d  /tmp/vfxstore-root-VFXstore.duc
> 
> [Tue Feb 21 13:46:47 2017] [error] [client 192.168.31.250] (8)Exec format error: exec of '/var/www/cgi-bin/vfxstore-root-VFXstore.cgi' failed
> [Tue Feb 21 13:46:47 2017] [error] [client 192.168.31.250] Premature end of script headers: vfxstore-root-VFXstore.cgi

Ok, it seems that duc writes something to stdout violating the CGI
protocol. Could you please try the following: please try to start duc
from the command line, but by providing some environment variables make
it think that it is actually running as a CGI under the web server. Your
command line should look something like this:

   GATEWAY_INTERFACE=1 QUERY_STRING="" SCRIPT_NAME=duc ./duc cgi

and check the output. The very first line should say 

   Content-Type: text/html

followed by an empty line. If there is anything else output there, your
webserver will usualle generate a 501.


--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by Radek-Svoboda** [comment]
The error ocures when loading the first page.

output from Your suggested params - as You write
[root@store05 bin]# GATEWAY_INTERFACE=1 QUERY_STRING="" SCRIPT_NAME=duc ./duc cgi -a  --tooltip --palette=rainbow  --ring-gap=10  --list -d  /tmp/vfxstore-root-VFXstore.duc 

` Content-Type:text/html`
`      `
`<!DOCTYPE html>`
`<head>`
`......`
differences betwen working and failed outputs - nothing special

`[root@store05 bin]# diff /tmp/distore.out /tmp/vfxstore.out`
`32,37c32,37`
`<    <td><a href="duc?cmd=index&path=/net/distore/root/DIstore">/net/distore/root/DIstore</a></td>`
`<    <td>459.9T</td>`
`<    <td>9047840</td>`
`<    <td>199744</td>`
`<    <td>2017-02-16</td>`
`<    <td>09:59:57</td>`
`---`
`>    <td><a href="duc?cmd=index&path=/net/vfxstore/root/VFXstore">/net/vfxstore/root/VFXstore</a></td>`
`>    <td>671.9T</td>`
`>    <td>44330549</td>`
`>    <td>1043671</td>`
`>    <td>2017-02-17</td>`
`>    <td>19:27:42</td>`

**Comment by Radek-Svoboda** [comment]
Sorry for mistake. There was a bug in the CGI script (I missed #!/bin/bash on the first line of the CGI script)
Thanks
Radek

**Comment by zevv** [comment]
Quoting Radek-Svoboda (2017-02-22 23:20:24)

> Sorry for mistake. There was a bug in the CGI script (I missed
> #!/bin/bash on the first line of the CGI script)

No problem. But still, out of curiosity: how does that explain the
behaviour where it sometimes works, but sometimes not?

--
:wq
^X^Cy^K^X^C^C^C^C
