### ISSUE TITLE
Application hangs when updating the database

### ISSUE THREAD

**Issue by j0hannes** [zevv/duc#178]
It had been running for 240 hours (cpu time). According to `lsof` it had been working on the same directory at least for a day or two. That directory contains only 40k files.

Killing the process, deleting the database and running the application again results in a clean new (smaller) database.

Maybe related to #176?

**Comment by zevv** [comment]
Quoting j0hannes (2017-03-22 13:47:53)
> It had been running for 240 hours (cpu time). According to `lsof` it had been working on the same directory at least for a day or two. That directory contains only 40k files.
> 
> Killing the process, deleting the database and running the application again results in a clean new (smaller) database.
> 
> Maybe related to #176?

And #80, most likely. It seems that it is time to leave tokyocabinet
behind and choose a different default database type, as there are too
many reports of stability issues lately.

Thanks for reporting.

--
:wq
^X^Cy^K^X^C^C^C^C
