### ISSUE TITLE
1.4.3 ./configure badly broken

### ISSUE THREAD

**Issue by Whichcraft** [zevv/duc#187]
Hi zevv

The build process is really broken with the 1.4.3 release. no configure script no makefile ...

cheers

**Comment by zevv** [comment]
Where exactly did you download the release?

Quoting Whichcraft (2017-10-25 17:08:15)
> Hi zevv
> 
> The build process is really broken with the 1.4.3 release. no configure script no makefile ...
> 
> cheers
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/zevv/duc/issues/187


--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by BEFH** [comment]
It's missing from the github release page.

**Comment by zevv** [comment]
It's the top link at this page: https://github.com/zevv/duc/releases

Direct link to the release is https://github.com/zevv/duc/releases/download/1.4.3/duc-1.4.3.tar.gz

This includes the `configure` script.

**Comment by guysoft** [comment]
Is there a way to build from master?
How do you generate the files?

**Comment by guysoft** [comment]
Ok, got it via the ``.spec`` file for rpm,

You can do:
```
autoreconf --install
./configure
make install / checkinstall``

Should I PR?

**Comment by l8gravely** [comment]
Guy> Is there a way to build from master?
Guy> How do you generate the files?

This is certainly a good thing to put into the documentation as a
quick note at the bottom.

John

**Comment by zevv** [comment]
Seems that this can be closed.
