### ISSUE TITLE
ZFS anyone?

### ISSUE THREAD

**Issue by j4jes** [zevv/duc#188]
has anyone tried duc on a ZFS volume? I have two partitions mounted, one ext4 on / , and one ZFS on /share.  When I try a duc index command on the /share partition it doesn't throw any errors and says it wrote to the DB, but whenever I try graphing or using "duc ui" with that /share path it says it doesn't exist in the database. 

root@cortex:~/bin # /usr/local/bin/duc index /share/projects --verbose
Writing to database "/root/.duc.db"
Indexed 263368 files and 9229 directories, (6.1TB apparent, 1.3TB actual) in 0.923057 secs.
root@cortex:~/bin # 
root@cortex:~/bin # /usr/local/bin/duc graph /share/projects -o /var/www/html/diskreport/projects.png --verbose
Reading from database "/root/.duc.db"
Requested path not found
root@cortex:~/bin #

**Comment by stuartthebruce** [comment]
duc on ZFS is working for me. I suggest you double check the path reported by duc info, e.g.,

[root@gridmon filesystem]# duc info -d zfs2.duc
Date       Time       Files    Dirs    Size Path
2017-11-16 19:00:12    1.7M   15.8K   21.9T /zfs2

**Comment by j4jes** [comment]
Just tried that and it reports the correct path. I guess it's not indexing properly or something:

`root@cortex:~ # duc info -d .duc.db
Date       Time       Files    Dirs    Size Path
2017-11-17 14:21:21    4.0M   65.0K   10.2T /exports/meaney.lab
2017-11-17 14:24:56  263.4K    9.2K    1.3T /share/projects
root@cortex:~ # duc graph /share/projects
Requested path not found
root@cortex:~ # 
root@cortex:~ # df -h
Filesystem                      Size  Used Avail Use% Mounted on
/dev/sda3                        15T   13T  1.2T  92% /
devtmpfs                        126G     0  126G   0% /dev
tmpfs                           126G  4.0K  126G   1% /dev/shm
tmpfs                           126G  1.2G  125G   1% /run
tmpfs                           126G     0  126G   0% /sys/fs/cgroup
/dev/sda2                       477M  344M  104M  77% /boot
zaphod                           18T   13T  5.5T  69% /share
tmpfs                            26G     0   26G   0% /run/user/0
tmpfs                            26G     0   26G   0% /run/user/1063
tmpfs                            26G     0   26G   0% /run/user/20007
tmpfs                            26G     0   26G   0% /run/user/20023
tmpfs                            26G     0   26G   0% /run/user/1040
tmpfs                            26G     0   26G   0% /run/user/1065
172.16.131.50:/volume1/archive   11T  6.8T  4.1T  63% /ratking/archive
tmpfs                            26G     0   26G   0% /run/user/1052
tmpfs                            26G     0   26G   0% /run/user/1048
root@cortex:~ # `

**Comment by j4jes** [comment]
I updated to the latest version of duc, and not only did it fix the problem but I find indexing 2x faster!

Thanks.
