### ISSUE TITLE
Feature suggestion: duc ui xdg-open

### ISSUE THREAD

**Issue by nonsns** [zevv/duc#192]
Dear all, 

I use duc quite regularly and I like pretty much the UI interface 

I wanted to contribute with a (likely) one-liner idea:  when in the function  :

        duc_dir *do_dir(duc_dir *dir, int depth)

you are at a leaf node (i.e., a file),  when the user presses ENTER or LEFT (i.e., tries to "enter" the file)  what about launching the default viewer for that file ?

occasionally, it happens that in the UI you find a large file you would like to "see" (e.g., before deleting), but then you are forced to re-find  the file and open it by other means (shell or mc or ...).

I guess that this could be done somehow around the following lines of duc/cmd-ui.c

240:			case KEY_LEFT:
242:					  return NULL;   // xdg_open(dir)  //dir should in this case be a file, right? 

and similarly for the  ENTER case:
254:			case '\n': 
...
                  
(sorry it's ages since I last programmed in C and I am still a n00b in github  -- had this been some scripting language, I could have tried  to contribute with the one-liner myself)

best, 
D.

**Comment by zevv** [comment]
Sounds like a good idea, although I'm not sure if I would like to bind this to the default right/enter key. This might cause xdg-open to start all kind of things (open browsers, video players) while I'm navigating my way around.

I've added a new key for this instead: `o` 

Code is available in commit 7387b987ed879ebdb215293f35ac775d247dc759

**Comment by nonsns** [comment]
Wow.... amazingly fast! will try it asap ;)

thanks!
D.
