### ISSUE TITLE
[Feature Request] Can I delete files within `duc ui`?

### ISSUE THREAD

**Issue by NightMachinary** [zevv/duc#194]
It would be very convenient to just press, say, 'd' and get the offending files/directories deleted, and the database updated.

**Comment by zevv** [comment]
Quoting NightMachinary (2018-05-24 17:03:13)
> It would be very convenient to just press, say, 'd' and get the offending files/directories deleted, and the database updated.

It would, but the implementation would be kind of hairy, since building
the index is a recursive operation and modifications would require
recalculation of all te parent directories. I'm afraid this is not a
feature that is eaisily added...

--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by NightMachinary** [comment]
@zevv Would it be easier if `d` marked the files for removal, and then after exiting duc, it would remove those files and update the index? `Daisydisk`, a commercial GUI app, kind of does this.

**Comment by zevv** [comment]
I'm sorry, but I decided not to put this in for various reasons. One is stated above (hairy implementation), and the other is that Duc should be a non-intrusive tool that you can trust never to touch your data. We index and display file systems, but never modify.

Closing this issue, sorry I couldn't help you out!

**Comment by Gurkenglas** [comment]
Perhaps a compromise can be found here: You could have a button that, when pressed, copies the currently selected file's path into your clipboard. Then deleting something would be merely a matter of `<copy><Ctrl-Z>rm -rf<Ctrl-V> && fg<Enter>`, which one could bind to a macro if one were so insane.

**Comment by l8gravely** [comment]
>>>>> "Gurkenglas" == Gurkenglas  ***@***.***> writes:

Gurkenglas> Perhaps a compromise can be found here: You could have a
Gurkenglas> button that, when pressed, copies the currently selected
Gurkenglas> file's path into your clipboard. Then deleting something
Gurkenglas> would be merely a matter of <copy><Ctrl-Z>rm -rf<Ctrl-V>
Gurkenglas> && fg<Enter>, which one could bind to a macro if one were
Gurkenglas> so insane.

Patches gratefully discussed if proposed.  But again, duc is not meant
to be an interactive tool in terms of file deletions, but an
exploration tool to examine *large* volumes/filesystems.

Again, if you step up with a patch (and test cases!!!) we will look
them over and decide if we want to integrate it or not.

John
