### ISSUE TITLE
Cannot run multiple "duc gui" simultaneously (Separate read and write locks?)

### ISSUE THREAD

**Issue by anntzer** [zevv/duc#197]
Sometimes, it could be nice to have multiple "duc gui" running at the same time, e.g. comparing the memory usage of two directories.  However, this is (AFAICT) currently not possible, as "duc gui" locks the database, and the second invocation fails with "Resource temporary unavailable".

I guess(?) the lock is present to avoid an indexing to run simultaneously while the GUI is running; but multiple GUIs can definitely run safely concurrently.  In other words, perhaps the GUI should only acquire a read-lock, whereas the indexing would acquire a write-lock?

**Comment by zevv** [comment]
The use case you describe is supposed to work, duc has some basic logic to open the database R/O or R/W depending on the work to be done. I just verified this with the default build configuration using tokyocabinet on Ubuntu 16.04. What configuration are you using, did you build Duc yourself using non-standard options? What is the output of `duc --version`?

Thanks,

**Comment by anntzer** [comment]
I got duc from from Arch Linux's Arch User Repository, which effectively means that I built it "myself" using the build script at https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=duc + https://aur.archlinux.org/cgit/aur.git/tree/?h=duc.
```
$ duc --version
duc version: 1.4.3
options: cairo x11 ui leveldb
```

**Comment by zevv** [comment]
Ah, yes, LevelDB is the culprit here, as it does not support multiple processes using the same database at the same time. As far as I know there is now way around this, except to make a full copy of the database, use that for the reader and delete it afterwards - which is kind of crude.

For now my advice would be to build with a different database backend. We use tokyocabinet by default because it is pretty fast and provides good compression, although it is not very robust and easily creates corrupt databases if you terminate the indexing process.

**Comment by zevv** [comment]
Quoting Antony Lee (2018-08-15 12:20:56)

> Ah, I see.  I note that configure.ac supports the following dbs:
> tokyocabinet,leveldb,sqlite3,lmdb,kyotocabinet
> 
> Any thoughts on the advantage of each? (as in, is there anything that
> is both robust and supports concurrent reads)

Yes, but then it's not fast and doesnt't compress well. You can't have
your lunch, and eat it too, I'm afraid.

A safe bet is to use sqlite3, it is not the fastest nor the smallest,
but as long as you are not indexing petabytes that might not be a
problem for you.
 
--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by anntzer** [comment]
Thanks!
Looks like switching from one backend to another (i.e., leveldb to sqlite3) can cause a slightly cryptic error message:
```
$ duc index
Error opening: /home/antony/.duc.db - Database not found
Database not found
```
Of course, nuking out the old ~/.duc.db solved the issue, but you may perhaps want to clarify the error.

Feel free to close the issue, thanks for the help.

**Comment by zevv** [comment]
Created new issue #198 for the error message, closing this one.

Thanks
