### ISSUE TITLE
Return selected path in QUERY_STRING

### ISSUE THREAD

**Issue by stuartthebruce** [zevv/duc#199]
When running in cgi mode with tooltip enabled, clicking on a location in the map sets QUERY_STRING to include the x,y coordinates and the path of the map originally being display, e.g., "x=476&y=308.4499969482422&path=/home2". It would be helpful for my cgi wrapper script if QUERY_STRING also included the path of the click-to-select location. While that path is displayed in the resulting <canvas> object, I would like it to also be easily parsed in my script.

The use case is that after a user clicks on a map I add a header to the resulting displayed page that lets them toggle between actual disk usage, apparent disk usage (-a) and file count (--count). However, the x,y coordinates represent different path locations depending on the view.

Hopefully this request makes enough sense to understand.

**Comment by zevv** [comment]
Hi, I'm not sure if I understand how this should work. At this time, clicking at the Duc graph is a two step process:

The first HTTP request [1] is done by javascript and passes the `x`, `y` and `path` arguments to look up the clicked coordinates in the current graph. This request is handled by the CGI which calculates the new path that should be displayed, and redirects the browser to the new graph using only the `path` argument using a HTTP 302. This results in the second HTTP request [2], which then returns the javascript code to generate the graph of the new location.

The javascript part of Duc does not know about the new location until the server responds to the first request.

Can you explain your original question again in terms of the above 2-step process?

**Comment by stuartthebruce** [comment]
This was fixed in 1.4.4, i.e., the path in the QUERY_STRING shown in my browser address bar is now updated when clicking on a map rather than adding x,y pixel locations.  This makes it much more robust to switch between disk usage, apparent disk usage, and file count. Thanks.
