### ISSUE TITLE
[GUI] font size

### ISSUE THREAD

**Issue by yukulele** [zevv/duc#201]
font size is very small and is very hard to read on HiDPI.

Duc GUI should have an option to change font size

**Comment by l8gravely** [comment]
Clément> font size is very small and is very hard to read on HiDPI.
Clément> Duc GUI should have an option to change font size

I don't know the GUI code well at all, but maybe you go into:

  src/duc/cmd-guigl.c

and change the line where the var font_scale is defined to be 2.0
instead as a quick and dirty test?

    double font_scale = 1.0;
    sc2fb(window, &font_scale, NULL);
    graph = duc_graph_new_opengl(duc, font_scale);

If that works, then we can whip up a more complete solution.

Also, some details on your setup would be nice.  Windows?  Linux?  OS
Version?

Thanks,
John

**Comment by yukulele** [comment]
I'm on ubuntu 18.04 with pixel density 144px/in
