### ISSUE TITLE
duc ls -g misaligned in the presence of multibyte characters

### ISSUE THREAD

**Issue by mgedmin** [zevv/duc#206]
On my system when I do `duc index ~` and then `duc ls -Fgc`, this is what I see:

```
 50.9G src/                                                        [++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++]
 15.8G Atsiuntimai/                                                [++++++++++++++++++++                                              ]
  4.1G .ccache/                                                    [+++++                                                             ]
  3.4G Paveikslėliai/                                             [++++                                                              ]
  2.2G tmp/                                                        [++                                                                ]
...
```

You can see how the multibyte UTF-8 character in `Paveikslėliai` caused the graph to be misindented.

**Comment by mgedmin** [comment]
To fix this you'd have to use `mbstowcs()` to convert the `char*` filename to a `wchat_t*`, and then use `wcswidth()` to get the width in screen characters.  I believe this would handles most cases (multibyte characters, combining characters, double-width CJK characters), although emoji might be tricky.

**Comment by zevv** [comment]
Quoting Marius Gedminas (2018-11-09 17:59:07)

> To fix this you'd have to use `mbstowcs()` to convert the `char*`
> filename to a `wchat_t*`, and then use `wcswidth()` to get the width
> in screen characters.  I believe this would handles most cases
> (multibyte characters, combining characters, double-width CJK
> characters), although emoji might be tricky.

Thanks, will fix!

--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by zevv** [comment]
Funny, I wanted to attach the snippet below to show that Duc now behaves as expected. It looks just fine in my terminal, but is rendered wrong in the browser: :)

```
  8.0K оживлённым   [+++++++++++++++++++++++++++++++++++++++++++++++++++++]
  8.0K ♜♞♝♛♚♝♞♜     [+++++++++++++++++++++++++++++++++++++++++++++++++++++]
  8.0K 有朋自遠方來 [+++++++++++++++++++++++++++++++++++++++++++++++++++++]
```
