### ISSUE TITLE
HTTPS certificate on the homepage is expired

### ISSUE THREAD

**Issue by adynathos** [zevv/duc#217]
Hello,
The certificate on https://duc.zevv.nl/ has expired.
By the way, thanks for developing this software.

**Comment by zevv** [comment]
Quoting Adynathos (2019-07-06 12:18:29)
> Hello,
> The certificate on https://duc.zevv.nl/ has expired.

Good catch, will fix. Thanks!

--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by Wingysam** [comment]
The issue seems to be fixed; Should it be closed?

**Comment by zevv** [comment]
Yes, thanks!
