### ISSUE TITLE
Export Database

### ISSUE THREAD

**Issue by WillianBR** [zevv/duc#219]
Thank you very much! 
The tool is amazing and very powerfull.  I was wondering if you are planning a feature to export/dump the database as a JSON output.  It'l be a amazing improvement.

**Comment by zevv** [comment]
There is already the XML export (duc xml), would that fit your needs?

Quoting Willian Silva (2019-07-24 15:41:00)

> The tool is amazing and very powerfull.  I was wondering if you are
> planning a feature to export/dump the database as a JSON output.  It'l
> be a amazing improvement.

**Comment by l8gravely** [comment]
Old issue.  No further feed back from requestor so closing.
