### ISSUE TITLE
Diff mode?

### ISSUE THREAD

**Issue by zvezdochiot** [zevv/duc#224]
Whether diff mode in duc is planned?

Now duc is creating a simple index, can it creating and show the diff-index between the previous index and the current state?

**Comment by l8gravely** [comment]
звездочёт> Whether diff mode in duc is planned?

Nothing concrete is planned, and I won't have time for the next month
or so to do any work.

**Comment by zvezdochiot** [comment]
@l8gravely say> Nothing concrete is planned, and I won't have time for the next month or so to do any work.

You would just say "no". Why answer so blurry?
