### ISSUE TITLE
Removing oldest entries from DB

### ISSUE THREAD

**Issue by Tomekke** [zevv/duc#235]
Hello

I've been using this program for a couple of months, very useful. But after a couple of months the DB start to grow more and more. Would it be possible to implement something that would allow the DB to rotate it's data? And a function to be able to delete some old data from the DB?

Thank you very much!

**Comment by zevv** [comment]
Quoting Tomekke (2020-03-25 09:45:06)
> Hello
> 
> I've been using this program for a couple of months, very useful. But after a couple of months the DB start to grow more and more. Would it be possible to implement something that would allow the DB to rotate it's data? And a function to be able to delete some old data from the DB?

Deleting is hard because the data is redundant in spread throughout the
database. The pragmatic solution might work for you instead: index to a
new database and move it over the old one when it is done?

--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by l8gravely** [comment]
I have to agree here.  When I re-index my DBs at $WORK, I just index to a new database, then move it over the old one.  There's no real reason to keep re-using the same old DB.  For now I'm going to close this, but if you want to try and come up with a patch to solve this, we'd be happy to look at it.

John
