### ISSUE TITLE
--dark doesn't works with webgl

### ISSUE THREAD

**Issue by yukulele** [zevv/duc#238]
If I do
```shell
./configure
make
./duc index .
./duc gui --dark
```
I get black background

but if I do
```shell
./configure --enable-opengl --disable-x11
make
./duc index .
./duc gui --dark
```
I get white background

**Comment by yukulele** [comment]
did I ask an irrelevant question?

**Comment by zevv** [comment]
Quoting Clément P (2020-04-29 10:55:24)
> did I ask an irrelevant question?

No, I fixed this 5 days ago with

https://github.com/zevv/duc/commit/718644880f59ddda3da560634ebf954126f08d09

--
:wq
^X^Cy^K^X^C^C^C^C
