### ISSUE TITLE
SSL certificate at https://duc.zevv.nl/ expired on 2020-05-07

### ISSUE THREAD

**Issue by mika** [zevv/duc#239]
The SSL certificate at https://duc.zevv.nl/ expired today:

```
% echo | openssl s_client -connect duc.zevv.nl:443 -servername duc.zevv.nl 2>/dev/null | openssl x509 -noout -dates
notBefore=Feb  7 05:14:48 2020 GMT
notAfter=May  7 05:14:48 2020 GMT
```

FYI :)

**Comment by zevv** [comment]
Thanks, fixed!

Quoting Michael Prokop (2020-05-07 15:07:19)
> The SSL certificate at https://duc.zevv.nl/ expired today:
> 
> ```
> % echo | openssl s_client -connect duc.zevv.nl:443 -servername duc.zevv.nl 2>/dev/null | openssl x509 -noout -dates
> notBefore=Feb  7 05:14:48 2020 GMT
> notAfter=May  7 05:14:48 2020 GMT
> ```
> 
> FYI :)
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/zevv/duc/issues/239


--
:wq
^X^Cy^K^X^C^C^C^C
