### ISSUE TITLE
Add in debian packaging

### ISSUE THREAD

**Issue by l8gravely** [zevv/duc#243]
Merged branch debian  into master, this is the debian/ directory and packaging from the 1.4.4 debian package.  Need to figure out how to update it to reflect the upcoming 1.4.5 release...

**Comment by jmtd** [comment]
Hi, I'm the Debian package maintainer. I'm just writing a reply to a private mail outlining basically the same as this comment, but I wonder: why have you done this? It will actually make packaging duc in Debian harder. There's some information for upstreams on Debian packaging, and what "best practises" make packaging easier for us, here: https://wiki.debian.org/UpstreamGuide#Pristine_Upstream_Source

Best wishes

**Comment by zevv** [comment]
Hi Jonathan,

> Hi, I'm the Debian package maintainer. I'm just writing a reply to a
> private mail outlining basically the same as this comment, but I
> wonder: why have you done this? It will actually make packaging duc in
> Debian harder. There's some information for upstreams on Debian
> packaging, and what "best practises" make packaging easier for us,
> here: https://wiki.debian.org/UpstreamGuide#Pristine_Upstream_Source

Thanks for your message. I already had a bit of a feeling we should not
meddle in /debian affairs as an upstream, but pulled the MR in anyway.
We'll clean this up and look at the guidlines you mentioned. Sorry for
the noise!

@John, well, there we have it! :)

Quoting Jonathan Dowland (2020-05-26 15:59:05)

**Comment by zevv** [comment]
>>>>> "Ico" == Ico Doornekamp <ico@zevv.nl> writes:

Ico> Hi Jonathan,
>> Hi, I'm the Debian package maintainer. I'm just writing a reply to a
>> private mail outlining basically the same as this comment, but I
>> wonder: why have you done this? It will actually make packaging duc in
>> Debian harder. There's some information for upstreams on Debian
>> packaging, and what "best practises" make packaging easier for us,
>> here: https://wiki.debian.org/UpstreamGuide#Pristine_Upstream_Source

Ico> Thanks for your message. I already had a bit of a feeling we should not
Ico> meddle in /debian affairs as an upstream, but pulled the MR in anyway.
Ico> We'll clean this up and look at the guidlines you mentioned. Sorry for
Ico> the noise!

Ico> @John, well, there we have it! :)

Yup, we need to revert that commit.  Not a biggee.

Jonathan,
Thank you for your reply!  We were just trying to make it easier on
you guys to package duc, but obviously I jumped in too eagerly.  We'll
make sure this isn't part of the next release.

John

**Comment by jmtd** [comment]
Hi folks, thanks for replying! No problem, I know there was no ill intent. It turns out, that the current versions of the debian packaging tools will automatically scrub any ./debian directory from the source tarball, so there might be no inconvenience anyway.
