### ISSUE TITLE
provide duc executable in AppImage format?

### ISSUE THREAD

**Issue by BobBagwill** [zevv/duc#246]
I would like to use duc on systems that I cannot compile or install additional libraries on.  An AppImage binary would be handy.  I can work on it if it's not an objectionable idea.

**Comment by zevv** [comment]
Haven't played with that yet, how would that work when we want to make a new release?

**Comment by BobBagwill** [comment]
I think you would create a GitHub Action to do the build when you tag a release.

**Comment by l8gravely** [comment]
﻿Could you maybe just compile it statically, and just enough to index the filesystem then move the dB over to a system where you can run regular doc?

The hard part will be the backend dB, and getting that to statically compile.  Of course you can just copy over the shared lib(s) you need and muck with your LD_LIBRARY_PATH Env variable on these systems.

**Comment by BobBagwill** [comment]
I will play with Github Actions and AppImage and see if I can get it to work.
