### ISSUE TITLE
Wrong units for ui file count footer

### ISSUE THREAD

**Issue by stuartthebruce** [zevv/duc#251]
Version 1.4.3 running on SL7.8 reports `MB` in the `ui` display footer, e.g.,
<pre>
Total 17.8MB in 82 files and 95 directories (file count)
</pre>
whereas the units should be `M`, i.e., no Bytes involved.

**Comment by zevv** [comment]
Hm, not sure if I understand you. This footer tells you ther eis 17.8 megabytes of disk used by 82 files and 95 directories. How is this not right?

**Comment by zevv** [comment]
Oh right, if you switch to file count with the `f` key, right!

**Comment by stuartthebruce** [comment]
Note, I use the `c` key to switch to file count. Here is another example,
<pre>
Total 13.2TB in 14 files and 30 directories (actual size)
<pre>
and use `c` to switch to `file count`,
<pre>
Total 4.1MB in 14 files and 30 directories (file count)
</pre>

**Comment by zevv** [comment]
sure, will fix.

**Comment by zevv** [comment]
fixed in e5eb93c881a31d9f3b064599f4ad53396b3189fd
