### ISSUE TITLE
Recoll / xapiandb backend

### ISSUE THREAD

**Issue by heylix** [zevv/duc#255]
Hi, as I already index my files with Recoll and xapiandb regularly, it would be nice if that was implemented as backend or source for duc.

**Comment by l8gravely** [comment]
>>>>> "Helix" == Helix  <notifications@github.com> writes:

Helix> Hi, as I already index my files with Recoll and xapiandb
Helix> regularly, it would be nice if that was implemented as backend
Helix> or source for duc.

recoll isn't the same type of DB or details, at least from what I can
see.  So pulling the data out of that tool would be a big hassle.  I
can understand wnating to limit the number of sweeps of your disk(s)
to keep down load, but I don't think it's going to happen.

But if you can provide more details... such as whether there is an API
you can use to examine the recoll DB from other programs, then maybe
it would be possible.  But not very likely.

John

**Comment by heylix** [comment]
Well, you can use/query the Xapian DB in the background. There's a [guide on how to get started](https://getting-started-with-xapian.readthedocs.io/en/latest/) on their [homepage](https://xapian.org/).

Xapian seems to have an API where you can execute database queries. As far as I see it, there are no wrappers or bindings for C yet, as they list on their barebones [docs/bindings](https://xapian.org/docs/bindings/) page.

**Comment by l8gravely** [comment]
At this point, we're looking to reduce the number of backends that are supported by duc, and not really to increase them, unless there's a huge win for us to do so.  So for now, I'm going to close this issue, but please feel free to clone the repo and try to implement the support and submit patches.  

John
