### ISSUE TITLE
adding DUC to conda

### ISSUE THREAD

**Issue by splaisan** [zevv/duc#260]
would be great to allow installing DUC using conda together with plenty of other tools and make it deployable on servers without efforts
Please :-)

**Comment by zevv** [comment]
I will allow it.

But I guess that was not your question, was it? :)

**Comment by splaisan** [comment]
No it was not :-), I had used dot for my example, just that I meanwhile used a simple parser which uses underscore and now I have code based on this. If too difficult, please ignore this feature request and I will adapt my external code.
Best
S

**Comment by zevv** [comment]
I might help you out, but I don't really understand what's needed from me or Duc - can you elaborate on that?

**Comment by splaisan** [comment]
you are right, it would help me in the first place although I can build from your source without any problem.
it was just that I see Conda as really starting to take a nice piece of the cake and apps which are available there get a substantial chance to be installed in machines (physical or virtual) just because it is so easy 
`conda install DUC` and you have it on your machine.
I understand that this means some work at your side to package it all and put it on the anaconda repo
it was just an idea

**Comment by zevv** [comment]
Ah right. Well, honestly, I don't really care for packaging for upstream, and for most distributions it is even frowned upon when an "upstream" tries to do anything smart for specific distros. So the way to go is that Duc is just a package like any other, and something/someone from Conda takes care of the building & packaging.

**Comment by splaisan** [comment]
fair enough ;-)

**Comment by l8gravely** [comment]
If you provide us with a patch documenting how to compile duc for conda, then we might consider it.  But as Zevv says, it's not really in our wheelhouse.

**Comment by splaisan** [comment]
I do not know how to prepare a conda patch, I only use conda each time I need to install software. 
Duc is easy enough to build so this thread can be closed.
Best regards
