### ISSUE TITLE
License file missing in the release distribution: chosen license ambibuous.

### ISSUE THREAD

**Issue by rhpvorderman** [zevv/duc#295]
Hi, I maintain the conda-forge feedstock for duc so that duc can be installed via conda. (Very useful as it does not require root). 
The latest release tarball does not include a license file (in v1.4.4 it was called `COPYING`). This is not necessarily a problem as I can include the license myself in the conda package instead. However, the only statement about the license that I can easily find in the package is the man page, which still states that the project is under the GPL version 2.0. 

Could you re-release the tarball with a `COPYING` or `LICENSE` file included? That seems to be the easiest way to solve any ambiguity. 

Thanks for duc!

**Comment by zevv** [comment]
Hi Ruben,  `LICENSE` has been added to the release tarball. thanks!
