### ISSUE TITLE
segfault for ls on non-existing path

### ISSUE THREAD

**Issue by stuartthebruce** [zevv/duc#301]
`duc ls` segfaults for a non-existing path.
<pre>
[root@ldas-gridmon filesystem]# cat /etc/redhat-release 
Rocky Linux release 8.6 (Green Obsidian)

[root@ldas-gridmon filesystem]# duc --version
duc version: 1.4.4
options: cairo x11 ui tokyocabinet

[root@ldas-gridmon filesystem]# duc info -d zfshome1.duc
Date       Time       Files    Dirs    Size Path
2022-10-13 17:01:02    1.4G   50.7M  435.7T /home1

[root@ldas-gridmon filesystem]# duc ls -d zfshome1.duc /nonexisting
Path /nonexisting not found in database
Requested path not found
Segmentation fault (core dumped)
</pre>

**Comment by l8gravely** [comment]
Hi Stuart,
Thanks for the report.  Looks like I'll have to spin up a RHEL8.6
system to test against.  

Have you tried using the lastest stuff on the master branch as a
quick check?  

And could you please send me where you got duc for RHEL8, or your
config.log so I can see what you're using for package versions.

Thanks,
John

**Comment by stuartthebruce** [comment]
> Hi Stuart, Thanks for the report. Looks like I'll have to spin up a RHEL8.6 system to test against.

I just checked and I also see a segfault on Scientific Linux 7.

> Have you tried using the lastest stuff on the master branch as a quick check?

I just gave that a go on SL7 and master doesn't have this problem,

$ cat /etc/redhat-release 
Scientific Linux release 7.9 (Nitrogen)

$ git log -1
commit c24ce26c58b8833512df00d71567aa7592975830 (HEAD -> master, origin/master, origin/HEAD)
Author: Ico Doornekamp <ico@zevv.nl>
Date:   Mon Jul 25 10:01:08 2022 +0200

    Added LICENSE to "make release" target

$ git/duc/duc --version
duc version: 1.4.5
options: cairo x11 ui tokyocabinet

$ git/duc/duc index -xvp git/duc
Writing to database "/home/stuart.anderson/.cache/duc/duc.db"
Indexed 249 files and 39 directories, (9.0MB apparent, 6.5MB actual) in 0.06 secs.

$ git/duc/duc info
Date       Time       Files    Dirs    Size Path
2022-10-15 15:41:37     249      39    6.5M /home/stuart.anderson/git/duc

$ git/duc/duc ls /nonexisting
Path /nonexisting not found in database
The requested path '/nonexisting' was not found in the database,
Please run 'duc info' for a list of available directories.

> And could you please send me where you got duc for RHEL8, or your config.log so I can see what you're using for package versions. Thanks, John

Since this `duc` isn't available in EPEL we spin our own. We will first try updating our RPM builds from 1.4.4 to 1.4.5 and report back here whether that was sufficient or not.

**Comment by zevv** [comment]
Gents,

This was fixed in 1.4.5 with commit 8afb1bac7b3cd1b509084cd5da2dbce31bc83fa6.


Quoting stuartthebruce (2022-10-16 01:38:04)
> > Hi Stuart, Thanks for the report. Looks like I'll have to spin up a RHEL8.6 system to test against.
> 
> I just checked and I also see a segfault on Scientific Linux 7.
> 
> > Have you tried using the lastest stuff on the master branch as a quick check?
> 
> I just gave that a go on SL7 and master doesn't have this problem,
> 
> $ cat /etc/redhat-release 
> Scientific Linux release 7.9 (Nitrogen)
> 
> $ git log -1
> commit c24ce26c58b8833512df00d71567aa7592975830 (HEAD -> master, origin/master, origin/HEAD)
> Author: Ico Doornekamp ***@***.***>
> Date:   Mon Jul 25 10:01:08 2022 +0200
> 
>     Added LICENSE to "make release" target
> 
> $ git/duc/duc --version
> duc version: 1.4.5
> options: cairo x11 ui tokyocabinet
> 
> $ git/duc/duc index -xvp git/duc
> Writing to database "/home/stuart.anderson/.cache/duc/duc.db"
> Indexed 249 files and 39 directories, (9.0MB apparent, 6.5MB actual) in 0.06 secs.
> 
> $ git/duc/duc info
> Date       Time       Files    Dirs    Size Path
> 2022-10-15 15:41:37     249      39    6.5M /home/stuart.anderson/git/duc
> 
> $ git/duc/duc ls /nonexisting
> Path /nonexisting not found in database
> The requested path '/nonexisting' was not found in the database,
> Please run 'duc info' for a list of available directories.
> 
> > And could you please send me where you got duc for RHEL8, or your config.log so I can see what you're using for package versions. Thanks, John
> 
> Since this `duc` isn't available in EPEL we spin our own. We will first try updating our RPM builds from 1.4.4 to 1.4.5 and report back here whether that was sufficient or not.
> 
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/zevv/duc/issues/301#issuecomment-1279852464
> You are receiving this because you are subscribed to this thread.
> 
> Message ID: ***@***.***>


--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by stuartthebruce** [comment]
Rebuilding 1.4.5 does indeed solve this problem.
