### ISSUE TITLE
Reading DB file problematic across OS platforms

### ISSUE THREAD

**Issue by erichweiler** [zevv/duc#310]
Hello - I'm noticing a strange issue where I create a filesystem DB on Ubuntu 22.04 (via the duc package available in the standard repos), reading it works on that system just fine:

ubuntu# duc --version
duc version: 1.4.4
options: cairo x11 ui tokyocabinet

ubuntu# duc ls -d /data/duc/dbs/fileset.db /export/mydata
 40.0T dir1
 23.2T dir2
 15.0T dir3

But if I copy that same "/data/duc/dbs/fileset.db" file to one of our CentOS 7.9 servers (duc compiled by hand) to use there, it no longer works, even though the duc version is the same:

centos# duc --version
duc version: 1.4.4
options: cairo x11 ui tokyocabinet

centos# duc ls -d /data/duc/dbs/fileset.db /export/mydata
Error opening: /data/duc/dbs/fileset.db - Unknown error, contact the author

However, duc DBs created *on* CentOS 7.9 work just fine *on* CentOS 7.9.  But we are running duc across may different servers and platforms and we are copying the files to a central server for viewing, so necessarily they will be built on different OS platforms.  Is this a known issue?  Or maybe I am missing a small step somewhere?

The versions of tokyocabinet are pretty near the same version:

centos# rpm -q tokyocabinet
tokyocabinet-1.4.48-3.el7.x86_64

ubuntu# apt list | grep libtokyocabinet9
libtokyocabinet9/jammy,now 1.4.48-14build1 amd64 [installed]

Thanks for any insight!

**Comment by zevv** [comment]
yeah, Tokyocabinet has been causing us a lot of headaches over the years; long ago this was chosen as the default db implementation for Duc to rely on because it was the fastest and generated the smallest db size at that time, but it has since proven to be unreliable and not very portable. It has also been unmaintained for years, which does not help.

Ideally, we should switch database backend to a more solid alternative, but that will be a hairy transition with the existing install base of course.

For now, I'd advise to make a custom build (if you don't already do that) and switch to sqlite as the backend; this has proven to be stable and portable, although it will likely slow things down for you.

**Comment by erichweiler** [comment]
Absolutely right.  And now I see in the documentation that it's mentioned that tokyocabinet is not very portable, sorry for not seeing that earlier!  I rebuilt the binaries using sqlite3 and it now works like a charm between platforms.  And it's only a little slower for me, not enough to complain about by any stretch.  Thanks for the tip!

**Comment by l8gravely** [comment]
>>>>> "Ico" == Ico Doornekamp ***@***.***> writes:

> yeah, Tokyocabinet has been causing us a lot of headaches over the
> years; long ago this was chosen as the default db implementation for
> Duc to rely on because it was the fastest and generated the smallest
> db size at that time, but it has since proven to be unreliable and
> not very portable. It has also been unmaintained for years, which
> does not help.

Maybe we just bite the bullet and release v2.0 with a change in
default DB, but maybe also compile in tokyocabinet support as a
fallback?  

But... as shown here, this is hard to do with tokyocabinet being so
fragile just moving between Linux distros.  

> Ideally, we should switch database backend to a more solid
> alternative, but that will be a hairy transition with the existing
> install base of course.

I thought lmdb was a good choice, but honestly don't remember the
status.

It might also be time to just pick an external DB and pull it into the
source code and package it with duc moving forward as a known
situation.

**Comment by l8gravely** [comment]
I'm closing this issue since you have a solution for now.
