### ISSUE TITLE
Folder mounted with NFS4 are not indexed.

### ISSUE THREAD

**Issue by sty1103** [zevv/duc#322]
Hello, I am developing a real-time monitoring system, and I am using duc to pre-index a directory to check the usage of the server.

General directories are indexed well, but network directories mounted with nfs4 are not indexed.

My execution environment is bellow.

- OS: Ubuntu 20.04
- duc Version: 1.4.3 options: cairo x11 ui tokyocabinet
- mount info:
```
$ df -h /DATA

Filesystem           Size  Used Avail Use% Mounted on
xxx.xxx.xxx.xxx:/DATA 5.5T 1.4T 3.9T 27% /DATA
```

```$ duc index /DATA```

If i use the above command, it can be executed

```$ duc info```

However, When I use the above command, nothing is displayed.

It was the same even if I used the sudo command together.

How do I index an nfs4 directory?

**Comment by zevv** [comment]
Can you run the `duc index` command with `--verbose --debug` flags?

**Comment by sty1103** [comment]
It works! Thank you.

But how does it work?
Can i use verbose, debug flag in crontab?

```*/30 * * * * duc index --verbose --debug /DATA```

**Comment by zevv** [comment]
Well, this was not supposed to *solve* your issue, it was just supposed to output verbose information during indexing to see what is happening so we can debug the problem.

Please retry with and without these arguments, the behavior of `duc index` should not change when these flags are passed, you should not need those flags in normal operation.

**Comment by l8gravely** [comment]
>>>>> "JeongHyeonjun" == JeongHyeonjun  ***@***.***> writes:

> It works! Thank you.
> But how does it work?
> Can i use verbose, debug option in crontab?

> */30 * * * * duc index --verbose --debug /DATA

I wonder if your /DATA directory is automounted, and the first time
duc comes along, it's not mounted, and when you run it again, it is
mounted.

But we'd need to see more details to really understand what's
happening.  One quick dumb hack might be to have your cronjob be a
script which does:

      
   #!/bin/bash

   ls /DATA > /dev/null
   duc index /DATA

But as Ico says, it's hard to know. Please post some of the outout
(not all!) of the --debug and --verbose so we can look at what's going
on.

John

**Comment by l8gravely** [comment]
Any updates here before I close this issue?

**Comment by sty1103** [comment]
Thank you for your advice. Since it is currently working fine, I will close the issue.
