### ISSUE TITLE
checking the return code of fwrite() calls

### ISSUE THREAD

**Issue by alexmyczko** [zevv/duc#328]
there's only three places with fwrite():
https://github.com/search?q=repo%3Azevv%2Fduc%20fwrite&type=code

if you could check the return code, and check if it's feof or ferror, and handle that gracefully,
you'd not get these:

3280534 Bus error               (core dumped) duc index
2385968 Bus error               (core dumped) duc index
4171965 Bus error               (core dumped) duc index
946551 Segmentation fault      duc index

would that be great to do?

**Comment by zevv** [comment]
Excellent idea, I'd be more than happy to merge a PR for this!

**Comment by l8gravely** [comment]
>>>>> "Alex" == Alex Myczko ***@***.***> writes:

> there's only three places with fwrite():
> https://github.com/search?q=repo%3Azevv%2Fduc%20fwrite&type=code

> if you could check the return code, and check if it's feof or ferror, and handle that gracefully,
> you'd not get these:

> 3280534 Bus error (core dumped) duc index
> 2385968 Bus error (core dumped) duc index
> 4171965 Bus error (core dumped) duc index
> 946551 Segmentation fault duc index

> would that be great to do?

Yup!  Can you tell me what you use to re-create these crashes reliably
so I can add it to the test case I try to use?  

John

**Comment by alexmyczko** [comment]
@l8gravely easy fill the disk you run duc in, write the db file on that filesystem, profit!

**Comment by l8gravely** [comment]
>>>>> "Alex" == Alex Myczko ***@***.***> writes:

> @l8gravely easy fill the disk you run duc in, write the db file on
> that filesystem, profit!

Thanks, that will help.  I've got some simple patches for this.  Not
sure that 'frwite(..., stdout)' will ever really fail, but simple
enough to check.

I'll see what I can do to improve this edge case handling.

**Comment by l8gravely** [comment]
So here's a set of patches for you to test please:

From 1b64bc4b659c13de9eb8305a62d5ac6a942bd7f0 Mon Sep 17 00:00:00 2001
From: John Stoffel ***@***.***>
Date: Sat, 17 Aug 2024 11:57:42 -0400
Subject: [PATCH] handle fwrite() errors more gracefully

---
 src/duc/cmd-cgi.c              | 8 +++++---
 src/duc/main.c                 | 4 +++-
 src/libduc-graph/graph-cairo.c | 5 ++++-
 3 files changed, 12 insertions(+), 5 deletions(-)

diff --git a/src/duc/cmd-cgi.c b/src/duc/cmd-cgi.c
index 7cd3f64..ae2fbe8 100644
--- a/src/duc/cmd-cgi.c
+++ b/src/duc/cmd-cgi.c
@@ -257,9 +257,11 @@ static void include_file(const char *fname)
 		printf("\n");
 		for(;;) {
 			char buf[4096];
-			size_t n = fread(buf, 1, sizeof(buf), f);
-			if(n == 0) break;
-			fwrite(buf, 1, n, stdout);
+			size_t in = fread(buf, 1, sizeof(buf), f);
+			if(in == 0) break;
+			size_t out = fwrite(buf, 1, in, stdout);
+			if(out == 0) break;
+			if(out < in) break;
 		}
 		printf("\n");
 		fclose(f);
diff --git a/src/duc/main.c b/src/duc/main.c
index 9a4906e..287abfe 100644
--- a/src/duc/main.c
+++ b/src/duc/main.c
@@ -211,6 +211,7 @@ static void printi(const char *s, int pos, int indent, int max)
 	const char *p1 = s;
 	const char *p2 = s;
 	int i;
+	int out;
 
 	while(*p1) {
 		while(*p2 && !isspace(*p2)) p2++;
@@ -222,7 +223,8 @@ static void printi(const char *s, int pos, int indent, int max)
 			pos = indent;
 		}
 
-		fwrite(p1, l, 1, stdout);
+		out = fwrite(p1, l, 1, stdout);
+		if (out == 0) break;
 		while(*p2 && isspace(*p2)) p2++;
 		pos += l;
 		if(pos < max) {
diff --git a/src/libduc-graph/graph-cairo.c b/src/libduc-graph/graph-cairo.c
index 3e83279..3cce019 100644
--- a/src/libduc-graph/graph-cairo.c
+++ b/src/libduc-graph/graph-cairo.c
@@ -41,7 +41,10 @@ struct cairo_backend_data {
 static cairo_status_t cairo_writer(void *closure, const unsigned char *data, unsigned int length)
 {
 	FILE *f = closure;
-	fwrite(data, length, 1, f);
+	size_t out = fwrite(data, length, 1, f);
+	if (out == 0 || out < length) {
+	    return CAIRO_STATUS_WRITE_ERROR;
+	}
 	return CAIRO_STATUS_SUCCESS;
 }
 
-- 
2.39.2

**Comment by l8gravely** [comment]
So I've applied this proposed patch to 1.5.0-rc1 which you can now try out.  I'm closing this ticket for now, please open new issues with the new release.
