### ISSUE TITLE
Duc calculates file size, not disk usage

### ISSUE THREAD

**Issue by zevv** [zevv/duc#44]
At this time Duc indexes file sizes, but not he actual disk usage like du and df. This is confusing for some users because the numbers differ, and for some users calculating disk usage instead of file size is Just The Right Thing To Do.

I see two obvious solutions:

- The indexer gets an option so at index time the user chooses to count either file size or disk usage

- The indexer keeps track of both, and the user chooses at display time which to show.

Any feedback welcome.

**Comment by arrjay** [comment]
I'd rather have the indexer record both numbers and leave it up to the display functions for chosing what to graph - this would let you do neat things like actively find sparse files when fiddling with the index database directly.

**Comment by zevv** [comment]
I'm working on this one. The database will keep two sizes for each fild/dir: the apparent file size (old behaviour) and actual file size (disk blocks used). Size of the database will increase, I'll report some measurements when I get to it.

The various tools will be extended with an option to choose between apparent and actual size when displaying.

**Comment by zevv** [comment]
This functionality is available in the new disk-usage branch. Indexing speed is not affected measurably for me, the index file is approx 6% larger for my system. I find this increase in database size acceptable for the given functionality.

Disk usage is now counted twice in two modes: actual disk usage (blocks) and apparent file size (st.st_size). The user can choose which to display by specifying the -a flag, or use the 'a' key in gui mode.

With this change <b>Duc's default mode for counting size is to use disk usage, not apparent file size</b>

**Comment by zevv** [comment]
Merged to trunk
