### ISSUE TITLE
Is it time for a config file?

### ISSUE THREAD

**Issue by zevv** [zevv/duc#49]
Duc has a lot of options already, and it seems that there is some functionality that people would like to save.

It might be time to get started with implementing a configuration file with default settings and preferences. The configuration file should be optional if possible, but if it is found the settings should be used if applicable.

Some things that should go in there:

- database path
- verbose operation / debugging
- default path to start from 'duc gui' tool, etc

I propose a simple format with different sections, one for each duc subcommand, and one with global options. I guess it will be flexible enough if the config file simple uses the exact same options as the command line, so everything will be unambigious and self-documenting.

For example:

```
[global]

database-path=/var/duc/duc.db
verbose

[index]

hide-files
maxdepth=5

[ls]

graph
human-readable
recursive
```

Configuration files are searched in different paths, and settings are overruled be subsequent files found. Search order:

- .duc.conf
- ~/.duc.conf
- /etc/duc.conf

The only thing that has to be defined is a way to cancel options which were found earlier. The vim-way should do; simple prepend 'no-' to a setting to cancel it. 

```
no-hide-files
no-recursive
```

Does the above make sense?

**Comment by d33psky** [comment]
Yes, this would be great to have.

**Comment by zevv** [comment]
For those interested, please check put the branch 'ducrc', this kind of implements the above.

getopt() option handling in each duc cmd is now replaced by general mechanism for handling configuration option. Each subcommand can register a number of options, which get parsed by the main function.

Options can be configured through the command line (mostly compatibly with old code), or via one of the config files /etc/duc.rc, ~/.duc.rc and ./.duc.rc.

An example config file is provided in the examples directory.

Any feedback appreciated.

```
duc help [options]: Show help

  -a,  --all             show complete help for all commands

duc info [options]: Dump database info

  -d,  --database=VAL    select database file to use [~/.duc.db]

duc index [options] PATH ...: Index filesystem

  -d,  --database=VAL    use database file ARG
  -e,  --exclude=VAL     exclude files matching ARG
  -f,  --force           force writing in case of corrupted db
       --hide-files      hide file names, index only directories
  -m,  --maxdepth=VAL    limit directory names to given depth
  -x,  --one-file-system don't cross filesystem boundaries
       --uncompressed    do not use compression for database

duc gui [options] [PATH]: Graphical interface

  -d,  --database=VAL    select database file to use [~/.duc.db]
       --fuzz=VAL        use radius fuzz factor when drawing graph
  -l,  --levels=VAL      draw up to ARG levels deep [4]
       --palette=VAL     select palette <size|rainbow|greyscale|monochrome>

duc ls [options] [PATH]: List directory

       --ascii           use ASCII characters instead of UTF-8 to draw tree
  -b,  --bytes           show file size in exact number of bytes
  -F,  --classify        append file type indicator (one of */) to entries
  -c,  --color           colorize output
  -d,  --database=VAL    select database file to use [~/.duc.db]
  -g,  --graph           draw graph with relative size for each entry
  -R,  --recursive       list subdirectories in a recursive tree view

duc graph [options] [PATH]: Draw graph

  -d,  --database=VAL    select database file to use [~/.duc.db]
  -f,  --format=VAL      select output format <png|svg|pdf> [png]
       --fuzz=VAL        use radius fuzz factor when drawing graph [0.7]
  -l,  --levels=VAL      draw up to ARG levels deep [4]
  -o,  --output=VAL      output file name [duc.png]
       --palette=VAL     select palette <size|rainbow|greyscale|monochrome>
  -s,  --size=VAL        image size [800]

duc xml [options] [PATH]: Dump XML output

  -d,  --database=VAL    select database file to use [~/.duc.db]
  -s,  --min_size=VAL    specify min size for files or directories
  -x,  --exclude         exclude file from xml output, only include directories

duc cgi [options] [PATH]: CGI interface

  -d,  --database=VAL    select database file to use [~/.duc.db]
       --fuzz=VAL        use radius fuzz factor when drawing graph [0.7]
  -l,  --levels=VAL      draw up to ARG levels deep [4]
  -o,  --output=VAL      output file name [duc.png]
       --palette=VAL     select palette <size|rainbow|greyscale|monochrome>
  -s,  --size=VAL        image size [800]
```

**Comment by zevv** [comment]
Just merged this into master

**Comment by nonsns** [comment]
great!
