### ISSUE TITLE
proc gets indexed while --one-file-system was given

### ISSUE THREAD

**Issue by d33psky** [zevv/duc#54]
Test VM running Ubuntu 12.04.3 LTS , https://github.com/zevv/duc/archive/master.zip of 20150121

created index with : duc index --verbose --one-file-system /

duc ls / -Fcg
shows proc (with 128.0T) as first item ;-)

The indexer should skip proc, especially with --one-file-system

**Comment by zevv** [comment]
Duplicate of #55
