### ISSUE TITLE
featurerequest: overall graph of multiple datasets in a database

### ISSUE THREAD

**Issue by d33psky** [zevv/duc#56]
Or support indexing on multiple given filesystems, like : 
duc index -x / /data /someothermount

If I do : 
duc index -x /
duc index -x /data
dux index -x /someothermount
I get a database with multilpe datasets and no option to make a combined graph of them.

**Comment by zevv** [comment]
* On 2015-01-22 13:18:03 +0100, d33psky wrote:
 
> Or support indexing on multiple given filesystems, like : 
> duc index -x / /data /someothermount
> 
> If I do : 
> duc index -x /
> duc index -x /data
> dux index -x /someothermount
> I get a database with multilpe datasets and no option to make a combined graph of them.

True: there are multiple trees in the database, but their content is not
yet merged. Ideally, the /data and /someothermount would appear in the
same view as /, but this is not the case yet.

I'm currently working on a solution for threading or merging databases,
I'll keep this ticket open as a reminder.

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by ghuls** [comment]
@d33psky

I don't know if it will work for your case, but I wrote some wrapper function around duc, which uses different databases, depending on the requested path.

I only tested it with:

```
duce ls <path>
```

But is should also work in some other conditions.

#33

**Comment by zevv** [comment]
Closing this ticket for now. The request has been added to `TODO.md`
