### ISSUE TITLE
Unable to view subfolders on some mounts

### ISSUE THREAD

**Issue by narthollis** [zevv/duc#57]
nsteicke@media ~ $ rm .duc.db
nsteicke@media ~ $ duc index -v /store/
Writing to database "/home/nsteicke/.duc.db"
Skipping titan.a.e_2000: Permission denied
Skipping _UNPACK_Dredd.2012.1080p.BluRay.x264-SPARKS: Permission denied
Skipping kikis.delivery.service_1989: Permission denied
Skipping howls.moving.castle_2004: Permission denied
Indexed 44252 files and 1568 directories, (9.7TB total) in 0.09 secs.
nsteicke@media ~ $ duc
duc        duc.debug
nsteicke@media ~ $ duc gui
Path /home/nsteicke not found in database
Requested path not found
nsteicke@media ~ $ duc gui /store/
ERROR: Could not open display
nsteicke@media ~ $ duc ls /store/
  9.5T video
 85.1G Game of Thrones
 48.1G temp
 20.0G Thief
  9.2G books
  4.3G Audio
1010.5M proxmox
592.4M FreeLancer
222.0M template
222.0M debian-7.6.0-amd64-netinst.iso
  1.6M avcon2013.tar.bz2
   427 advancedsettings.xml
   212 backward.sh
   204 benchmark.sh
     0 virtuals
     0 dump
nsteicke@media ~ $ duc ls /store/video/
Key 7fff00000001/0 not found in database
Requested path not found

**Comment by zevv** [comment]
Hi,

I'm a bit confused by the numbers 7fff00000001/0, these should map to
the device id (dev_id) and inode number of the path you're querying.

Could you send the output of

  find /store/video/ -maxdepth 0 -printf "%i %D %p\n"

and, if privacy allows to, send my a copy of your database file (in
private mail)?


* On 2015-01-30 14:13:12 +0100, Nicholas Steicke wrote:
 
> nsteicke@media ~ $ rm .duc.db
> nsteicke@media ~ $ duc index -v /store/
> Writing to database "/home/nsteicke/.duc.db"
> Skipping titan.a.e_2000: Permission denied
> Skipping _UNPACK_Dredd.2012.1080p.BluRay.x264-SPARKS: Permission denied
> Skipping kikis.delivery.service_1989: Permission denied
> Skipping howls.moving.castle_2004: Permission denied
> Indexed 44252 files and 1568 directories, (9.7TB total) in 0.09 secs.
> nsteicke@media ~ $ duc
> duc        duc.debug
> nsteicke@media ~ $ duc gui
> Path /home/nsteicke not found in database
> Requested path not found
> nsteicke@media ~ $ duc gui /store/
> ERROR: Could not open display
> nsteicke@media ~ $ duc ls /store/
>   9.5T video
>  85.1G Game of Thrones
>  48.1G temp
>  20.0G Thief
>   9.2G books
>   4.3G Audio
> 1010.5M proxmox
> 592.4M FreeLancer
> 222.0M template
> 222.0M debian-7.6.0-amd64-netinst.iso
>   1.6M avcon2013.tar.bz2
>    427 advancedsettings.xml
>    212 backward.sh
>    204 benchmark.sh
>      0 virtuals
>      0 dump
> nsteicke@media ~ $ duc ls /store/video/
> Key 7fff00000001/0 not found in database
> Requested path not found
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/zevv/duc/issues/57

-- 
:wq
^X^Cy^K^X^C^C^C^C
