### ISSUE TITLE
Remove incorrect path

### ISSUE THREAD

**Issue by silviuvulcan** [zevv/duc#58]
It might be that I didn't find the right command but I can't seem to be able to remove a wrongly indexed path:

```
$ duc index /trwtwet
Skipping /trwtwet: No such file or directory
Indexed 0 files and 0 directories, (0B total) in 0.00 secs.

$ duc info
  2015-02-02 13:21:01  244.6G /data/audio
  2015-02-02 13:19:55       0 /trwtwet
```

Is there a way to remove that path from the database? Other than removing and reindexing everything else?

Cheers

**Comment by zevv** [comment]
* On 2015-02-02 12:25:02 +0100, Silviu Vulcan wrote:
 
> It might be that I didn't find the right command but I can't seem to be able to remove a wrongly indexed path:
> ```
> $ duc index /trwtwet
> Skipping /trwtwet: No such file or directory
> Indexed 0 files and 0 directories, (0B total) in 0.00 secs.
> 
> $ duc info
>   2015-02-02 13:21:01  244.6G /data/audio
>   2015-02-02 13:19:55       0 /trwtwet
> ```
> 
> Is there a way to remove that path from the database? Other than removing and reindexing everything else?

Not at this time. I'll leave this ticket open as a reminder to implement
this functionality one day, though :)

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by zevv** [comment]
I'm closing this one as a 'wontfix' for now.
