### ISSUE TITLE
Query for access times

### ISSUE THREAD

**Issue by stlorenz** [zevv/duc#61]
Hi,

i am wondering if it is possible to query the db for files ordered by access time.

**Comment by zevv** [comment]
* On 2015-02-13 10:59:09 +0100, Stefan Lorenz wrote:
 
> Hi,
> 
> i am wondering if it is possible to query the db for files ordered by access time.  

No other metadata then file size is currently stored in the database, so
no, not possible.

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by l8gravely** [comment]
>>>>> "zevv" == zevv  <notifications@github.com> writes:

zevv> * On 2015-02-13 10:59:09 +0100, Stefan Lorenz wrote:
>> Hi,
>> 
>> i am wondering if it is possible to query the db for files ordered by access time.

zevv> No other metadata then file size is currently stored in the database, so
zevv> no, not possible.

I've been slowly trying to add in support for per-directory file
counts, but been totally swamped with other work.  

John

**Comment by zevv** [comment]
I consider this out of scope for now, so closing the issue.
