### ISSUE TITLE
build problem on Ubuntu

### ISSUE THREAD

**Issue by jimsalterjrs** [zevv/duc#73]
followed the directions for Ubuntu, ended up with:

`duc: error while loading shared libraries: libduc.so.1: cannot open shared object file: No such file or directory`

Worked around it for now with `cd ~/git/duc; cp -a ./lib/.libs/* /usr/lib` but that kinda sucks. You're gonna need to double-check your build script, methinks.

**Comment by zevv** [comment]
* On 2015-04-20 16:52:58 +0200, Jim Salter wrote:
 
> `duc: error while loading shared libraries: libduc.so.1: cannot open
> shared object file: No such file or directory`
> 
> Worked around it for now with `cd ~/git/duc; cp -a ./lib/.libs/*
> /usr/lib` but that kinda sucks. You're gonna need to double-check your
> build script, methinks.

Thanks for the report. It seems that your shared library cache does not
get updated after 'make intall'. I'm able to reproduce, so I'll try to
fix this automatically in the system.

The proper solution for this is to run 'ldconfig' (as root) after the
make install phase.

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by zevv** [comment]
Fixed with 8e2a741. 'make install' no runs ldconfig after installing the libraries so the system knows where to find the libs when running duc.

**Comment by jimsalterjrs** [comment]
Are you still leaving the libraries in the build directory?  Gotta be honest, I pretty much hate that.  This is about as sysadmin-y a tool as I can imagine, and as a sysadmin, I don't like running production code out of user home directories! =)

**Comment by zevv** [comment]
No, I'm not. The libraries are installed where they shoud, which is /usr/local/bin by default. Check the output of 'make install', this will tell you exactly what it is doing and where all the files  are copied to.

There's no magic involved here, the only problem was that your ld cache was not up to date after installing.

**Comment by jimsalterjrs** [comment]
Well, that's certainly better than running linked to the home directory - but why not put the libraries in /usr/local/lib?  That's generally where I'd expect to see libraries that binaries in /usr/local/bin are referencing.

**Comment by zevv** [comment]
* On 2015-04-20 17:25:15 +0200, Jim Salter wrote:
 
> Well, that's certainly better than running linked to the home directory - but why not put the libraries in /usr/local/lib?  That's generally where I'd expect to see libraries that binaries in /usr/local/bin are referencing.

That was my typo, it's indeed /usr/local/lib.

-- 
:wq
^X^Cy^K^X^C^C^C^C
