### ISSUE TITLE
some CGI graphs don't work

### ISSUE THREAD

**Issue by daduke** [zevv/duc#76]
Hi Ico,

sorry, not quite done yet :)
It's almost working now, but one thing we noticed: when displaying CGI graphs, some clicks on the graph just yield a broken icon. I do not see a pattern, but here's what I know:

* all other interfaces (`ls`, `graph`, `gui` and `ui`) seem to work fine
* in the apache log, a *working* request reads `[Tue Apr 21 09:28:35 2015] [error] [client 192.33.x.y] /opt/usradm2/htdocs/groupreport/webreport/qo/qo/index.cgi: line 2: 17876 Segmentation fault      /opt/duc/bin/duc cgi -d duc.db, referer: https://admin.phys.ethz.ch/groupreport/webreport/qo/qo/index.cgi?cmd=index&path=/export/groupdata/qo`
* a *broken* requests results in `[Tue Apr 21 09:28:41 2015] [error] [client 192.33.x.y] /opt/usradm2/htdocs/groupreport/webreport/qo/qo/index.cgi: line 2: 17880 Segmentation fault      /opt/duc/bin/duc cgi -d duc.db, referer: https://admin.phys.ethz.ch/groupreport/webreport/qo/qo/index.cgi?cmd=index&path=/export/groupdata/qo`
`[Tue Apr 21 09:28:41 2015] [error] [client 192.33.x.y] Requested path not found, referer: https://admin.phys.ethz.ch/groupreport/webreport/qo/qo/index.cgi?cmd=index&path=/export/groupdata/qo&?451,296`
`[Tue Apr 21 09:28:41 2015] [error] [client 192.33.x.y] , referer: https://admin.phys.ethz.ch/groupreport/webreport/qo/qo/index.cgi?cmd=index&path=/export/groupdata/qo&?451,296`
`[Tue Apr 21 09:28:41 2015] [error] [client 192.33.x.y] Premature end of script headers: index.cgi, referer: https://admin.phys.ethz.ch/groupreport/webreport/qo/qo/index.cgi?cmd=index&path=/export/groupdata/qo&?451,296`
* I can provide a full `strace` log and the DB file if needed

thanks,
-Christian

**Comment by zevv** [comment]
* On 2015-04-21 09:41:56 +0200, Christian Herzog wrote:
 
> sorry, not quite done yet :) It's almost working now, but one thing we
> noticed: when displaying CGI graphs, some clicks on the graph just
> yield a broken icon. I do not see a pattern, but here's what I know:
> 
> * all other interfaces (`ls`, `graph`, `gui` and `ui`) seem to work
> fine * in the apache log, a *working* request reads `[Tue Apr 21
> 09:28:35 2015] [error] [client 192.33.x.y]
> /opt/usradm2/htdocs/groupreport/webreport/qo/qo/index.cgi: line 2:
> 17876 Segmentation fault      /opt/duc/bin/duc cgi -d duc.db, referer:
> https://admin.phys.ethz.ch/groupreport/webreport/qo/qo/index.cgi?cmd=index&path=/export/groupdata/qo`
> * a *broken* requests results in `[Tue Apr 21 09:28:41 2015] [error]
> [client 192.33.x.y]
> /opt/usradm2/htdocs/groupreport/webreport/qo/qo/index.cgi: line 2:
> 17880 Segmentation fault      /opt/duc/bin/duc cgi -d duc.db, referer:

There it is, the segfault.

Debugging segmentation faults from CGI's is not real fun to do. Can you
reproduce with

$ duc graph /export/groupdata/qo

and if so, could you run duc in gdb or valgrind?

  $ gdb duc
  (gdb) r graph /export/groupdata/qo

or

  $ valgrind duc graph /export/groupdata/qo

and return the output?

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by daduke** [comment]
I know debugging CGIs is a PITA.. unfortunately, the other output channels work fine, no segfault in any of them. Here's the strace output in case that helps: http://www.phys.ethz.ch/~daduke/log.err

**Comment by zevv** [comment]
* On 2015-04-21 11:54:55 +0200, Christian Herzog wrote:
 
> I know debugging CGIs is a PITA.. unfortunately, the other output
> channels work fine, no segfault in any of them. Here's the strace
> output in case that helps: http://www.phys.ethz.ch/~daduke/log.err

I'm afraid the strace output does not tell me enough to pinpoint the
problem. There's not much special going on systemcall-wise during
querying, but there's a lot of fiddling with variable length buffers and
strings, which doesn't show up in strace. 

Maybe we can trigger the bug from the command line by fooling duc to
think that it is running under CGI context. Could you try the following:

  export QUERY_STRING="cmd=index&path=/export/groupdata/qo&?457,311" 
  duc cgi -d duc.db

And if that crashes, run the same command on gdb or valgrind?

Thanks,

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by daduke** [comment]
sure! not much happening tho:

`(gdb) r cgi -d duc.db /export/groupdata/qo`
`Starting program: /opt/duc/bin/duc cgi -d duc.db /export/groupdata/qo`
`[Thread debugging using libthread_db enabled]`
`Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".`
`Content-Type: text/html`

`<!DOCTYPE html>`
`<head>`
`<style>`
`body { font-family: 'arial', 'sans-serif'; font-size: 11px; }`
`table, thead, tbody, tr, td, th { font-size: inherit; font-family: inherit; }`
`#list { 100%; }`
`#list td { padding-left: 5px; }`
`</style>`
`</head>`
`[Inferior 1 (process 31235) exited normally]`

**Comment by zevv** [comment]
Sorry, it seems that another CGI variable needs to be set to fool Duc to run in CGI mode, it can be empty however

```
export SCRIPT_NAME=""
```

**Comment by daduke** [comment]
ok now we get a bit more:

```
Starting program: /opt/duc/bin/duc cgi -d duc.db /export/groupdata/qo
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Content-Type: text/html

<!DOCTYPE html>
<head>
<style>
body { font-family: 'arial', 'sans-serif'; font-size: 11px; }
table, thead, tbody, tr, td, th { font-size: inherit; font-family: inherit; }
#list { 100%; }
#list td { padding-left: 5px; }
</style>
</head>
<center><table id=list><tr><th>Path</th><th>Size</th><th>Files</th><th>Directories</th><th>Date</th><th>Time</th></tr><tr><td><a href='?cmd=index&path=/export/groupdata/qo'>/export/groupdata/qo</a></td><td>688.5G</td><td>1746254</td><td>78314</td><td>2015-04-21</td><td>08:52:08</td></tr>
</table><a href='?cmd=index&path=/export/groupdata/qo/Paper&'><img src='?cmd=image&path=/export/groupdata/qo/Paper' ismap='ismap'>
</a><br>
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff5b6f959 in free () from /lib/x86_64-linux-gnu/libc.so.6
```

**Comment by zevv** [comment]
* On 2015-04-23 09:46:06 +0200, Christian Herzog wrote:
 
> ok now we get a bit more:

Great! If you now run this in gdb or valgrindd we should get a nice
stack trace. 

(If privacy allows, you could also send me the database file, as this is
probably easiest to fix if I'm able to reproduce locally.)

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by daduke** [comment]
errr that actually was the gdb output :)

anywhooo here's the DB file: http://www.phys.ethz.ch/~daduke/duc-qo.db

thanks

**Comment by zevv** [comment]
* On 2015-04-23 10:41:05 +0200, Christian Herzog wrote:
 
> errr that actually was the gdb output :)

Ah, of course, gdb does not give you the backtrace right away. It needs
the 'backtrace' command for that

(gdb) bt


> anywhooo here's the DB file: http://www.phys.ethz.ch/~daduke/duc-qo.db

Even better, thanks!

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by daduke** [comment]
for completeness' sake:

```
(gdb) bt
#0  0x00007ffff5b6f959 in free () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff7bd9dc7 in duc_dir_close (dir=dir@entry=0x61a350) at dir.c:250
#2  0x0000000000404635 in cgi_main (duc=0x60b8b0, argc=<optimized out>, argv=<optimized out>) at cmd-cgi.c:273
#3  0x0000000000402ede in main (argc=1, argv=0x7fffffffe498) at main.c:140
```

**Comment by zevv** [comment]
* On 2015-04-23 10:44:19 +0200, Christian Herzog wrote:
 
> for completeness' sake:

Thanks for that. I'm able to reproduce here, so the fix should be near.
Not much time today though, so don't wait for it.

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by daduke** [comment]
I'm not in a hurry.

**Comment by zevv** [comment]
Please pull & retry!

* On 2015-04-23 10:51:12 +0200, Christian Herzog wrote:
 
> I'm not in a hurry.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/zevv/duc/issues/76#issuecomment-95494288

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by daduke** [comment]
working beautifully. thank you Sir!

**Comment by zevv** [comment]
* On 2015-04-23 14:12:55 +0200, Christian Herzog wrote:
 
> working beautifully. thank you Sir!

Great, closing the issue, thanks for testing.

My current wishlist of functionality is kind of complete, so my goal is
to go for a stable release in the near future. Please let me know any
other bugs or strange behaviour!

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by zevv** [comment]
Bug fixed, closing issue
