### ISSUE TITLE
Toplist below graph in CGI

### ISSUE THREAD

**Issue by roccolord** [zevv/duc#79]
It would be a great enhancement if a toplist (in text) could be printed below the graph in cgi mode. Like the one in duc ui or philesight for that matter.

It's really a nice feature if you are search for a specific folder (think duc of a backup dir for many hosts so finding the host you want to have a look at), if the folder you are trying to find isn't one of the biggest then it's hard to find it with the cgi as it is now.

Apart from that, luv the duc!

**Comment by zevv** [comment]
Added in ab10309..639912c in master branch. Enable with --list option on duc-cgi by using a cgi wrapper script or adding to ducrc config file, let me know if this works for you.

Style of the CGI is always an issue, probably nobody will be happy with the current style. I'll add a separate option to `duc cgi` to specify a CSS url.

**Comment by zevv** [comment]
I just added the --css-url option to `duc cgi`. Use this to point to your custom CSS if you do not like the embedded style sheet.

**Comment by roccolord** [comment]
Excellent, works a charm! Now everything about Duc is better then Philesight!

Also thanks for extreme speed in handling my request!

**Comment by zevv** [comment]
* On 2015-04-27 16:45:26 +0200, roccolord wrote:
 
> Excellent, works a charm! Now everything about Duc is better then
> Philesight!

Good to hear. There's always stuff to improve, I've got my wishlist for
version 2 ready!

> Also thanks for extreme speed in handling my request!

That was just luck, al already had the code lying around in a different
branch, more or less :)

-- 
:wq
^X^Cy^K^X^C^C^C^C
