### ISSUE TITLE
Problem with special characters in  cgi mode

### ISSUE THREAD

**Issue by olivluca** [zevv/duc#82]
This is the cgi script I'm using behind lighttpd (which omits QUERY_STRING if empty, so I compensate for that).
<pre>
#!/bin/bash
if [ -z $QUERY_STRING ] ; then
  QUERY_STRING=""
  export QUERY_STRING
fi  
/home/luca/duc/duc cgi -d /var/www/duc.db --list 2>&1
</pre>

There are two problems with files with special characters:

The first is that the page doesn't specify the charset (utf-8 in my case) so the names appears garbled. If I manually select utf-8 in the browser they show correctly.

The second is that clicking on such a link I get the following error (the text of the link was "UB1_Completación"):

<pre>
Requested path not found
/net/netapp01/vol/Data/home/samba/proyectos/proyectos/11/1115/publico/05 documentacion/10 entrega documentacion final a cliente/07 Entrega Final 140715/Bloque_13-Programas_de_Automatas/13.03_Imagenes_Variantes/UB1_Completaciÿffffc3ÿffffb3n
</pre>

Clicking on the imagemap corresponding to that directory I can enter it but the imagemap doesn't show (with the same error).

**Comment by zevv** [comment]
Hi Luca,

> The first is that the page doesn't specify the charset (utf-8 in my
> case) so the names appears garbled. If I manually select utf-8 in the
> browser they show correctly.

Good point, will add this.

> The second is that clicking on such a link I get the following error
> (the text of the link was "UB1_Completación"):

Which version was this, 1.0-rc1 or git latest? The CGI code was not
complete in the 1.0rc1 version, especially escaping of special
characters was not handled properly (or not done at all, actually).
I've put some work in this quit recently, can you check if git latest
works for you?

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by zevv** [comment]
Added the UTF-8 charset in b34fbd4, let me know if this fixes your problem.

**Comment by olivluca** [comment]
El 03/05/15 a les 07:37, zevv ha escrit:
> Hi Luca,
> 
>> The first is that the page doesn't specify the charset (utf-8 in my
>> case) so the names appears garbled. If I manually select utf-8 in the
>> browser they show correctly.
> 
> Good point, will add this.

Maybe that should be configurable. Nowadays most filesystem are utf-8
but they may be in any encoding (the names are just sequences of bytes
to the filesystem)

> 
>> The second is that clicking on such a link I get the following error
>> (the text of the link was "UB1_Completación"):
> 
> Which version was this, 1.0-rc1 or git latest? The CGI code was not
> complete in the 1.0rc1 version, especially escaping of special
> characters was not handled properly (or not done at all, actually).
> I've put some work in this quit recently, can you check if git latest
> works for you?

It was git latest (as of yesterday), 1.0-rc1 didn't have the --list
option. I pulled again today and, once it has finished indexing, I'll
try again.

**Comment by zevv** [comment]
> It was git latest (as of yesterday), 1.0-rc1 didn't have the --list
> option.

True

> I pulled again today and, once it has finished indexing, I'll try
> again.

Ok, thanks
 

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by olivluca** [comment]
This fixed the first problem but not the second.
If I manually correct in the url the i%ffffffc3%ffffffb3 to ó I can see the page (with the broken image since it still has the i%ffffffc3%ffffffb3, which I can correct and see the image)

**Comment by olivluca** [comment]
It also works if I simply remove the ffffff, i.e. from %ffffffc3%ffffffb3 to %c3%b3

**Comment by zevv** [comment]
* On 2015-05-03 12:17:59 +0200, Luca Olivetti wrote:
 
> It also works if I simply remove the ffffff, i.e. from %ffffffc3%ffffffb3 to %c3%b3

Should be fixed in 9f04fd1. No need to reindex, just update and compile
and the CGI should work.

Thanks for the report.

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by olivluca** [comment]
Now it works, thank you
