### ISSUE TITLE
info -b reports incorrect (truncated?) value

### ISSUE THREAD

**Issue by stuartthebruce** [zevv/duc#86]
duc info version 1.1 running on SL6 displays an incorrect value with the -b option, e.g.,

# /usr/local/bin/duc --version
duc version 1.1

# /usr/local/bin/duc info
Date       Time       Files    Dirs    Size Path
2015-05-10 19:23:01  308.2K    9.0K  120.5G /mnt/qfs1/ahnitz

# /usr/local/bin/duc info -b
Date       Time       Files    Dirs    Size Path
2015-05-10 19:23:01  308.2K    9.0K 1294179 /mnt/qfs1/ahnitz

Perhaps the Size display field is truncated when printed in --bytes mode?

Note, it would also be useful if the info command had the --apparent option, and if the Files and Dirs fields could also be printed as full machine parsable numbers without converting to K or similar.

Thanks.

**Comment by zevv** [comment]
* On 2015-05-11 05:19:35 +0200, stuartthebruce wrote:
 
> # /usr/local/bin/duc info -b
> Date       Time       Files    Dirs    Size Path
> 2015-05-10 19:23:01  308.2K    9.0K 1294179 /mnt/qfs1/ahnitz
> 
> Perhaps the Size display field is truncated when printed in --bytes mode?

Indeed.

> Note, it would also be useful if the info command had the --apparent
> option, and if the Files and Dirs fields could also be printed as full
> machine parsable numbers without converting to K or similar.

I agree with both, this will be the expected behaviour.

All of the above are fixed in git master. (The header and field width
can now differ when -b is given, I might fix this one day)

-- 
:wq
^X^Cy^K^X^C^C^C^C
