### ISSUE TITLE
Default path

### ISSUE THREAD

**Issue by stuartthebruce** [zevv/duc#91]
I think it makes sense to change the default path for most of the commands, e.g., ls, ui, gui, cgi, graph, to be the root path in the database rather than the CWD, which appears to be the case for version 1.2. If there are multiple paths in the specified database file then perhaps default to the first one returned by the info command.

**Comment by zevv** [comment]
It seems that there are two different views on this, depending on the
use case:

Other people have come up with the same question as you, to use the
indexed top path as default. The problem case is when there are more
indexed paths (as you already mentioned), which can of course be solved
pragmatically by simply using the first one in the list. The first path
in the index is not any more primary or important then the others, so
this might or might not be The Right Thing To Do for everyone.

I use duc myself often to navigate the current directory, and I like duc
to work as I expect general unix tools to work (ls, du, etc): explicitly
specify the path, or use the current path if no path is specified. To
mee this feels like the behaviour which shows the least surprise.

I understand the reason for your request, but I'm not sure if changing
the current behaviour is the best solution. Maybe we can come up with a
configuration option to let the user chose this; in your case you could
simple add this option in /etc/ducrc and have duc globally behave as you
would like.

What about something like the following global option:

```
--default-path=VAL  use the given path instead of the current directory when
                    quering the database with the `ls`, `ui`, `gui`, etc
                    commands. If VAL is the literal string `indexed`,
                    the first indexed path found in the database will be
                    used.
```

Any other ideas welcome.

**Comment by stuartthebruce** [comment]
> On May 13, 2015, at 11:49 PM, Ico Doornekamp <notifications@github.com> wrote:
> What about something like the following global option:
> 
> --default-path=VAL  use the given path instead of the current directory when
>                     quering the database with the `ls`, `ui`, `gui`, etc
>                     commands. If VAL is the literal string `indexed`,
>                     the first indexed path found in the database will be
>                     used.
Would this be an option to the index command that is stored in the
database file?
> Any other ideas welcome.
> 
Another random idea would be to keep the current default behavior but if
CWD is not found fail over to use the first indexed top path from the
database file?

In addition, how about enhancing the error message,
“Path XXX not found in database”
to include a list of the indexed top path(s).

Thanks.

--
Stuart Anderson  anderson@ligo.caltech.edu
http://www.ligo.caltech.edu/~anderson

**Comment by zevv** [comment]
* On 2015-05-14 23:26:02 +0200, stuartthebruce wrote:
 
> 
> > On May 13, 2015, at 11:49 PM, Ico Doornekamp <notifications@github.com> wrote:
> > What about something like the following global option:
> > 
> > --default-path=VAL  use the given path instead of the current directory when
> >                     quering the database with the `ls`, `ui`, `gui`, etc
> >                     commands. If VAL is the literal string `indexed`,
> >                     the first indexed path found in the database will be
> >                     used.

> Would this be an option to the index command that is stored in the
> database file?

I guess it would be global, so it applies to all querying commands, or
make it an option to gui, ui, xml, etc

I don't like the above though, but I have no better ideas for now.

> Another random idea would be to keep the current default behavior but if
> CWD is not found fail over to use the first indexed top path from the
> database file?

Possible, but I feel this also is a bit random; might surprise users
with unexpected behaviour.

> In addition, how about enhancing the error message, “Path XXX not
> found in database” to include a list of the indexed top path(s).

I'm note sure about listing all paths directly, but I could change the
error to indicate the user should look at the 'duc info' output to get a
list of paths.

Thanks,

-- 
:wq
^X^Cy^K^X^C^C^C^C
