### ISSUE TITLE
Databases are not portable between platforms.

### ISSUE THREAD

**Issue by zevv** [zevv/duc#92]
The current database is not portable between platforms with different int sizes and endianess. Find out what is needed to make this work. This includes

- The underlying database should be portable. (I suspect tokyocabinet is not)
- The contents of the database should be portable. At this time all data is written platform independent, expect for the index reports.

**Comment by stuartthebruce** [comment]
> On May 18, 2015, at 12:43 AM, Ico Doornekamp <notifications@github.com> wrote:
> 
> The current database is not portable between platforms with different int sizes and endianess. Find out what is needed to make this work. This includes
> 
> The underlying database should be portable. (I suspect tokyocabinet is not)
Do you know what needs to match here? I am trying to port between ELF 64-bit LSB AMD64 (Solaris) and ELF 64-bit LSB x86-64 (Linux), i.e., same endian, sizeof(int) and sizeof(long).

> The contents of the database should be portable. At this time all data is written platform independent, expect for the index reports.
I do indeed get a blank “duc info” output after copying database file between platforms.

Thanks.

--
Stuart Anderson  anderson@ligo.caltech.edu
http://www.ligo.caltech.edu/~anderson

**Comment by zevv** [comment]
master is now portable between solaris and linux using sqlite3 backend.

I'm not sure why tokyocabinet does not work, but this minimal test shows the problem lies indeed in tokyocabinet itself, not in duc:

- on Solaris, do `tcbmgr create test1`
- on Linux do `/opt/csw/bin/tcbmgr list test1`, this results in `/opt/csw/bin/tcbmgr: -: 5: invalid meta data`

The author of tokyocabinet recommends to use Kyotocabinet instead for various reasons. Not sure if Kyotocabinet is portable, it is not available on openocw anyway.

**Comment by stuartthebruce** [comment]
> On May 18, 2015, at 11:12 PM, Ico Doornekamp <notifications@github.com> wrote:
> 
> master is now portable between solaris and linux using sqlite3 backend.
> 

ui and gui are working for me now with both sqlite3 and tokyocabinet. However, in both cases the info command comes up empty.

> I'm not sure why tokyocabinet does not work, but this minimal test shows the problem lies indeed in tokyocabinet itself, not in duc:
> 	• on Solaris, do tcbmgr create test1

That creates a test1 file for me.

> 	• on Linux do /opt/csw/bin/tcbmgr list test1, this results in /opt/csw/bin/tcbmgr: -: 5: invalid meta data

Presumably you mean /usr/bin/tcbmgr on Linux. When I copy the solaris generated test1 file to a linux machine tcbmgr list there does not generate an error, I just get a prompt.

Thanks.

--
Stuart Anderson  anderson@ligo.caltech.edu
http://www.ligo.caltech.edu/~anderson

**Comment by zevv** [comment]
* On 2015-05-20 02:49:04 +0200, stuartthebruce wrote:
 
> ui and gui are working for me now with both sqlite3 and tokyocabinet.
> However, in both cases the info command comes up empty.

So there's still something different between your setup and mine. Could
you send me your sqlite db file so I can inspect why there is no report?

> > I'm not sure why tokyocabinet does not work, but this minimal test shows the problem lies indeed in tokyocabinet itself, not in duc:
> >     • on Solaris, do tcbmgr create test1
> 
> That creates a test1 file for me.
> 
> >     • on Linux do /opt/csw/bin/tcbmgr list test1, this results in /opt/csw/bin/tcbmgr: -: 5: invalid meta data
> 
> Presumably you mean /usr/bin/tcbmgr on Linux. When I copy the solaris generated test1 file to a linux machine tcbmgr list there does not generate an error, I just get a prompt.

Funny, what is your Linux distro?

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by stuartthebruce** [comment]
Here is the process I used to build on Solaris (SRU 11.2.10.5.0) and Linux (Scientific Linux 6),

git clone https://github.com/zevv/duc.git
cd duc
autoreconf --install
./configure --with-db-backend=sqlite3
make (on Linux and gmake on Solaris)

I then indexed the duc directory on the Solaris machine,

# ./duc index -v -x -p -d solaris.duc /root/duc
Writing to database "solaris.duc"
Indexed 148 files and 29 directories, (5.8MB apparent, 5.0MB actual) in 0.004478 secs.

# ./duc info -d solaris.duc
Date       Time       Files    Dirs    Size Path
2015-05-20 10:38:52     148      29    5.0M /root/duc

However, when I copy that to the Linux machine I get,
# ./duc info -d solaris.duc
Date       Time       Files    Dirs    Size Path
# ./duc gui -d solaris.duc
(generates working X11 graph)

I have posted a copy of the solaris.duc file at,
http://www.ligo.caltech.edu/~anderson/solaris.duc

Thanks.

**Comment by zevv** [comment]
> I have posted a copy of the solaris.duc file at,
> http://www.ligo.caltech.edu/~anderson/solaris.duc

Thanks, that was enlightening.
 
It takes some iterations, but we're getting there. Reports were
stored in a buffer of size PATH_MAX, which differs between solaris and
linux. I've changed this into a fixed platform-independent buffer size.

The usual routine: please pull master and retry!

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by stuartthebruce** [comment]
> On May 20, 2015, at 11:26 AM, Ico Doornekamp <notifications@github.com> wrote:
> 
> > I have posted a copy of the solaris.duc file at,
> > http://www.ligo.caltech.edu/~anderson/solaris.duc
> 
> Thanks, that was enlightening.
> 
> It takes some iterations, but we're getting there. Reports were
> stored in a buffer of size PATH_MAX, which differs between solaris and
> linux. I've changed this into a fixed platform-independent buffer size.
> 
> The usual routine: please pull master and retry!

That works, for both sqlite3 and tokyocabinet!

In particular, running “index” from a 32-bit ELF on Solaris and
then running “info” on a 64-bit ELF on Linux generates the same
information.

One remaining minor point, would it be possible to have configure
automatically add -R/opt/csw/lib option in addition to -L/opt/csw/lib?

If I run into any problems I will switch to a 64-bit ELF binary on
Solaris by running,
env PKG_CONFIG_PATH=/opt/csw/lib/pkgconfig CFLAGS=-m64 ./configure
and then manually re-running the final link command pointed at
the OpenCSW directory with the 64-bit versions of libtokyocabinet,
-L/opt/csw/lib/amd64 -R/opt/csw/lib/amd64

Many thanks in getting this to work. It will definitely be helpful
to have the large index commands run 10x faster on backend Solaris
file servers (rather than Linux NFS clients) and then provide cgi
functionality from a Linux Apache instance.

--
Stuart Anderson  anderson@ligo.caltech.edu
http://www.ligo.caltech.edu/~anderson

**Comment by zevv** [comment]
Closing this issue; I've created a separate issue for the -R option.
