### ISSUE TITLE
Add more information to --version output

### ISSUE THREAD

**Issue by stuartthebruce** [zevv/duc#93]
I think it would be useful to have git --version report more information, e.g.,
* The git branch and hash that was built
* Most if not all of the configuration information displayed by ./configure, especially the database backend choice, e.g.,

  configuration summary:

   - Package version: duc 1.2
   - Prefix: /usr/local
   - Database backend: tokyocabinet
   - GUI (X11) support: yes
   - UI (ncurses) support: yes
   - Graph drawing support: yes

**Comment by zevv** [comment]
Added the configure options. Git revision is tricky because this should not break builds if compiling from a release tarball. I'll figure that one out one day, but not this day.
