### ISSUE TITLE
Silent failure when reading a different database format

### ISSUE THREAD

**Issue by stuartthebruce** [zevv/duc#94]
If I run "info" against a tokyocabinet database file file an sqlite3 duc build it silently fails with null output rather than displaying an error message, e.g.,

# ./duc info -d solaris.db 
Date       Time       Files    Dirs    Size Path

Ideally this should report an error message indicating both the database format of the executable and the database file.

**Comment by zevv** [comment]
Fixed in 9907afd. 

sqlite3_open() does not always notice corrupt database files. We do a bugus query after database open to catch this error case
