### ISSUE TITLE
Silent failure for missing database file

### ISSUE THREAD

**Issue by stuartthebruce** [zevv/duc#95]
Running duc info against a non-existing database file results in creating a database file and displaying a null result, e.g.,

# ./duc info -d random_name
Date       Time       Files    Dirs    Size Path

# ls -l random_name
-rw-r--r--   1 root     root      131072 May 20 15:35 random_name

This seems counter intuitive to me.

Thanks.

**Comment by zevv** [comment]
Fixed with 82b7a7a. Problem was in the sqlite3 backend only.
