### ISSUE TITLE
tooltip display for center of graph

### ISSUE THREAD

**Issue by stuartthebruce** [zevv/duc#97]
I think it would be useful if tooltip displayed summary information in cgi mode when the cursor is over the central white circle.

**Comment by zevv** [comment]
Not sure what it should show. The current tooltip shows the path, type and size. The path for the center is already shown on top of the graph, the type is always a directory, and the size is already written in the center. Closing ticked for now. If the tooltip will ever show more info in the future there might be need for a tooltip in the center as well.
